### ISSUE TITLE
vue版本的option只能写在data里么？如果两个表格，第二个表格的查询参数需要第一个表格的数据，该怎么实现呢

### ISSUE THREAD

**Issue by cupPhone** [baukh789/GridManager#102]
问题一：
        vue版本的option只能写在data里么？如果两个表格，第二个表格的查询参数需要第一个表格的数据，该怎么实现呢？

问题二：
       vue的新版本在哪下载？

问题三：
      现在0.1.6版本的vue销毁方法不管用，怎么解决呢？元素能获取到

     在线等，急用

**Comment by baukh789** [comment]
- 下载最新的vue版本
```
npm install gridmanager-vue
```
- 自测过了，destroy生效
