### ISSUE TITLE
在哪儿下载未压缩的js和css，最新版本的。2.6.11

### ISSUE THREAD

**Issue by kavizzz** [baukh789/GridManager#107]
如题，求作者大发慈悲。

**Comment by baukh789** [comment]
所有的源码都在这个项目下，你所说的js和css都是打包之后的。
我并不是很明白，你想要做什么。
如果你要更改某些功能，通过更改未构建前的文件可能更便利些。
如果你仅仅只是想这样，那么你可以：
- fork项目
- 禁用 webpack-config.js下的`webpack.optimize.UglifyJsPlugin`
- 执行 npm run build
