### ISSUE TITLE
filter

### ISSUE THREAD

**Issue by 1444713101** [baukh789/GridManager#108]

**Comment by 1444713101** [comment]
filter 复选选中的值存在那个地方

**Comment by hueeicane** [comment]
前端能获取到参数。。。但是显示不出来

**Comment by hueeicane** [comment]
{"data":[{"tr_user_id":"9b4bd4a415704a37b29a6be9deec54f4","tr_user_name":"root","tr_user_password":"4QrcOUm6Wau+VuBX8g+IPg==","tr_user_status":"0","tr_user_nickname":"Admin","tr_user_avatar":"/images/faces/face1.jpg","tr_user_department":null,"tr_user_task":"80","tr_user_entryTime":"无","tr_user_introduction":"开心每一天","tr_user_sex":"男","department":{"tr_department_id":"0","tr_department_name":"管理员","tr_department_floor":"","tr_department_task":null,"tr_department_createT":"","tr_department_project":null,"tr_department_number":"0","tr_department_principal":""}}],"totals":10}

**Comment by baukh789** [comment]
检查以下配置项
- `columnData`
- `dataKey`
- `totalsKey`
或者你对照一下demo

**Comment by BoWang816** [comment]
getCheckedTr这个方法是获取当前选中的列, 返回的为数组格式的TR DOM节点，详细信息请看API：http://gridmanager.lovejavascript.com/api/index.html#query

getCheckedData这个方法是获取已经选中的行数据，但是获取的是所有选中的行数据，你不是单行数据

**Comment by BoWang816** [comment]
另外请更新至最新版本，目前最新版本是2.7.1

**Comment by hueeicane** [comment]
好的谢谢
