### ISSUE TITLE
静态数据支持分页吗

### ISSUE THREAD

**Issue by lifeisgood1990** [baukh789/GridManager#109]
我看demo静态数据分不了页

**Comment by BoWang816** [comment]
静态数据是不能支持分页的，翻页是发送请求重新获取数据的过程，你如果是静态数据的话，每次翻页就相当于获取的是重复的数据，所以并没有体现分页的效果；

如果想使用静态数据并且要产生分页效果，可以在静态数据中设置cPage的值，比如你发送请求是cPage为1，则静态数据返回的是某一段数据，如果cPage是2，则静态数据中需要返回另一段数据，这样才能看出是分页效果。

**Comment by lifeisgood1990** [comment]
好吧  我还是把数据传到后台 在获取下
