### ISSUE TITLE
关于Gridmanger 获取每行数据

### ISSUE THREAD

**Issue by lifeisgood1990** [baukh789/GridManager#11]
var rowVal = $('#tableWrap table').GM('getRowData', 'tr');
我以前是这样就可以获取 每行的数据 console.log("rowVal:"+rowVal.id)  
然后就可以获取想要的数据  现在3.0版本的 这样为啥获取不到？

**Comment by lifeisgood1990** [comment]
代码如下
 $("#tableWrap table").on("click","tbody tr",function(){
      var $this = $(this);
      var rowVal = $('#tableWrap table').GM('getRowData', 'tr');
      console.log("rowVal:"+rowVal.id)
})

**Comment by baukh789** [comment]
从版本2.1.8中移除了对jquery的依赖，完全使用原生JS实现。你可以使用如下原生的方式进行获取
`
var tableDOM = document.querySelector('table');
var tr = tableDOM.querySelector('tbody tr:first-child');
tableDOM.GM('getRowData', tr);
`
希望可以帮助到你。

**Comment by lifeisgood1990** [comment]
可以  谢谢了
