### ISSUE TITLE
bootstrap模态框内表格样式问题

### ISSUE THREAD

**Issue by bulusite** [baukh789/GridManager#111]
![image](https://user-images.githubusercontent.com/41330200/51007684-6d4a5d80-1583-11e9-9d06-867b9ae0c19c.png)
但是我页面大小一变就正常了
![image](https://user-images.githubusercontent.com/41330200/51007781-d0d48b00-1583-11e9-8106-e5e4e535ac03.png)

**Comment by baukh789** [comment]
你通过`GM.version`查看下当前的版本，如果不是最新版的升级下版本

**Comment by bulusite** [comment]
谢谢,我先试试

**Comment by bulusite** [comment]
@baukh789 谢谢了,问题解决了

**Comment by bulusite** [comment]
@baukh789 ,checkedAfter: function(event) {}这里是event 是不是变更了 event的值最新版是只带columnData的内容了吗

**Comment by baukh789** [comment]
是的, 你可以看一下更新文档
- `getCheckedData`: 返回值调整为仅返回在`columnData`中配置过的项，未配置的项将不再返回

你如果要使用其它项的值，可以通过返回的值自行查找。

**Comment by bulusite** [comment]
OK谢谢
