### ISSUE TITLE
showTh和hideTh的问题

### ISSUE THREAD

**Issue by bulusite** [baukh789/GridManager#112]
我用这两个方法的时候 列数据是显示和隐藏了 但是表头没有显示和隐藏

**Comment by bulusite** [comment]
var thList = document.querySelectorAll('table th');
是不是我要隐藏一列 然后要 thList 要传入对应的两个

**Comment by BoWang816** [comment]
showTh与hideTh方法是根据dom节点显示或隐藏对应的dom节点，你如果要隐藏某一列中表头和表格内数据列，需要给thList传入两个对应的值的。

另外，如果你想实现隐藏列表中表头和表格内容的显示与隐藏，可以使用列配置中的isShow属性，针对不同列使用isShow设置为true或false可以控制列的显示与隐藏。
![image](https://user-images.githubusercontent.com/26587649/51372531-8b423000-1b38-11e9-82b3-0ac8bc76720a.png)

**Comment by bulusite** [comment]
@BoWang816 谢谢,我知道怎么用
