### ISSUE TITLE
在同一页面内，如果渲染两个表格，那么第二个表格的表头会出现定宽的问题

### ISSUE THREAD

**Issue by Sunwendi** [baukh789/GridManager#113]
![image](https://user-images.githubusercontent.com/38480924/52104377-5ac4c080-2625-11e9-9d56-a0756c613c90.png)
这个图是第二个表格的图，如果滚动的话，就恢复正常，否则就会一直处于这个状态
![image](https://user-images.githubusercontent.com/38480924/52104456-abd4b480-2625-11e9-992a-deff861ce8e7.png)
是我哪里写的不对吗？

**Comment by baukh789** [comment]
可能是由版本问题导致的，这个现象在以前的某个版本确实存在，不过已经修复很久了。
你可以参考同页面多个表格的示例 [demo](http://develop.lovejavascript.com/node_modules/gridmanager/demo/demo3.html)

或者直接去看这个demo 的源码 [demo code](https://github.com/baukh789/GridManager/blob/master/src/demo/demo3.html)

**Comment by Sunwendi** [comment]
已经更新版本，这个问题解决了，但是更新后现在出现了一个新的问题，就是我的数据在剩下最后一条进行删除的时候，会出现点坐下角刷新不会刷新成空数据，还会存在这个数据，除非刷新页面才可以清除掉

**Comment by Sunwendi** [comment]
我这个删除逻辑什么的都写好了，所有其他的表格数据内容删除都没问题，都是表格省下最后一条数据时，删除也会执行，数据库已经清除了，但是页面上未刷新成功，对了，它会报错：请求数据失败！response中的data必须为数组类型，可通过配置项[dataKey]修改字段名。

**Comment by Sunwendi** [comment]
怎么说呢，就是多条数据的时候，都会完美的删除掉，但是如果数据只剩下一条，它就会挂掉了

**Comment by Sunwendi** [comment]
可以加个微信或者QQ详谈一下吗？微信：s978761  QQ：978761587

**Comment by Sunwendi** [comment]
问题已解决，非常感谢您的回答，以及您的框架
