### ISSUE TITLE
关于getCheckedData

### ISSUE THREAD

**Issue by bulusite** [baukh789/GridManager#119]
比如我第一页选了一条
这时候我翻页 第一页选中的效果还在,如果只想要单页选中的该怎么解决?
`GridManager.setCheckedData('test', []);`
除了这个办法还有其他办法吗

**Comment by baukh789** [comment]
如果你们不需要`分页后原选中效果存在`的效果，那么你找到的方法是对的。
你可以通过在事件`pagingBefore`中调用该方法进行清除。
但是从使用者的角度来看，保存住之前的选中效果是很必要的。
