### ISSUE TITLE
Vue项目：GridManager使用过程中遇到的问题

### ISSUE THREAD

**Issue by HduSy** [baukh789/GridManager#120]
您的Demo示例为表格顶部通栏不变的查询。我的项目中根据查询结果，每张表顶部通栏基本需重新定义。我尝试destroy原来的GridManager避免gridManagerName重复，之后再更新this.option里columnData为新的表头，接着init初始化。问题出现了，这时某行template返回的是<router-link>时并不会起效，查看前端代码，被渲染成<router-link>，与第一个GridManager中某行<router-link>不同（它会渲染成<a></a>）

**Comment by HduSy** [comment]
补充一点，函数也与前一个GridManager不共享

**Comment by baukh789** [comment]
需要确认一下，你说的顶部通栏是topFullColumn还是指的thead?

**Comment by BoWang816** [comment]
- - 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
