### ISSUE TITLE
新版本报错

### ISSUE THREAD

**Issue by Zsoner** [baukh789/GridManager#122]
![image](https://user-images.githubusercontent.com/11805413/54209887-7fac2d80-4519-11e9-9b83-47b66475eff3.png)
我引用的你的，应该是最近的版本

**Comment by baukh789** [comment]
首先谢谢你的反馈
是否可以将使用的方式或代码说明一下，只用这一个错误信息并无法判断原因。

**Comment by heriky** [comment]
@Zsoner 
![TIM截图20190313104029](https://user-images.githubusercontent.com/12195736/54249787-7c965900-457c-11e9-92a6-9937a8e5929c.png)
我也遇到了同样的问题。最终发现造成该问题的原因在于配置表格columnData时，某一项缺失key。grid-manager中配置列数据时，key值时必须且唯一的。你可以检查你的配置，为每一列都配置唯一key，然后再尝试。

**Comment by baukh789** [comment]
@heriky 是的，key值是必设项。
在接下来的版本，我将会把key值未设置的情况以错误的形式抛出。
这样就不再会有这种疑惑了。

**Comment by baukh789** [comment]
@Zsoner 昨天发布了小版本，把key值未设置的情况以错误的形式抛出。
详情可点击=> [2.7.6](http://gridmanager.lovejavascript.com/version/index.html)
