### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by bulusite** [baukh789/GridManager#123]
比如layui table的https://fly.layui.com/extend/tableMerge/
作者有没有这方面的想法

**Comment by baukh789** [comment]
感谢反馈。
这个功能我需要先调研一下使用场景，可行的话，将会进入开发计划。

**Comment by bulusite** [comment]
> 感谢反馈。
> 这个功能我需要先调研一下使用场景，可行的话，将会进入开发计划。

感谢大佬,来自一个弱鸡java开发
