### ISSUE TITLE
麻烦问下，这个插件有编辑功能吗？

### ISSUE THREAD

**Issue by xianggithubli** [baukh789/GridManager#124]
麻烦问下，这个插件有编辑功能吗？

**Comment by baukh789** [comment]
你可以参考下[示例](http://develop.lovejavascript.com/node_modules/gridmanager/demo/index.html)

**Comment by xianggithubli** [comment]
你是说给点击绑定一个自定义控件出来修改rowData吗？

**Comment by baukh789** [comment]
> 你是说给点击绑定一个自定义控件出来修改rowData吗？

是的，通过列模版进行自由配置。
