### ISSUE TITLE
destroy方法有问题

### ISSUE THREAD

**Issue by yaozhiying1995** [baukh789/GridManager#125]
destroy
消毁指定的GridManager实例
GridManager.destroy(table);
参数说明
table: 需要操作的table dom
-------------------------------------------
此种方式调用该方法报错：
![image](https://user-images.githubusercontent.com/26517419/55697804-aa44b580-59f5-11e9-96e3-3adf22610de8.png)
![image](https://user-images.githubusercontent.com/26517419/55697786-9bf69980-59f5-11e9-8fac-2048317ca049.png)

如果用文档中的方法调用：
![image](https://user-images.githubusercontent.com/26517419/55697830-c21c3980-59f5-11e9-8d87-75e37d18f080.png)
没有任何反应.......

**Comment by baukh789** [comment]
你可以查看一下这个里面的消毁实现[demo](http://develop.lovejavascript.com/node_modules/gridmanager/demo/index.html)

另外，你需要确认一下当前的版本。
destroy是v2.5.0新增的方法，且在v2.7.5进行了调整。
