### ISSUE TITLE
滚动条的问题

### ISSUE THREAD

**Issue by Ancient-Ares** [baukh789/GridManager#126]
分页后： 第一页滚动条拉到最下面，点击第二页，滚动条还是在最下面。应该重置滚动条的位置到最上面。

**Comment by baukh789** [comment]
谢谢反馈，你说的这个现像是存在的。
待确认可行性后，我会将该问题列入修复计划。
到时我会在这里回复修复结果。

**Comment by baukh789** [comment]
@Ancient-Ares 
新版本已对该问题实现了优化，版本号v2.8.0
