### ISSUE TITLE
样式的问题

### ISSUE THREAD

**Issue by bulusite** [baukh789/GridManager#127]
如图,用的是最新版 2.8.0
![微信截图_20190507112256](https://user-images.githubusercontent.com/41330200/57269622-bab28380-70ba-11e9-91aa-1d301db84037.png)

**Comment by baukh789** [comment]
请附带一下配置项

**Comment by bulusite** [comment]
> 请附带一下配置项

```
        document.querySelector('table[grid-manager="table"]').GM('init',{
            ajax_data: 'singlewindow/decApi'
            ,ajax_type: 'POST'
            ,emptyTemplate: '<div class="gm-emptyTemplate">暂无数据</div>'
            ,supportAjaxPage: true//分页
            // ,supportAutoOrder: false
            // ,supportAdjust: false
            // ,supportDrag: false
            ,height: '850px'
            ,columnData: [
                {key: 'id',isShow:true,text: '操作',align:'center',template:
                    function(nodeData, rowData){
                        return '<span class="layui-btn layui-btn-xs layui-btn-normal operation" data-id="'+nodeData+'" data-hetonghao="'+rowData.hetonghao+'">操作</span>'
                    }
                },
                {key: 'status',align:'center',text: '报关单状态'},
                {key: 'hetonghao',align:'center',text: '合同号'},
                {key: 'guihao',align:'center',text: '柜号'},
                {key: 'kehu',align:'center',text: '客户'},
                {key: 'creater',align:'center',text: '创建者'},
                {key: 'gmt_create',align:'center',text: '创建时间'},
                {key: 'updater',align:'center',text: '更新者'},
                {key: 'gmt_modified',align:'center',text: '更新时间'}
            ],
            ajax_success:function(data){
                entQualifData = JSON.parse(data).data;
                console.info(entQualifData,"清除选项")
                GridManager.setCheckedData("table", []);
            }
        })
```

**Comment by baukh789** [comment]
你的页面中是否存在多个grid-manager="table"的实例，如果是的话，需要将这个字段唯一化。

**Comment by bulusite** [comment]
> 你的页面中是否存在多个grid-manager="table"的实例，如果是的话，需要将这个字段唯一化。

就一个

**Comment by baukh789** [comment]
@bulusite 我刚去调试了一下，并没有复现。
你可以首先排除以下问题来进行确认:
- 是每一个表都出问题，还是仅这一个表出问题。
- 是否有其它样式冲突问题

**Comment by bulusite** [comment]
> @bulusite 我刚去调试了一下，并没有复现。
> 你可以首先排除以下问题来进行确认:
> 
> * 是每一个表都出问题，还是仅这一个表出问题。
> * 是否有其它样式冲突问题
![微信截图_20190509114009](https://user-images.githubusercontent.com/41330200/57425833-70164000-724f-11e9-9b71-5c80f8e9b953.png)

**Comment by baukh789** [comment]
有点诡异，并没有复现你的情况
你可以与[demo](http://develop.lovejavascript.com/node_modules/gridmanager/demo/demo1.html)的使用方式比对一下。

**Comment by BoWang816** [comment]
看项目可能是你使用了layui，导致里面的某些样式冲突了。可以尝试将其他样式先全部注释再看是否正常

**Comment by bulusite** [comment]
> 看项目可能是你使用了layui，导致里面的某些样式冲突了。可以尝试将其他样式先全部注释再看是否正常

我后面截图的时候把其他css去掉了

**Comment by bulusite** [comment]
> 有点诡异，并没有复现你的情况
> 你可以与[demo](http://develop.lovejavascript.com/node_modules/gridmanager/demo/demo1.html)的使用方式比对一下。

我再试试

**Comment by bulusite** [comment]
还是之前那个问题
![127](https://user-images.githubusercontent.com/41330200/58151398-29d3ce80-7c9c-11e9-9778-acf29107de68.png)
![192](https://user-images.githubusercontent.com/41330200/58151409-30624600-7c9c-11e9-9e36-b3c07b744aae.png)
我发现使用127.0.0.1的话我的样式是正常的
但是使用192.168.15.249样式却有异样，列越多，列差越大

**Comment by BoWang816** [comment]
192.168.15.249应该是你本地的局域网IP地址吧，你可以试着清理一下浏览器缓存，看是否是因为之前有使用这个IP地址，导致有缓存的存在

**Comment by bulusite** [comment]
> 192.168.15.249应该是你本地的局域网IP地址吧，你可以试着清理一下浏览器缓存，看是否是因为之前有使用这个IP地址，导致有缓存的存在

刚才试了一下，我把缓存全清除了，还是有同样问题 而且我浏览器一直是disable cache选中的

**Comment by bulusite** [comment]
前面那个问题解决了，但是又发现一个问题
我在ajax_success方法里面使用了
```
GM.hideTh(table,thHide);
GM.showTh(table,thShow);
```
![微信截图_20190522144924](https://user-images.githubusercontent.com/41330200/58153371-6d7d0700-7ca1-11e9-83e2-c1a98f22501d.png)

我们线上使用的是2.7.1没有问题，但是我本地换成了2.8.3发现有这个问题

**Comment by baukh789** [comment]
你把你的gridManagerName设置成唯一的，同一项目下不要出现重复值。
