### ISSUE TITLE
exportGridToXls

### ISSUE THREAD

**Issue by BlueDemonChicken** [baukh789/GridManager#128]

**Comment by BlueDemonChicken** [comment]
exportGridToXls右键会默认指定一个文件名字，请问，我可以在初始化的时候，修改这个方法吗？

**Comment by baukh789** [comment]
右键导出功能，导出文件名默认为配置项gridManagerName的值, 如果使用静态导出可以直接修改该字段。
另: 导出功能，建议使用blob方式。

**Comment by BlueDemonChicken** [comment]
收到回复，谢谢您，是的。我使用右键static导出的时候如果想自定义文件的名字的时候，是不是不能通过某种配置直接重写默认的导出方法以边来修改下载文件名呢？

**Comment by baukh789** [comment]
@BlueDemonChicken 是这样的

**Comment by BlueDemonChicken** [comment]
好的，那么通过非blob模式是否可以修改动态设定文件名字呢？

**Comment by baukh789** [comment]
也是不可以的，你可以详细的描述下使用场景。
可行的话，我将会把这个功能进行完善。

**Comment by BlueDemonChicken** [comment]
比如下载的时候，举个例子：一般特别是财务之类的信息等等其他数据导出功能，我下载的时候是有查询的，一般财务肯定是希望导出的文件名最好是当前操作日期或者时间来命名的。这个时候就需要这里的export方法可以提供给开发者来重命名（我们肯定是不希望用默认的某个名字）。谢谢。

**Comment by baukh789** [comment]
这个功能近期会发布，发布后我会在这里回复你。

**Comment by BlueDemonChicken** [comment]
好的，谢谢。

**Comment by hellozhoujiang** [comment]
如何使表格下方变成下拉方式显示，而不是滚轮的方式

**Comment by baukh789** [comment]
@BlueDemonChicken 
该功能已发布，请参考[API](http://gridmanager.lovejavascript.com/api/index.html#exportConfig)

使用方法如下
```
exportConfig: {
    fileName: query => {
        const date = new Date();
        let fileName = `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}`;
        for (let key in query) {
            fileName = `${fileName}-${key}=${query[key]}`;
        }
        return fileName;
    }
}
```

**Comment by baukh789** [comment]
@hellozhoujiang 不是很明白你的意思

**Comment by BlueDemonChicken** [comment]
好的，收到，谢谢，幸苦了

**Comment by baukh789** [comment]
@BlueDemonChicken 喜欢的话就推荐下，顺便点个`star`

**Comment by BlueDemonChicken** [comment]
好的，已star

**Comment by hellozhoujiang** [comment]
> @hellozhoujiang 不是很明白你的意思

这个问题已经解决了，感谢作者的关注

**Comment by hellozhoujiang** [comment]
您好，在使用本插件的过程中遇到以下问题，阅读demo和API后还有些许的疑问，请问要如何解决
（1）换肤功能是否已经上线，如何使用？
（2）国际化时如何改变columnData中的text值，（demo中的国际化text的值都是固定写好的）
（3）在vue中使用this.option.i18n=“en-us”无法修改实现国际化的转换，请问要怎样操作实现点击按钮就能进行国际化的转变
以上
打扰之处请多多见谅。

**Comment by BoWang816** [comment]
1、项目没有单独的换肤功能，但是有部分皮肤插件可供选择安装；可查看https://github.com/baukh789/GridManager readme中的皮肤；

2、使用国际化时，需要设置 i18n:字段配置为'en-us'，并且需要你自己去配置columData中每个text字段为英文状态；

**Comment by hellozhoujiang** [comment]
> 1、项目没有单独的换肤功能，但是有部分皮肤插件可供选择安装；可查看https://github.com/baukh789/GridManager readme中的皮肤；
> 
> 2、使用国际化时，需要设置 i18n:字段配置为'en-us'，并且需要你自己去配置columData中每个text字段为英文状态；

好的，谢谢

**Comment by BlueDemonChicken** [comment]
您好，还是想在之前的导出功能上再问个问题：
我看到右键菜单是可以屏蔽列的，如果导出的时候也能够根据需要（就是程序手动配置需要导出的列）。这样就更加完美了。以为有的时候需要展示的列和需要下载导出的列是不一样的。有的列仅仅是展示，导出是没有意义的。这个时候，默认程序导出的时候如果在exportConfig里面可以配置列是否允许导出，那就完美了。

**Comment by baukh789** [comment]
你可以通过exportConfig.handler，将需要导出的列以参数的形式传至服务端来实现这个功能
