### ISSUE TITLE
分页的页数记录

### ISSUE THREAD

**Issue by zyt61146** [baukh789/GridManager#129]
你好，有个问题需要请教。现在想实现对分页的页数进行记录的功能。例如：我进入列表的第二页点击某一列的操作按钮进入编辑页面后返回之前页面就会进入第一页，期望返回到第二页。我在调用pagingAfter这个事件的时候可以看到是第几页，我存起来，从详情页返回到列表页的时候，不知道怎么把这个页面传给表格组件？

**Comment by BoWang816** [comment]
在API文档中，
refreshGrid方法：http://gridmanager.lovejavascript.com/api/index.html#refreshGrid

可以配置相关的参数

**Comment by cafugiggs** [comment]
麻烦能给出在vue中的具体写法吗

**Comment by baukh789** [comment]
vue 项目请看这里 [GridManager-Vue](https://github.com/baukh789/GridManager-Vue)
vue版本除了在columnData.text columnData.template topFullColumn.template中可以使用vue模版外，其它使用方式与GridManager相同
