### ISSUE TITLE
分页条无法显示

### ISSUE THREAD

**Issue by fruitdish** [baukh789/GridManager#13]
GridManager的作者你好，我对你的GridManager的插件非常感兴趣，这个插件功能十分强大。不过我在使用的过程中出现了一些问题，我的分页栏显示不出来，我认为我该加的参数（supportAjaxPage）都添加了但是没有效果。我想请问下作者如何解决。

**Comment by baukh789** [comment]
确认下数据格式是否包含data及totals， 如下所示
![image](https://cloud.githubusercontent.com/assets/11342827/26334856/83e4ec2e-3f9a-11e7-8802-49cffdec9516.png)

**Comment by fruitdish** [comment]
抱歉，那么晚才回复您的邮件。按照你的方式我去重新比对了我的数据，发现是因为后台传输的POJO转换JSON的时候，totals这个属性少了s。这是我的不细心造成的。
您的插件很好用，为您点赞



pengguo1996@gmail.com
 
发件人： 拭目以待
发送时间： 2017-05-23 09:31
收件人： baukh789/GridManager
抄送： fruitdish; Author
主题： Re: [baukh789/GridManager] 分页条无法显示 (#13)
确认下数据格式是否包含data及totals， 如下所示
