### ISSUE TITLE
使用ajax_url请求get类型的动态数据，pageSize无效

### ISSUE THREAD

**Issue by xiavia** [baukh789/GridManager#133]
数据是直接从数据库获取的，数据末尾添加了totals总数后，可以显示分页效果，但是当前页加载了所有的数据，pageSize设置为和sizeData相同的10条后，还是显示所有数据400多条。

还有一个问题，筛选条件不生效是什么原因？

**Comment by baukh789** [comment]
后端需要通过解析查询参数、分页参数，并通过参数返回相应页的数据。

**Comment by xiavia** [comment]
谢谢




------------------ 原始邮件 ------------------
发件人: "拭目以待"<notifications@github.com>;
发送时间: 2019年7月10日(星期三) 下午3:30
收件人: "baukh789/GridManager"<GridManager@noreply.github.com>;
抄送: "学员"<502091751@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [baukh789/GridManager] 使用ajax_url请求get类型的动态数据，pageSize无效 (#133)




后端需要通过解析查询参数、分页参数，并通过参数返回相应页的数据。

**Comment by xiavia** [comment]
大神你好，我还有一个问题想要请教一下
在每一列的列名区域点击右键出现对应列的选择筛选条件是通过什么方法实现的？

**Comment by baukh789** [comment]
请参考[columnData](http://gridmanager.lovejavascript.com/api/index.html#columnData) 中的filter配置

**Comment by xiavia** [comment]
谢谢




------------------ 原始邮件 ------------------
发件人: "拭目以待"<notifications@github.com>;
发送时间: 2019年7月12日(星期五) 上午9:41
收件人: "baukh789/GridManager"<GridManager@noreply.github.com>;
抄送: "学员"<502091751@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [baukh789/GridManager] 使用ajax_url请求get类型的动态数据，pageSize无效 (#133)




请参考columnData 中的filter配置

**Comment by xiavia** [comment]
您好，我在用filter时遇到了一个问题如下，大神能否帮忙解答：：



对比了网上的demo，对于这个参数row比较疑惑，不知道问题出在哪里。。。
------------------ 原始邮件 ------------------
发件人: "拭目以待"<notifications@github.com>;
发送时间: 2019年7月12日(星期五) 上午9:41
收件人: "baukh789/GridManager"<GridManager@noreply.github.com>;
抄送: "学员"<502091751@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [baukh789/GridManager] 使用ajax_url请求get类型的动态数据，pageSize无效 (#133)




请参考columnData 中的filter配置

**Comment by baukh789** [comment]
rowData是当前单元格所在行的渲染数据
