### ISSUE TITLE
关于在vue-cli使用的问题

### ISSUE THREAD

**Issue by 523600610** [baukh789/GridManager#134]
1.You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

2.this.$el.GM is not a function

你好，请问一下引用了列子，一直报这两个错，是为什么呢

**Comment by baukh789** [comment]
需要确认两个事项
- vue版本需要安装gridmanager-vue而不是gridmanager
- 现仅支持vue2

请参考[vue 版](https://github.com/baukh789/GridManager-Vue)使用方式。

**Comment by 523600610** [comment]
> 需要确认两个事项
> 
> * VUE版本需要安装gridmanager-VUE而不是gridmanager
> * 现仅支持vue2
> 
> 请参考[vue版](https://github.com/baukh789/GridManager-Vue)使用方式。

你好，我安装的是gridmanager-vue，引起那两个报错，是因为版本的问题吗？

**Comment by baukh789** [comment]
https://github.com/baukh789/GridManager-Vue/blob/master/src/demo/index.html
