### ISSUE TITLE
template中定义click事件无效

### ISSUE THREAD

**Issue by QueastZero** [baukh789/GridManager#135]
<el-button type="primary" size="mini" @click="toEditor(row)">编辑</el-button>

报错信息:TypeError: toEditor is not a function

**Comment by baukh789** [comment]
有以下几个事项需要注意
- 请确认你所使用的框架与所安装的版本一致，如果是vue需要安装gridmanager-vue而不是gridmanager
- 当前使用的事件函数是否在methods中声明

可以参考下 [demo](https://github.com/baukh789/GridManager-Vue/blob/master/src/demo/app.js)
