### ISSUE TITLE
请问是否能自定义表头

### ISSUE THREAD

**Issue by zhoulijuanmiao** [baukh789/GridManager#137]

**Comment by baukh789** [comment]
请参考 [columnData](http://gridmanager.lovejavascript.com/api/index.html#columnData) 下的text属性

**Comment by shan33** [comment]
请问表头的背景颜色直接修改background吗？
skinClassName是要涵盖所有的类吗？

**Comment by baukh789** [comment]
@shan33 
你可以直接通过样式覆盖进行修改，也可以通过`skinClassName`定义一组皮肤进行修改。

如果你们有独特的样式需求，建议通过`skinClassName`进行皮肤定义; 可参考其它皮肤做为示例:
- [ccms-skin](https://github.com/BoWang816/GridManager-ccms-skin)
- [element-skin](https://github.com/xtfan21/GridManager-element-skin)

**Comment by shan33** [comment]
> @shan33
> 你可以直接通过样式覆盖进行修改，也可以通过`skinClassName`定义一组皮肤进行修改。
> 
> 如果你们有独特的样式需求，建议通过`skinClassName`进行皮肤定义; 可参考其它皮肤做为示例:
> 
> * [ccms-skin](https://github.com/BoWang816/GridManager-ccms-skin)
> * [element-skin](https://github.com/xtfan21/GridManager-element-skin)

我们也不算有特殊的要求，主要是 设计的时候 表头是绿色的，其他的就用原版就可以。
需要改动样式的地方很小，所以才想有没有比较简单一下的修改。感觉文档里面的skinClassName属性不是很清晰。

**Comment by baukh789** [comment]
@shan33 `skinClassName `是为了方便使用者拥有一套自已的表格皮肤，这样自定义的样式比较容易维护。
