### ISSUE TITLE
请问支持定制吗，给您126邮箱发了一份邮件

### ISSUE THREAD

**Issue by yangyuanlife** [baukh789/GridManager#139]

**Comment by baukh789** [comment]
如果仅是样式问题，建议参考 [ccms-skin](https://github.com/BoWang816/GridManager-ccms-skin) 与 [element-skin](https://github.com/xtfan21/GridManager-element-skin)。
如果改动比较大，可以选择fork，然后进行自定义开发。

**Comment by yangyuanlife** [comment]
不是，是功能上的问题，比起多表头，锁定接，还有列过滤扩展，还有导出pdf等

**Comment by baukh789** [comment]
@yangyuanlife 暂时不支持定制开发，这些功能你可以fork后进行实现。
