### ISSUE TITLE
关于初次加载  直接跳转指定页码

### ISSUE THREAD

**Issue by lifeisgood1990** [baukh789/GridManager#14]
由于页面大小问题  页码只能显示前几条 12345******100 最后一页   
但我想在页面初次加载时跳转到指定页码 
$("ul.pagination").find("li[cPage="+cPage+"]").click(); 
但当cPage为**里面的页码时  是不能跳转的 
 我想知道还有什么办法解决这个问题 谢谢

**Comment by baukh789** [comment]
初次进入时， 并没有可以指定页码的参数。
我不是很明白，你所讲的【但当cPage为里面的页码时】指的是什么。

**Comment by lifeisgood1990** [comment]
就是省略的那些页码  like 首页 上一页 123*100 下一页 尾页 
我想在ajax_complete 完成时跳转指定的页码  
但要跳转的页码在页码条中没有显示；
比如我想跳转第20页 就不行
跳转第3页就可以

**Comment by baukh789** [comment]
这个需求没有对应公开方法，暂时不能通过配置和公开方法进行实现。
