### ISSUE TITLE
层主考虑针对多表头问题吗？ 

### ISSUE THREAD

**Issue by shan33** [baukh789/GridManager#141]
类似这样
![image](https://user-images.githubusercontent.com/14146319/67281703-99c3da80-f502-11e9-9a97-07767e30b660.png)

**Comment by baukh789** [comment]
这种形式的，你可以通过配置模板进行实现。
你可以在这里找到类似的[demo](http://develop.lovejavascript.com/)

**Comment by shan33** [comment]
我可以根据text的模板配置头部成这个样子，但是下面对应的应该是两个td表格，我修改表头模板对应的下面只是一个表格

**Comment by baukh789** [comment]
你可以通过`columnData.template`配置与text一样的分割，text与template是一个灵活的参数。
另外问下，你使用的是哪个框架下的gridmanager？

**Comment by shan33** [comment]
> 你可以通过`columnData.template`配置与text一样的分割，text与template是一个灵活的参数。
> 另外问下，你使用的是哪个框架下的gridmanager？

react的

**Comment by shan33** [comment]
> > 你可以通过`columnData.template`配置与text一样的分割，text与template是一个灵活的参数。
> > 另外问下，你使用的是哪个框架下的gridmanager？
> 
> react的

你的意思是  text 用来配置 th的分割吗， template用来分割下面的td吗  感觉好像可行的样子
