### ISSUE TITLE
请问渲染表格成功之后的回调是callback吗？

### ISSUE THREAD

**Issue by miluluyo** [baukh789/GridManager#142]
如果是callback的话，假设在里面写了一个alert，为何渲染完毕后不显示？
如果不是callback的话，渲染完毕后有调用的方法吗？（找了半天没找到，求告知！）
打扰您了 谢谢~

**Comment by baukh789** [comment]
@miluluyo 你所使用的是哪个前端框架，当前GridManager的版本是多少。
是否可以提供使用的方式，因为我刚在本地试了下是可以的。

**Comment by miluluyo** [comment]
@baukh789 好像是17/10/26的，我重新试一下最新版本的~

**Comment by miluluyo** [comment]
版本号问题，使用最新版本，回调顺序问题已解决~
