### ISSUE TITLE
怎样使用自己的表格数据，测试了表格显示空白

### ISSUE THREAD

**Issue by honwer** [baukh789/GridManager#143]
![image](https://user-images.githubusercontent.com/41855895/69726930-7bce4300-115c-11ea-8c98-f93744d9429b.png)

我把示例数据原样复制下来，另存为一个json文件，挂在我自己的域名地址里面，替换这个数据的调用地址，为什么整个表格空白了不出数据，小白问题，望大佬赐教

**Comment by BoWang816** [comment]
参考：http://gridmanager.lovejavascript.com/api/index.html#ajaxData

保证你的文件格式正确，以及文件路径正确

**Comment by honwer** [comment]
![image](https://user-images.githubusercontent.com/41855895/69791307-2f880f00-11ff-11ea-8746-154cee7e0a97.png)

帮我看一下格式对不对

![image](https://user-images.githubusercontent.com/41855895/69791347-4b8bb080-11ff-11ea-8c6f-8dc05d248317.png)

也能在浏览器访问

![image](https://user-images.githubusercontent.com/41855895/69791374-5cd4bd00-11ff-11ea-87d3-ca73e57424e4.png)
![image](https://user-images.githubusercontent.com/41855895/69791417-75dd6e00-11ff-11ea-85e9-8ec332e0b4ef.png)

**Comment by baukh789** [comment]
@honwer 这个文档中有介绍的，function 的返回格式分三种: url string, responseData, promise。
你现在使用的并不是url string，而是一个静态json地址。

**Comment by BoWang816** [comment]
可以使用
https://www.fastmock.site/
模拟数据，通过url 接口的方式返回你需要的数据，静态的json地址是不能这样的使用的，你如果要使用静态的json，需要在本地进行

**Comment by honwer** [comment]
![image](https://user-images.githubusercontent.com/41855895/69800394-1e93c980-1210-11ea-85cc-25e78f44daa9.png)

我用这种方式可以显示自定义数据了，但是搜索条件不起作用了

    $scope.onSearch = () => {
        console.log('onSearch');
        $gridManager.setQuery('testAngular', $scope.searchForm);
    };

        setQuery: {
            key: 'setQuery',
            relyInit: true,
            title: '更改在生成组件时所配置的参数query',
            code: `$gridManager.setQuery('${$scope.gridManagerName}', {'userName':'baukh','sex':'男'});`
        },

是跟这两个地方有关吗，要怎么修改

**Comment by baukh789** [comment]
setQuery需要通过ajaxData进行对应的数据返回

**Comment by honwer** [comment]
![image](https://user-images.githubusercontent.com/41855895/69811146-66bee600-1228-11ea-8ccc-ea266bfbf23c.png)
![image](https://user-images.githubusercontent.com/41855895/69811189-85bd7800-1228-11ea-9a78-a426d96c421d.png)

是这样对应的吗
