### ISSUE TITLE
选中行数据，缓存问题

### ISSUE THREAD

**Issue by miluluyo** [baukh789/GridManager#145]
我又来提问了哈，
当前选中的行数据 （GridManager.getCheckedData(table)），
然后刷新后表格后（table.GM('refreshGrid',false)），

获取的数据是有缓存的，就是获取到了上一次选中的数据加上当前选中的数据，

如何解决这个问题呢？

**Comment by baukh789** [comment]
这个是正常的情况，刷新后并不会清除当前已经选中的项，这可以保证在分页时继续保存选中数据。
如果存在需要清除的情况，可以通过`GridManager.setCheckedData(gridManagerName, []); `清空选中数据

还有个建议，尽量使用`GridManager.setCheckedData`的调用方式，而不是使用`table.GM`

**Comment by miluluyo** [comment]
嗯嗯，已解决，谢谢你~
