### ISSUE TITLE
columnData要如何动态地更改啊。。。

### ISSUE THREAD

**Issue by YOUYEde** [baukh789/GridManager#149]
如题。
使用的是react，我的方法是组件的state中设置Columdata，初始为空。
componentdidmount中读取服务端数据，setstate更新columndata（可能抛弃之前的数据，有完全新的列数据），但是总是报错，定位到的是gridmanagerreact.js中的updateReactTemplate方法，其中“columnMap[item.key].text = item.text”,这一句总报错“can not set property text of undefined”，所以意思是columnMap中并没有item.key这一项。
官方api的方式也用过了，例如refresh或者render，但是都不行。。
实在不懂怎么更新columnData，希望作者能帮助下，提供个大概的模板例子，谢谢！！

**Comment by baukh789** [comment]
columnData是初始化时所必须存在的数据，不可为空。
像你所提到的情景，存在 columnData初始为空与变更的情况，你需要将获取columnData的操作前置于组件渲染之前。

**Comment by YOUYEde** [comment]
> 数据，不可为空。

**Comment by YOUYEde** [comment]
作者你好，感觉看api文档，方法里面貌似只有renderGrid和refreshGrid能实现更改columnData，我之前也一直这么调用的，但总是遇到上面说的问题。看了源码才发现，需要用到setSettings函数，最后相当于自己去定制一个方法。
总而言之，作者你实际上并没有提供columnData修改的接口，不知道理解得对不对。
ajaxData倒是有很方便的接口“setAjaxData”，我感觉columnData也是很有可能经常变化的，所以希望作者能改进下，提供一个方便的接口。谢谢！！

**Comment by baukh789** [comment]
renderGrid和refreshGrid能实现更改columnData这两个方法是使用现有的columnData进行刷新操作。
不同的是renderGrid用现有用数据，refreshGrid重新获取数据。
columnData不可删减是因为columnData是做为一个基础的存在，在初始化时需要通过columnData对表格进行基础的配置。

setSettings函数是为跨框架时使用的，并不对外透出。也不建议你使用该方法，这个方法会对已实例的对像进行修改。

对于动态列，做到以下两点是可以达到期望效果的:
- 在获取到columnData之后，再触发表格的渲染
- 在需要更新columnData时，触发表格的销毁和再次渲染
