### ISSUE TITLE
拖拽功能

### ISSUE THREAD

**Issue by SixgodIMiss** [baukh789/GridManager#15]
当表格在x轴上有滚动条时，拖拽列，该列不会紧跟鼠标位置移动，而是跟鼠标位置在x轴方向上有一定距离的位移

**Comment by baukh789** [comment]
![image](https://user-images.githubusercontent.com/11342827/27063438-6293861c-5024-11e7-9f57-79aa52c436cc.png)
你通过上面的例子，查看下你当前的版本号是否为2.3.1.

**Comment by SixgodIMiss** [comment]
下的是2.3.1，但输出的是2.3.0

**Comment by baukh789** [comment]
你暂时先禁用掉拖拽功能，我新版本发布后后回在这里回复你。

**Comment by SixgodIMiss** [comment]
OK

**Comment by baukh789** [comment]
已经发布，请下载最新版本v2.3.9
