### ISSUE TITLE
表格列宽度拖拽式调整的形式

### ISSUE THREAD

**Issue by xuanyangdear** [baukh789/GridManager#151]
请问作者后续会考虑 "某些情况下，表格列宽调整的时候，不影响下一个单元格所在列的宽度"吗？
因为表格渲染不出现滚动条的时候，把某一列的宽度拉大（它的下一列刚好是最小宽度了），这时候表格就会出现滚动条，用户这个时候无法再通过拖拽把表格拉回没有滚动条的状态。
个人目前感觉比较好的体验是当表格没有出现滚动条的时候，把某一列拉更大，下一列不会被影响，而且可以通过拉小列宽可以把表格恢复到没有滚动条；当表格没有滚动条的时候，拉小列宽，那么下一列可以被影响列宽变大。
thanks.

**Comment by baukh789** [comment]
这里存在一个问题点，组件并不能确认用户当前是想将这一列缩小还是要将表格恢复至没有滚动条的状态。
如果存在这种需求，可以在表格宽度调整事件中调用`resetLayout()`函数实现清除滚动条的效果。

**Comment by xuanyangdear** [comment]
大多数情况下，主要是想保留之前操作列的宽度，比如说刚拉好的某一列到特定宽度后，但是后面的其他列的宽度拉拽影响到了前面操作完的列宽。

**Comment by baukh789** [comment]
好的，谢谢提的建议

**Comment by baukh789** [comment]
@xuanyangdear 宽度调整的交互在 v2.12.0版本中已经调整，类excel的交互。
