### ISSUE TITLE
表格区域高度随表格内容自动变化

### ISSUE THREAD

**Issue by sumy7** [baukh789/GridManager#152]
最近实现一个填写参数的功能，点击添加按钮之后增加一行，表格区域的高度随着表格行数进行变化。固定表格高度出现滚动条对于用户体验不友好。

![image](https://user-images.githubusercontent.com/3841747/75957645-6607b100-5ef5-11ea-9d87-38c8e2b7f7b8.png)

查看文档，对于高度的设置是

> 配置表格区域的高度,，需要带单位，超过这个高度会出现滚动条。支持以下写法:
> 1. '100px' 
> 2. '50%'
> 3. '100% - 40px'
> 4.'100vh - 64px - 57px'

没有自动改变高度的配置方法。

我的实现方案是通过JS修改表格 `.table-wrap` 和 `.table-div` 的 style，高度设置为auto

```javascript
that.$el.querySelector(".table-wrap").style['height'] = 'auto';
that.$el.querySelector(".table-div").style['height'] = 'auto';
```

请问表格目前本身能支持这个效果吗？如果没有能考虑下这个配置参数的需求吗？谢谢

**Comment by baukh789** [comment]
可以将设置height: 100%，表格的高度将为父容易的高度控制。
你可以将table所在的父容器的高度调整为auto即可解决。

**Comment by sumy7** [comment]
你的方案我在jsfiddle测试了是可行的，但是放在项目里就有问题。

因为表格在dialog中，所以最外层容器有一个height: 750px的高度。

```
---------------------
|  #container       |
| height: 750px;    |
| |--------------|  |
| | .table-parent|  |
| | |----------| |  |
| | | table    | |  |
---------------------
```

这样设置table height:100%之后，表格的高度就变成最外层容器的750px了，即使将.table-parent设置为height: auto; position: relative; 也是无效。

不知道是哪里影响了。

**Comment by baukh789** [comment]
外部容器的高度需要为auto，这样内部的100%才能伸展

**Comment by sumy7** [comment]
参考方案无法实现该效果，建议height增加auto选项。
