### ISSUE TITLE
template里如何获取对应的元素td

### ISSUE THREAD

**Issue by xuanyangdear** [baukh789/GridManager#153]
请问在template里如何获取对应的元素td,，想在td上的data-*存储对应的数据，像
`<td data-id="" data-type="input" data-text="111" data-name="orderNo"></td>`

thanks

**Comment by baukh789** [comment]
你可以像这样操作:
```
template: (action, row) => {
    return `<span class="plugin-action" data-id="${row.id}" onclick="demo1.editRowData(this)">修改</span>`;
}
```
当然data-*并不会放到td上，而是在td下的元素上。
至于获取dom元素，虽然我不是很确定你是期望达到什么效果，但你可以通过在模板上的事件来实现。

**Comment by xuanyangdear** [comment]
好的，谢谢，是想适应之前写的方法，在td上获取对应的属性来进行相关操作

**Comment by xuanyangdear** [comment]
真的没有对外的方法，直接获取单元格td对应的元素吗？（要改的代码太多）

**Comment by baukh789** [comment]
你可以在原来的获取函数中，获取你所标识的td下的元素，然后通过寻找父级来实现。
不过，我建议你可以把这块调整一下。
