### ISSUE TITLE
已开启用户记忆，但是点击浏览器的缩小或者最大化窗口按钮后，调整的列宽恢复初始宽

### ISSUE THREAD

**Issue by xuanyangdear** [baukh789/GridManager#154]
浏览器窗口在最大化的情况下，调整列宽后，再点击浏览器的缩小按钮，之前调整后的列宽变为初始的宽度，请问怎么在点击浏览器的缩小或者最大化窗口按钮后，前面调整的列宽不变？（因为会存储表格的相关状态到数据库）

蟹蟹

**Comment by baukh789** [comment]
因为这种操作触发了resize事件，而表格的存储策略是在resize事件中对宽度进行重新计算。
这个逻辑暂时不会改变，因为重新计算的存在是有必要的。
