### ISSUE TITLE
是否支持单行双击事件

### ISSUE THREAD

**Issue by janice-jia** [baukh789/GridManager#155]
嗨，大神，请问下是否考虑支持行双击事件呢？目前使用过程中需要用到行双击事件~
thanks.

**Comment by baukh789** [comment]
现在没有提供的双击事件，只有`rowClick`单击事件。
不过你可以通过该事件进行双击事件模拟，在一定时间内触发两次单击事件，则执行双击事件的脚本。

**Comment by janice-jia** [comment]
好的，那我尝试处理下~
thanks

**Comment by janice-jia** [comment]
嗨，，另外还有疑问，，对于这种多行表头是否支持呢？
![image](https://user-images.githubusercontent.com/15044639/77054057-36cf6480-6a0a-11ea-9fe1-f43bd5994656.png)

**Comment by janice-jia** [comment]
嗨，，另外我想问下，，对于这种多行的表头是否支持呢？
![111](https://user-images.githubusercontent.com/15044639/77054807-1b188e00-6a0b-11ea-822d-69b7f96f4e19.png)

**Comment by janice-jia** [comment]
另外还有一个疑问：
Angular框架内使用GridManager，可以通过封装一个指令方便使用，那么如果是“编辑”表格，即：表格内某字段是可以编辑的，那么通过指令调用后就不能触发ng-model，ng-change了，这种怎么解决呢？

**Comment by baukh789** [comment]
你如果使用的是angular1.x，那么可以直接使用已经封装好的框架版[gridmanager-angular-1.x](https://github.com/baukh789/GridManager-Angular-1.x)。

**Comment by janice-jia** [comment]
目前已经使用的是gridmanager-angular-1.x，如下图，如果在columnData中定义template为input，并绑定ng-model,,更改字段后，那么传入的list并不会被刷新~，所以只能支持静态表格吗？对于这种编辑表格怎么处理呢？
![image](https://user-images.githubusercontent.com/15044639/77292443-41943d00-6d1b-11ea-8ca0-b718d6ba0857.png)

![image](https://user-images.githubusercontent.com/15044639/77292646-a9e31e80-6d1b-11ea-9967-4ebd5cebe907.png)

**Comment by baukh789** [comment]
是的，由于是基于原生代码，所以这里需要特殊处理一下。
首先，你可以在input上绑定ng-blur事件, 如下所示
```
template: function(lastDate, rowObject){
    return '<input ng-model="row.lastDate" ng-blur="testBlur(row)">';
}
```
此时传入testBlur的将是更新后的数据，在testBlur内将是需要进行特殊处理的地方
```
testBlur(row){
// test是当前表格的gridManagerName
// id 是当前行数据的唯一值，可以为其它字符串
GridManager.updateRowData('test', 'id', row);
}
```

[关于updateRowData的API在这里](http://gridmanager.lovejavascript.com/api/index.html#updateRowData)

希望可以帮助到你，也希望GridManager可以让你的表格开发变的更轻松。

**Comment by janice-jia** [comment]
好的，了解了，感谢
