### ISSUE TITLE
firefox 下固定列错位

### ISSUE THREAD

**Issue by opxdo** [baukh789/GridManager#158]
firefox下 官网demo中的固定列表头错位

**Comment by baukh789** [comment]
@opxdo 已确认，会尽快修复，感谢你的反馈。

**Comment by baukh789** [comment]
火狐问题已修复，请下载最新版本

**Comment by opxdo** [comment]
已下载最新版，还是有点问题
![1](https://user-images.githubusercontent.com/19682814/81464782-362ba100-91f7-11ea-92b8-ec7e0e5682dc.png)
![2](https://user-images.githubusercontent.com/19682814/81464783-37f56480-91f7-11ea-8c0c-78b34c8540cb.png)

**Comment by baukh789** [comment]
develop. lovejavascript. com 试一下，如果还有问题请提供下火狐的版本号

**Comment by opxdo** [comment]
之前是 75(64位)，刚才升级到76.0.1(64位),
develop. lovejavascript. com 上的demo同样是这个问题

**Comment by baukh789** [comment]
已经确认，windows环境右侧固定列存在该问题。
待下一个版本修复。

**Comment by baukh789** [comment]
左侧问题上一版本已经修复

**Comment by baukh789** [comment]
@opxdo 你好，最新的版本针对火狐下的一些问题进行了修复，希望对你有帮助。

**Comment by opxdo** [comment]
OK了
