### ISSUE TITLE
树型表格如何实现上下拖拽效果

### ISSUE THREAD

**Issue by tangchenwxx** [baukh789/GridManager#159]

**Comment by tangchenwxx** [comment]
基于jquery开发出树型表格可以实现上下拖动效果

**Comment by baukh789** [comment]
你指的是行移动功能吗？
树形结构与行移动功能互斥，非树形结构上才可以使用行移动。

**Comment by tangchenwxx** [comment]
是的，是行移动，可以实现吗

**Comment by baukh789** [comment]
@tangchenwxx 树形结构在当前的版本中不可以使用行移动功能

**Comment by tangchenwxx** [comment]
好的，以后会更新吗

**Comment by baukh789** [comment]
@tangchenwxx 近期不会，已知树形结构的表格在处理行移动时会有一些异常情况。

**Comment by tangchenwxx** [comment]
好的，谢谢，我看有网站可以实现树型表格行拖动的效果
