### ISSUE TITLE
在固定列的情况下，使用复杂表头会导致排版错误。

### ISSUE THREAD

**Issue by the8th** [baukh789/GridManager#160]
表头高度被写死为了39px

用例：
https://codepen.io/the8th-the-looper/pen/YzydepN

**Comment by baukh789** [comment]
@the8th 该问题已修复，请更新至最新版本。

**Comment by the8th** [comment]
表头高度正常了，第一条数据被多出的表头遮盖的问题还存在。

**Comment by baukh789** [comment]
> 表头高度正常了，第一条数据被多出的表头遮盖的问题还存在。

已修正，同时也建议你直接使用与当前框架对应的版本。

**Comment by the8th** [comment]
你好。搞了个完整的复杂表头例子。参考下列连接
https://codepen.io/the8th-the-looper/pen/XWmOddQ
目前按你提供的方法注入二级表头，虽然有点怪，但是大致还是可以用的。

supportCheckbox打开时，表头横向就错乱了，少了一个checkbox的空间。我目前没有这个需求，只是在调试时发现了该问题

**Comment by baukh789** [comment]
你如果用到fixed: 'left', 又开启了supportCheckbox, 是需要配置checkbox的fixed。参考下API http://gridmanager.lovejavascript.com/api/index.html#checkboxConfig

**Comment by baukh789** [comment]
2.13.0版本中新增了配置项columnData[children]，可以很好的解决嵌套表头的需求。
