### ISSUE TITLE
能提供旧版本下载么

### ISSUE THREAD

**Issue by houdianjie** [baukh789/GridManager#161]
我现在用的是2.9.4，但是找不到旧版本的开源代码，想基于这个版本加上固定列

**Comment by baukh789** [comment]
每个版本发布后都有tag，可以在项目的Tag列表中找到。
另外固定列的功能在最新的版本上已经存在了，只需增加columnData[fixed]参数即可。

**Comment by houdianjie** [comment]
找到了，谢谢。我知道新版本有，但是我们这边页面比较多，改起来有点麻烦。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"写个程序换个饼"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月25日(星期一) 中午1:30
收件人:&nbsp;"baukh789/GridManager"<GridManager@noreply.github.com&gt;;
抄送:&nbsp;"竹杖芒鞋轻胜马"<352026213@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [baukh789/GridManager] 能提供旧版本下载么 (#161)





 
每个版本发布后都有tag，可以在项目的Tag列表中找到。
 另外固定列的功能在最新的版本上已经存在了，只需增加columnData[fixed]参数即可。

**Comment by baukh789** [comment]
[版本更新记录](http://gridmanager.lovejavascript.com/version/index.html)
