### ISSUE TITLE
初始化的时候能否跳到特定页？

### ISSUE THREAD

**Issue by xuanyangdear** [baukh789/GridManager#162]
GridManager.setQuery(table,{}, gotoPage, callback); 这个函数可以跳到特定页码，请问有没有初始化的时候就可以跳到特定页码的？
谢谢

**Comment by baukh789** [comment]
## 方法一(建议使用)
- 增加配置项`firstLoading`指定初始进入时不加载数据
- 通过GridManager.setQuery(table,{}, gotoPage, callback);进行加载数据

## 方法二
- 通过执行函数`responseHandler`修改传递参数

## 方法三(不建议使用)
- 通过参数`query`指定跳转页，但当前不允许直接使用分页参数，需要接口方特殊处理指定页参数

**Comment by xuanyangdear** [comment]
猴的，谢谢
