### ISSUE TITLE
columnData的template返回值为dom节点时，无法触发绑定的事件

### ISSUE THREAD

**Issue by the8th** [baukh789/GridManager#163]
请看以下例子：
https://codepen.io/the8th-the-looper/pen/RwWOdop

为删除按钮绑定了事件，但无法触发

**Comment by baukh789** [comment]
deleteBtn.addEventListener 不要写在模板内部，你可以通过给删除按纽一个className或者attr。然后在外部统一进行事件绑定。
还有，建议你直接使用与你项目对应框架版本进行开发。
比如说用的vue，可以使用gridmanager-vue。
这样你就可以直接使用@click进行事件绑定了。

**Comment by the8th** [comment]
通过钩子在外部绑定无法直接获取闭包内的数据，而且既然支持返回dom节点，就应该可以绑定事件。这样比较符合直觉。你文档的template部分也显式的声明了支持通过element.addEventListener方法绑定。所以我觉得支持一下比较好

不使用vue版本的原因是我这边想仅让它负责一个表格的view层渲染，不参与数据流同步，降低组件副作用。
