### ISSUE TITLE
复杂列出现错位

### ISSUE THREAD

**Issue by yinxinzhanchi** [baukh789/GridManager#164]
您好，这个复杂列的错位有没有什么好的办法解决呢
这个是复杂列的运用：
https://codepen.io/yinxinzhanchi/pen/eYpaGVM?editors=0010

**Comment by baukh789** [comment]
现有的支持方式是通过在`columnData.text`中配置来实现的，暂时没有针对于复杂列的单独配置项。

**Comment by baukh789** [comment]
2.13.0版本中新增了配置项columnData[children]，可以很好的解决该需求。
