### ISSUE TITLE
vue使用keepalive缓存，切换页面表格内容和下滚动条都复位，表头不会复位，导致错位

### ISSUE THREAD

**Issue by Zhansensei** [baukh789/GridManager#167]

**Comment by baukh789** [comment]
我在本地模拟了一下，并未出现这种情况。
你可以把详细的情况提供一下

**Comment by Zhansensei** [comment]
> 我在本地模拟了一下，并未出现这种情况。
> 你可以把详细的情况提供一下，包括出错时的截图。

我这边截图传不上来，首先第一个页面先把表格下边的滚动条往右划，然后切换页面，再切换回来，然后数据和滚动条都会出现复位的情况，表头不会复位，导致错位

**Comment by baukh789** [comment]
@Zhansensei 已复现

**Comment by baukh789** [comment]
V1.5.1版本已修复
