### ISSUE TITLE
多行表头处理

### ISSUE THREAD

**Issue by BBniubility** [baukh789/GridManager#168]
我在大佬的demo上看到的多行表是通过<p>标签加<sqan>标签组合出来的，组合之后样式不好辨认，而且大表头下的各个列，只有带key值的列可以排序。如果是需要行数较多的多复杂的多行表头能通过插件实现嘛。
图一是现在我能通过插件做到的效果。图二是我想达到的效果。
![Image_20200629103807](https://user-images.githubusercontent.com/33337177/85967493-2a897900-b9f5-11ea-8333-0206377de3d1.png)
![1593398352](https://user-images.githubusercontent.com/33337177/85967502-2eb59680-b9f5-11ea-9417-be87f382dc4d.png)

**Comment by baukh789** [comment]
这个表格有点复杂呃。
现有版本的gridmanager(v2.12.0)对于复杂表格是需要通过template配置的，并没有直接的配置项可以实现。
如果通过template实现需要调整样式，排序如需在最小的列使用需要在模板中调用setQuery或setSort方法。

虽然可以实现，但实现的代码会比较复杂。

后续会考虑将这种表格通过配置项进行支持，感谢你的支持。

**Comment by baukh789** [comment]
最新版的2.13.0中已经实现了多表头嵌套的功能，像你所提的需求可通过参数columnData.children进行实现。
详情请查看[API](https://gridmanager.lovejavascript.com/api/index.html#columnData), 感谢你对开源项目的支持。

**Comment by BBniubility** [comment]
非常感谢大佬，喝杯咖啡
