### ISSUE TITLE
数据比较多时纵向滚动条太短，就像一个点一样，不好操作，建议限制最小滚动条长度

### ISSUE THREAD

**Issue by EwingTsai** [baukh789/GridManager#173]

**Comment by baukh789** [comment]
@EwingTsai 感谢提醒，下个版本调整

**Comment by baukh789** [comment]
@EwingTsai V2.13.1版本已优化了该功能，详细请查看[更新记录](https://gridmanager.lovejavascript.com/version/index.html)。
