### ISSUE TITLE
大部分情况下，我们希望看到cell的所有内容，希望改进一下td样式

### ISSUE THREAD

**Issue by EwingTsai** [baukh789/GridManager#175]
我使用了以下样式来覆盖默认的样式，以便于显示完整的cell内容，希望提供一个可选配置项

    .table-wrap td {
        white-space: normal;
        word-break: break-all;
    }

**Comment by baukh789** [comment]
@EwingTsai 这个提议很不错，下个版本见。

**Comment by baukh789** [comment]
@EwingTsai 最新版已经加入该功能，详情请参与[useWordBreak](https://gridmanager.lovejavascript.com/api/index.html#useWordBreak)
