### ISSUE TITLE
嵌套表头，部分数据左浮动情况下。表头一与表头二对齐错位

### ISSUE THREAD

**Issue by nn200433** [baukh789/GridManager#177]
![image](https://user-images.githubusercontent.com/15652213/90003635-ef05ee00-dcc6-11ea-973d-be6ea45ab85e.png)

![image](https://user-images.githubusercontent.com/15652213/90003861-4c01a400-dcc7-11ea-8d43-806d4c235f98.png)

---

怀疑少生成了一个th

![image](https://user-images.githubusercontent.com/15652213/90005072-43aa6880-dcc9-11ea-8095-f231fca0cedb.png)

**Comment by baukh789** [comment]
@nn200433 目前嵌套表头与固定列是两个相冲突的功能，暂时不可以一同使用
