### ISSUE TITLE
麻烦问下表格内的行高怎么调整？

### ISSUE THREAD

**Issue by luguoyinhexi** [baukh789/GridManager#178]
表格的行高有个height调整，但是表格内的每一行的高度怎么调整呢？我现在默认的行高度都是640左右，而且没办法调整？

**Comment by baukh789** [comment]
行内高与文本内容所占高度相关，默认高度是上下各padding11 + lineHeight。
如果需要更改，可以通过样式去控制。

**Comment by luguoyinhexi** [comment]
![image](https://user-images.githubusercontent.com/37978516/90221271-7f197400-de3c-11ea-8a22-f96e7eebc1da.png)
感谢解答，主要是我只是很简单几行文字，每一行却占据了600多像素，实在摸不着头脑，调整样式也减不下去

**Comment by luguoyinhexi** [comment]
```json
# 请求获取到的数据如下：
{"data":[
 {"host_ip":"192.168.1.12",
 "host_name":"it-26",
"status":"在线",
"project":" ",
"station":" ",
"group_name":"default",
"ID":1,
"is_update":false,
"is_use":true},
{"host_ip":"172.168.1.13",
"host_name":"mes",
"status":"在线",
"project":"test",
"station":"",
"group_name":"default",
"ID":2,
"is_update":false,
"is_use":true},
{
"host_ip":"172.168.1.13",
"host_name":"mes",
"status":"在线",
"project":"test",
"station":"",
"group_name":"default",
"ID":3,
"is_update":false,
"is_use":true}],
"totals":3}
```

GridManger的请求如下：

```json
 height:"80%",
    gridManagerName: 'demo-baseCode',
    ajaxData: 'http://127.0.0.1:8000/api/clientInfo/',
    ajaxType: 'GET',
    columnData: [
        {
            key: 'host_ip',
            text: '主机地址'
        },{
            key: 'host_name',
            text: '主机名称'
        },{
            key: 'status',
            text: '状态'
        }
```

**Comment by BoWang816** [comment]
> ![image](https://user-images.githubusercontent.com/37978516/90221271-7f197400-de3c-11ea-8a22-f96e7eebc1da.png)
> 感谢解答，主要是我只是很简单几行文字，每一行却占据了600多像素，实在摸不着头脑，调整样式也减不下去

分析你的dom，从最里面的文字是否有被dom包裹 开始，逐层向上查看样式。这个高度应该就是你自己写的样式影响的，和返回的数据没有关系

**Comment by luguoyinhexi** [comment]
> > ![image](https://user-images.githubusercontent.com/37978516/90221271-7f197400-de3c-11ea-8a22-f96e7eebc1da.png)
> > 感谢解答，主要是我只是很简单几行文字，每一行却占据了600多像素，实在摸不着头脑，调整样式也减不下去
> 
> 分析你的dom，从最里面的文字是否有被dom包裹 开始，逐层向上查看样式。这个高度应该就是你自己写的样式影响的，和返回的数据没有关系
----

感谢解答
我检查后发现，即便是每一行文字的占据的宽度也有600px多，并且调整样式改变高度是无效的。麻烦帮忙看看，是什么地方我做错了，谢谢

![image](https://user-images.githubusercontent.com/37978516/90222357-7c1f8300-de3e-11ea-8994-675fc3f211bd.png)
![image](https://user-images.githubusercontent.com/37978516/90222376-85a8eb00-de3e-11ea-87fd-ea33ec1068fc.png)

**Comment by baukh789** [comment]
这个应该不是组件的问题，你可以看一下是哪块影响到了这个td的高度

**Comment by luguoyinhexi** [comment]
> 这个应该不是组件的问题，你可以看一下是哪块影响到了这个td的高度

刚测试了一下，确实是框架存在的问题

当请求的数据量过少的时候，他就会把每一行的高度扩大到600多，数据多的时候才会正常。
并且这个扩大的高度不受整个表格的高度影响，猜测是按照屏幕的高度来除以行数得到的表格高度，所以造成了我现在这样的错误。

**Comment by baukh789** [comment]
[demo](http://develop.lovejavascript.com/node_modules/gridmanager/demo/index.html)，可以在这个上面复现下。

**Comment by luguoyinhexi** [comment]
找到问题所在了，原来是在其他地方定义过表格的高度。。。。
谢谢帮忙解答




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "写个程序换个饼"<notifications@github.com&gt;; 
发送时间: 2020年8月14日(星期五) 下午3:43
收件人: "baukh789/GridManager"<GridManager@noreply.github.com&gt;; 
抄送: "龙龙"<504759770@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [baukh789/GridManager] 麻烦问下表格内的行高怎么调整？ (#178)





 
demo，可以在这个上面复现下。
