### ISSUE TITLE
表头和内容行宽度不一致，怎么解决

### ISSUE THREAD

**Issue by soylar** [baukh789/GridManager#179]
__
![image](https://user-images.githubusercontent.com/66368541/92835136-743b0a80-f40d-11ea-829f-8f25b0376919.png)

**Comment by baukh789** [comment]
是顶层的列(如图中的项目开发费用列)的宽度 / 子项数 的平均值需大于等于子项中最大宽的列。
你所示例中的项目开发费用列 /12的值小于了项目开发费用合计列，建议你用项目上开发费用合计的列宽*12做为项目上发开费用列的宽，或者宽度使用auto。

**Comment by soylar** [comment]
@baukh789 
![image](https://user-images.githubusercontent.com/66368541/92839173-3d1b2800-f412-11ea-8e9f-f62fb853877c.png)
这种错位现象怎么解决的

**Comment by baukh789** [comment]
@soylar 造成这种情况的原因是某一列的实际宽超出了所配置，或生成的宽。

**Comment by soylar** [comment]
![image](https://user-images.githubusercontent.com/66368541/92840054-3e008980-f413-11ea-83b1-90ff9f595642.png)
IE浏览器报错，谷歌正常，不适配IE吗？
@baukh789

**Comment by baukh789** [comment]
是的，不支持IE。所支持的浏览器readme.md中有介绍

**Comment by soylar** [comment]
@baukh789 
![image](https://user-images.githubusercontent.com/66368541/92840543-ce3ece80-f413-11ea-9b19-e26da8ce2717.png)
我将宽度设置很大了，但还是会出现错位
？？

**Comment by baukh789** [comment]
错位的并不一定是配置小的那一列，我后面的版本把这种情况兼容一下

**Comment by soylar** [comment]
最新的版本没有兼容吗？

**Comment by baukh789** [comment]
你可以试着调一下，配置正常的情况下是不会出这种问题的。
我本周会出一个兼容版本

**Comment by soylar** [comment]
![image](https://user-images.githubusercontent.com/66368541/92843169-0b589000-f417-11ea-92ab-9b2640708c6a.png)
这种表头配置有啥问题，不太清楚呀

**Comment by baukh789** [comment]
留一列的宽自适应

**Comment by soylar** [comment]
麻烦帮忙看一下，为啥显示的跟设置的不一样
![image](https://user-images.githubusercontent.com/66368541/92847752-14982b80-f41c-11ea-9c40-9f9554b0140c.png)

**Comment by baukh789** [comment]
子项的宽度配置是无效的，子项宽度由父项宽度进行平均分配。

**Comment by lishuaishuai123** [comment]
这个情况不要给配置width了，直接都删掉就ok了

**Comment by baukh789** [comment]
请更新至v2.14.6，该版本内对嵌套表头的宽度算法进行了优化。

**Comment by soylar** [comment]
![image](https://user-images.githubusercontent.com/66368541/93033308-4b628180-f668-11ea-9f3a-0e70ed722e1e.png)
更新之后还是有错位的，最后一列没有设置宽度
@baukh789

**Comment by baukh789** [comment]
请把你的columnData发一下

**Comment by soylar** [comment]
![image](https://user-images.githubusercontent.com/66368541/93035281-27566e80-f66f-11ea-897f-b666d8b688fc.png)
![image](https://user-images.githubusercontent.com/66368541/93035304-3806e480-f66f-11ea-891b-3acd0c18abc6.png)

**Comment by baukh789** [comment]
麻烦以code的形式发送下

**Comment by soylar** [comment]
![image](https://user-images.githubusercontent.com/66368541/93037280-a306ea00-f674-11ea-8000-db5f7f4d1824.png)
这种？？

**Comment by baukh789** [comment]
我这没有复现，建议你确认下在渲染完成前后，表格所在的容器宽度是否发生了变化。
