### ISSUE TITLE
IE下remove()不支持希望修改下

### ISSUE THREAD

**Issue by polofish** [baukh789/GridManager#18]
判断是否在IE下如果在那么将  remove()  改成 removeNode(true)   就能完美支持IE10以上了

**Comment by baukh789** [comment]
使用表格插件的大都是管理平台或系统,通常都是会进行浏览器指定,所以设计之初就没有考虑这个方面.

**Comment by BlueDemonChicken** [comment]
体制内的，希望可以兼容ie，这个插件很好。但是我们没办法要用ie的
