### ISSUE TITLE
列宽的拖动要是没忍住拉的具体太大了，在往回拖的时候已经拉开的总长度不变了，这个体验感觉很差，得把后面的好多列都往回拉一次，来均摊拉开的长度问题

### ISSUE THREAD

**Issue by lishuaishuai123** [baukh789/GridManager#180]
留一列的宽自适应

_Originally posted by @baukh789 in https://github.com/baukh789/GridManager/issues/179#issuecomment-690831056_

**Comment by baukh789** [comment]
你在控制台输入GM.version，发一下版本号

**Comment by lishuaishuai123** [comment]
感觉应该是考虑性能了，但是体验感觉很难受呢

**Comment by lishuaishuai123** [comment]
版本号2.10.5，还有就是这个版本的列宽，width这个属性不配置完全没有问题，但是想要给定一个宽度，就会存在表头和表格列出现错位，应该是计算的问题，感觉因该是没有计算正确累计偏差

**Comment by baukh789** [comment]
你更新下版本，这个拖动的交互在后面的版本已经优化过了。
width是有用的，你可以详细的看一下API。嵌套表头的宽度问题在下一个版本修复

**Comment by lishuaishuai123** [comment]
嗯嗯，好的，感谢站长们

**Comment by lishuaishuai123** [comment]
现在用的是最新的版本了2.14.5，表头进行拖拽移动整列的时候，被拖动的列下面超出“滚动条”的地方没隐藏掉

**Comment by baukh789** [comment]
@lishuaishuai123 这个列位置更换交互是会站用分页区域，这个交互是正常的

**Comment by lishuaishuai123** [comment]
嗯嗯，好的，这样也好
