### ISSUE TITLE
树型表格是否支持部分行展开，部分行收缩，或者通过哪个参数可以控制行的收缩和展开

### ISSUE THREAD

**Issue by CherishDing** [baukh789/GridManager#181]
你好，

请问树型表格是否支持部分行展开，部分行收缩，或者通过哪个参数可以控制行的收缩和展开

谢谢

**Comment by CherishDing** [comment]
你好，

树型表格是否支持部分行展开，部分行收缩，或者通过哪个参数可以控制行的收缩和展开

谢谢

**Comment by baukh789** [comment]
参数与方法只支持统一修改:
初始折叠状态: [treeConfig](https://gridmanager.lovejavascript.com/api/index.html#treeConfig)
改变折叠状态: [updateTreeState](https://gridmanager.lovejavascript.com/api/index.html#updateTreeState)
