### ISSUE TITLE
表头和表列对不齐

### ISSUE THREAD

**Issue by EakerZT** [baukh789/GridManager#182]
![图片](https://user-images.githubusercontent.com/6635806/93098229-340fac80-f6d9-11ea-9529-561a6b12edfc.png)
打开还是正常的
![图片](https://user-images.githubusercontent.com/6635806/93098336-54d80200-f6d9-11ea-8e00-bf03462025c4.png)
但是只要一拉长列头
![图片](https://user-images.githubusercontent.com/6635806/93098390-61f4f100-f6d9-11ea-991a-1098a7230409.png)

**Comment by baukh789** [comment]
建议在console里输入GM.version查看下版本号，更新到最新版2.14.6试下

**Comment by EakerZT** [comment]
> 
> 
> 建议在console里输入GM.version查看下版本号，更新到最新版2.14.6试下

最新版

**Comment by baukh789** [comment]
你的标签用错了，应该是table标签。把<div id="table_test">替换为<table id="table_test">

**Comment by EakerZT** [comment]
> 
> 
> 你的标签用错了，应该是table标签。把`<div id="table_test">`替换为`<table id="table_test">`
改了 这下是可以了
![图片](https://user-images.githubusercontent.com/6635806/93104979-18100900-f6e1-11ea-8bd6-95be7320457d.png)
直接出现了滚动条
![图片](https://user-images.githubusercontent.com/6635806/93105174-53aad300-f6e1-11ea-9e87-bc4e6c7e3c8c.png)
和官网的效果不一样

**Comment by baukh789** [comment]
你用的高度是100%，这个100%取决于当前所在容器的高度。

**Comment by EakerZT** [comment]
问题解决 感谢耐心指导 还有一个问题 
能不能提供一个完全关闭ajax的方式 手动设置loading状态和设置数据(后者有api但是好像loading圈也会出来)

**Comment by baukh789** [comment]
没有相关的API，不过你可以通过修改loadingTemplate来更改loading样式
