### ISSUE TITLE
镶嵌表头后面内容被压缩掉了

### ISSUE THREAD

**Issue by BBniubility** [baukh789/GridManager#184]
![image](https://user-images.githubusercontent.com/33337177/93978374-7c505e00-fdae-11ea-94c7-4c7117231ece.png)
![image](https://user-images.githubusercontent.com/33337177/93978417-8ffbc480-fdae-11ea-80c9-5f92b04420ee.png)
后面的列全部都不展示了，是我编写的问题还是不支持这么多列？

**Comment by baukh789** [comment]
1、当前使用的是哪个框架版本，版本号是否为最新的。
2、如果当前列为较复杂的情况，建议不设置宽度由组件自行匹配。
