### ISSUE TITLE
template事件不起作用

### ISSUE THREAD

**Issue by wangfx** [baukh789/GridManager#185]
template: (cell, row, index, key) => {
          let dv = document.createElement('div');
          for (let i = 0; i < tmp.length; i++) {
            let anode = document.createElement('a');
            anode.setAttribute('nztype', 'link');
            anode.setAttribute('id', index + '-' + tmp[i]);
            // anode.setAttribute('row', row);
            anode.innerText = tmp[i];
            anode.onclick = function() {
              console.log('=============1');
              // this.rowActionCall.emit({ action: tmp[i], row: row });
            };
            dv.appendChild(anode);
            if (i < tmp.length - 1 ){
              let d = document.createElement('nz-divider');
              d.setAttribute('nztype', 'vertical');
              d.setAttribute('ng-reflect-nz-type', 'vertical');
              d.classList.add('ant-divider');
              d.classList.add('ant-divider-vertical');
              dv.appendChild(d);
            }
          };
          // dv.onclick = () => {
          //   console.log('=============1');
          //   this.rowActionCall.emit({ action: tmp[i], row: row });
          // };
          return dv;
        }

**Comment by baukh789** [comment]
这个dom在渲染中会被clone，事件会被抛弃。
建议你直接返回htmlString或使用addEventListener方式进行事件绑定。

如果使用的是框架版本可以直接返回框架模板
