### ISSUE TITLE
使用时发现的一些问题

### ISSUE THREAD

**Issue by jinhong-wu** [baukh789/GridManager#186]
1、下载表格数据csv排版不对
问题：如果table中内容包含逗号/换行时，下载csv打开后样式全部错乱。
解决：应该判断, \n情况下的转化

2、列数过多引发的宽度样式
问题：笔记本列数过多，导致表格头与内容宽度错位
解决：
最开始是we(e).width()，动态再去计算宽度。发现e中已有之前thead计算好的宽度，故直接取值。
出现滚动条时，e.offsetWidth才准确；
无滚动条时，we(e).width()才准确。

**Comment by baukh789** [comment]
关于导出的问题是存在的，可以在exportConfig.handler()执行器内进行处理。

关于错位问题中有几个事项需要确认下:
1、提到的we()具体代码的什么？
2、所使用的版本号是多少(通过在控制台输出GM.version获取)
3、所使用的浏览器信息
4、列的配置信息

**Comment by jinhong-wu** [comment]
哈哈不好意思，we()是我压缩过后的代码（用的时候还没来github取源码），这个我没找到如何传图片。
我写在我的博客里了：https://blog.csdn.net/W_jin/article/details/107402326
