### ISSUE TITLE
windows下高分辨率缩放不是100%时，gridmanager在chrome下出现线条对不齐

### ISSUE THREAD

**Issue by kavizzz** [baukh789/GridManager#187]
现在的windows电脑基本都是1920 x 1080分辨率起步了。 在设置面板中一般推荐缩放都是 125%， 有些高分辨率推荐缩放甚至达到了200%以上，这种情况下，gridmanager在chrome下会出现thead和tbody的线条对不齐的情况， mac下没有这种现象。 用firefox测试也正常。用了这个插件两年了，也给作者支持过，希望能早日解决此问题。

**Comment by baukh789** [comment]
收到，感谢反馈

**Comment by baukh789** [comment]
@kavizzz  该问题在v2.14.18已经修复，对应的框架版本为v1.7.18
