### ISSUE TITLE
scrollLeft性能问题，打开fixed为left时明显下降

### ISSUE THREAD

**Issue by Violam** [baukh789/GridManager#188]
最近用上了gridManager作为数据表格组件，版本：2.14.10
然后发现fixed设置为left时，会导致性能显著下降，等待时间明显升高。 
数据量为：十多二十列，行数不到100，跑了300多毫秒，打开fixed后延迟感觉明细，如果行数为400行，延迟难以忍受。但是，发现当fixed为none后则等待时间显著减少。

一开始以为是服务器查数据库很慢，后来api里面加上服务器消耗时间后，并且使用requestHandler和responseHandler计算网络时间差，发现服务器其实很快。主要耗时还是在GridManager。
从chrome的Performance调试来看，消耗时间在updateFakeThead中的scrollLeft函数，猜测是引起了布局调整之类的导致大量cpu消耗。根据这函数用途，于是关闭fixed特性后变得很快。

但是浮动功能效果挺好挺实用的，还是得请大佬再优化一下

**Comment by baukh789** [comment]
这个主要是为了兼容firefox,chrome,safari所采用的方式，具体表现为: 固定的列越多，性能问题会越明显。
中间调试过几次，但都不太理想，暂时还没有找到特别好的方式来解决。
容我再耗掉几根头发，兴许不久后就会有了解决方案。

**Comment by Violam** [comment]
大佬加油！我比较了好多个表格组件，除了某个vue表格，没有像你这个这么整齐完善的，饿了么，layui之类的也没这么好用。scrollLeft性能消耗太显著了

**Comment by baukh789** [comment]
做了一版优化，你可以试一下新版。
