### ISSUE TITLE
请问关于页面跳转该如何实现

### ISSUE THREAD

**Issue by wacily** [baukh789/GridManager#189]
具体来说：假设我现在在第3页，我全选中第3页的数据，然后删除，在数据删除成功以后，页面需要自动进入第2页。我该如何实现呢？求解！！！

**Comment by baukh789** [comment]
[setQuery](https://gridmanager.lovejavascript.com/api/index.html#setQuery)中的第三个参数可以指定页码，通过[get][setQuery](https://gridmanager.lovejavascript.com/api/index.html#get)中的`pageData`可以获取当前页码信息。
