### ISSUE TITLE
gridmanager固定列时，thead和tbody样式显示，firefox显示正常，chrome显示错位

### ISSUE THREAD

**Issue by yyj-are** [baukh789/GridManager#190]
gridmanager固定列时，thead和tbody样式显示，firefox显示正常，chrome显示错位（chrome版本86.0.4240.183）：
![image](https://user-images.githubusercontent.com/73978445/98196024-15ea5e00-1f5e-11eb-8385-007da79b1460.png)

gridmanager版本：2.13.7
![image](https://user-images.githubusercontent.com/73978445/98195738-68774a80-1f5d-11eb-8c09-078cebc6ad76.png)
![image](https://user-images.githubusercontent.com/73978445/98195794-8e045400-1f5d-11eb-829b-0096fdd047cb.png)
部分js代码：
```
for (let index in labelIndexListJSON) {
    if (labelIndexListJSON.hasOwnProperty(index)) {
        let data = {};
        data.key = labelIndexListJSON[index]['INDEX_FULLNAME'];
        data.text = labelIndexListJSON[index]['INDEX_NAME'];
        data.sorting='';
        if(fixed_columnArray.indexOf(data.key)>=0){
        	data.fixed="left";
        	data.width="150px";
        }else{
        	data.width="auto";
        }
        data.template = function (data) {
            return data || "";
        };
        columnList.push(data);
    }
}
```
```
        ,checkboxConfig: {
            fixed: 'left',
            width:'40px'
        }
        ,autoOrderConfig: {
            fixed: 'left',
            width:'50px'
        }      
```

**Comment by baukh789** [comment]
你可以更新下组件版本



---原始邮件---
发件人: "yyj-are"<notifications@github.com&gt;
发送时间: 2020年11月5日(周四) 中午11:58
收件人: "baukh789/GridManager"<GridManager@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [baukh789/GridManager] gridmanager固定列时，thead和tbody样式显示，firefox显示正常，chrome显示错位 (#190)




 
gridmanager固定列时，thead和tbody样式显示，firefox显示正常，chrome显示错位（chrome版本86.0.4240.183）：
 
 
gridmanager版本：2.13.7
 
 
 部分js代码：
 for (let index in labelIndexListJSON) {     if (labelIndexListJSON.hasOwnProperty(index)) {         let data = {};         data.key = labelIndexListJSON[index]['INDEX_FULLNAME'];         data.text = labelIndexListJSON[index]['INDEX_NAME'];         data.sorting='';         if(fixed_columnArray.indexOf(data.key)&gt;=0){         data.fixed="left";         data.width="150px";         }else{         data.width="auto";         }         data.template = function (data) {             return data || "";         };         columnList.push(data);     } }          ,checkboxConfig: {             fixed: 'left',             width:'40px'         }         ,autoOrderConfig: {             fixed: 'left',             width:'50px'         }

**Comment by yyj-are** [comment]
升级过了，升级到2.14.6这个问题依然在

**Comment by baukh789** [comment]
目最新版是2.14.14，你可以试一下。如果还有问题，使用[demo](http://develop.lovejavascript.com/node_modules/gridmanager/demo/index.html)看下是否也存在该问题。

**Comment by yyj-are** [comment]
2.14.14在firefox下依旧完美显示，但是在chrome上还是错位，不过比先前效果好多了
chrome:
![image](https://user-images.githubusercontent.com/73978445/98205336-e85bdf80-1f72-11eb-8f16-92a9b15c8d5a.png)
firefox:
![image](https://user-images.githubusercontent.com/73978445/98205360-f578ce80-1f72-11eb-9092-593402a19e19.png)

**Comment by yyj-are** [comment]
且底部分页区域又显示不正常：

![image](https://user-images.githubusercontent.com/73978445/98206457-e4c95800-1f74-11eb-8935-389694e043c5.png)
应该和分辨率有关系

**Comment by yyj-are** [comment]
2.14.14在chrome还是显示不齐，窗口缩小比率后才显示对齐，列数比较多
![image](https://user-images.githubusercontent.com/73978445/98207770-20652180-1f77-11eb-9c1b-e887ae2b64a1.png)

**Comment by BoWang816** [comment]
> 2.14.14在firefox下依旧完美显示，但是在chrome上还是错位，不过比先前效果好多了
> chrome:
> ![image](https://user-images.githubusercontent.com/73978445/98205336-e85bdf80-1f72-11eb-8f16-92a9b15c8d5a.png)
> firefox:
> ![image](https://user-images.githubusercontent.com/73978445/98205360-f578ce80-1f72-11eb-9092-593402a19e19.png)

看你图片中展示的是，你在chrome中使用了放大操作，因此出现稍微错乱的问题也是正常的

**Comment by yyj-are** [comment]
我是为了模拟有滚动条的情况，我实际情况是列比较多，正常情况下未放大或者缩小的时候，firefox是正常的，chrome显示不正常。但chrome缩小就显示正常。
![image](https://user-images.githubusercontent.com/73978445/98224253-3b8f5b80-1f8e-11eb-9322-82beb5a201cb.png)
缩小chrome:
![image](https://user-images.githubusercontent.com/73978445/98224322-4e099500-1f8e-11eb-9d97-79138e13d3ba.png)
未缩小和放大chrome:
![image](https://user-images.githubusercontent.com/73978445/98224489-7b564300-1f8e-11eb-86ea-09cea8503f28.png)

**Comment by baukh789** [comment]
缩放是会影响页面的布局，暂时不考虑对缩放的支持。

**Comment by yyj-are** [comment]
在chrome未缩放或者放大显示时（即100%），显示串列了，缩放（80%）才正常，不是要支持缩放，应该和分辨率有关系。我的屏幕分辨率是1920*1080，在firefox下都是正常显示的。

**Comment by baukh789** [comment]
![image](https://user-images.githubusercontent.com/11342827/98319932-cfa80400-201c-11eb-81bf-d953c7fda494.png)
你可以确认下是否存在该图标，我在相同分辨率的电脑上调试了，并没发复现该问题。

**Comment by yyj-are** [comment]
![image](https://user-images.githubusercontent.com/73978445/98320137-40e7b700-201d-11eb-9382-806f50e65228.png)
没有

**Comment by baukh789** [comment]
 上面发的那个demo链接你在本地会不会存在这个问题

**Comment by yyj-are** [comment]
会

**Comment by yyj-are** [comment]
![image](https://user-images.githubusercontent.com/73978445/98321503-37ac1980-2020-11eb-9c90-838281a5dac9.png)
我的屏幕分辩调整成1280x960  在chrome下就是正常的

**Comment by kavizzz** [comment]
这个问题应该和我之前提的问题是同一个
windows下，当桌面分辨率缩放非100%的时候，(现在的windows笔记本，基本推荐缩放都是125%，如果分辨率高的话2k 3k
等，那缩放比例会更大)，这种情况下，gm在chrome下显示就会错位， 即使是官方demo也会错位出现线条对不齐的问题。我记得我是在2个月前提过，然而这个问题还是open状态。

**Comment by baukh789** [comment]
@kavizzz 这个问题还在调研，尝试了几种修复方案，还在调试中。

**Comment by baukh789** [comment]
@yyj-are 该问题在v2.14.18已经修复，对应的框架版本为v1.7.18

**Comment by yyj-are** [comment]
好的，谢谢，我到时候看看
