### ISSUE TITLE
这个框架如何开启编辑功能？

### ISSUE THREAD

**Issue by chenzijicc** [baukh789/GridManager#193]
我想用这个表格填单

**Comment by BoWang816** [comment]
> 我想用这个表格填单

可以说下你具体的业务场景，看是否可以满足你的业务需求

**Comment by chenzijicc** [comment]
编辑某个表格，保存数据

**Comment by BoWang816** [comment]
![image](https://user-images.githubusercontent.com/26587649/102444983-5eb92a80-4065-11eb-95ad-9c272dd10f24.png)
表格没有配置单独属性用于是否可以直接编辑某个单元格功能，但是可以在cloumnData属性配置中通过template字段，设置模版，实现你的业务逻辑。
比如：
![image](https://user-images.githubusercontent.com/26587649/102445231-f6b71400-4065-11eb-9c41-2bbf602b2c8f.png)

**Comment by chenzijicc** [comment]
谢谢老板
