### ISSUE TITLE
可否将右键菜单功能显式的表示呢？

### ISSUE THREAD

**Issue by SystemLight** [baukh789/GridManager#196]
1. 通常情况用户可能不会注意到右键功能
2. 是否可以将右键功能显示的面板与一个设置按钮进行关联，通过左键单击触发
3. 是否可以通过调用一个方法触发右键的面板，并且可以传递位置参数进行对应位置显示

**Comment by SystemLight** [comment]
顺便再问下 ，supportConfig这个配置选项具体是做什么用的，有没有具体示例呢？

**Comment by SystemLight** [comment]
对于排序功能是否可以增加一次还原的状态，目前触发排序是 升序-降序-升序 ， 是否可以指定变换状态为 升序-降序-还原-升序-降序-还原，目前的排序状态切换无法还原回原有排序状态进行查看

**Comment by baukh789** [comment]
**关于右键**
右键是一种快捷操作，但是右键中的功能都可以通过方法直接调用，如导现:`exportGrid`

**关于排序**
排序有两种模式, 你可以尝试使用`sortMode: single `，点击查看相关[API](https://gridmanager.lovejavascript.com/api/index.html#sortMode)
