### ISSUE TITLE
exportGrid()方法是否可以指定列导出？

### ISSUE THREAD

**Issue by SystemLight** [baukh789/GridManager#198]
1. 大多时候需要为表格增加操作列，但是exportGrid()会将所有列导出
2. GridManager似乎没有提供传入的完整数据获取接口，即使自定义做导出项也有困难

**Comment by baukh789** [comment]
你所提到的这种导出，有两种实现方式:
- 静态导出`static': 在`handler`修改参数`tableData`
- 动态导出`blob||url`: 在`handler`中向后端指定列
详情可以参考虑配置项: [exportConfig](https://gridmanager.lovejavascript.com/api/index.html#exportConfig)
