### ISSUE TITLE
有自带的搜索框的API函数吗？

### ISSUE THREAD

**Issue by harryGao65535** [baukh789/GridManager#2]
其他都很好，就是项目会用到搜索框，请问有这个API函数吗？

**Comment by baukh789** [comment]
搜索框考虑到样式及筛选条件差异，所以并未集成到组件内。
要实现搜索功能，只需在编码中调用以下方法即可。
1.调用: $('table').GM('setQuery',  {'name':'baukh'}),将搜索条件设置到GridManager实例内。
2.调用: $('table').GM('refreshGrid'),刷新列表数据。
当然你也可以使用链式操作: $('table').GM('setQuery', {'name':'baukh'}).GM('refreshGrid');
