### ISSUE TITLE
datakey 不能是一个对象么？

### ISSUE THREAD

**Issue by hufuxin011** [baukh789/GridManager#20]
现在的数据格式如下：
{
"status":"success",
"totals":68,
"data":[
    {"id":1,"name":"gridManager"},
    {"id":2,"name":"gridManager2"}
  ]
}
 ==>datakey:"data" 
而实际上可能如下：
 {
"status":"success",
"totals":68,
"data":[
      {
          pagesize:5,
          total:10,
          list:[
              {"id":1,"name":"gridManager"},
              {"id":2,"name":"gridManager2"}
          ]
      }
  ]
}
==>datakey:"data.list"

而datakey不支持对象？ 怎么解决？

**Comment by baukh789** [comment]
datakey的定义是:ajax请求返回的列表数据key键值,默认为data.
如你所示的这种数据类型是不可以的， 这需要你的接口提供人员提供格式匹配的的数据。

另付上datakey的用法
- datakey: 'list'
```
{
     "status":"success",
    "totals":68,
    "list":[
    {"id":1,"name":"gridManager"},
    {"id":2,"name":"gridManager2"}
    ]
}
```
- datakey: 'dataList'
```
{
     "status":"success",
    "totals":68,
    "dataList":[
    {"id":1,"name":"gridManager"},
    {"id":2,"name":"gridManager2"}
    ]
}
```
