### ISSUE TITLE
如何实现数据的增删改查，增行，删行等操作呢？

### ISSUE THREAD

**Issue by a-l-o-n-g** [baukh789/GridManager#200]
能否提供个思路，我发现这个插件对数据渲染很有友好，但如果编辑该如何处理呢？每次都刷新列表？

**Comment by baukh789** [comment]
可以参考下[API updateRowData](https://gridmanager.lovejavascript.com/api/index.html#updateRowData)

**Comment by a-l-o-n-g** [comment]
这是对单行数据进行操作，然后刷新数据是吧？增行呢？有方法不

**Comment by baukh789** [comment]
增加数据需要触发列表刷新，或者是自行维护数据，以静态数据形式使用。

**Comment by a-l-o-n-g** [comment]
刷新数据后能否定位到刚刚选中或者编辑过的那行数据呢?

**Comment by a-l-o-n-g** [comment]
你好，树型结构的时候能否设置某几行数据是展开，其他折叠，treeConfig中的openState设置的是整个列表的打开状态
