### ISSUE TITLE
ios上报错

### ISSUE THREAD

**Issue by nacxy** [baukh789/GridManager#202]
ios 上这段代码报错，
i.browser=navigator.userAgent.toLowerCase().match(/(msie|firefox|chrome|opera|version).*?([\d.]+)/)[1].replace(/version/,"safari")
navigator.userAgent.toLowerCase() 运行出的是appleWebkit
navigator.userAgent.toLowerCase().match(/(msie|firefox|chrome|opera|version).*?([\d.]+)/)[1] 运行为null
这种怎么解决，是否ios不能用这个框架？

**Comment by baukh789** [comment]
你指的是手机端的ios还是macos，这个组件是pc端使用的

**Comment by nacxy** [comment]
ipad，那这个...不会支持么？

**Comment by baukh789** [comment]
移动端的交互与PC不相同，这个组件是在PC端来使用的。不过你如果有兴趣，可以fork该项目进行改造。

**Comment by nacxy** [comment]
好的，谢谢
