### ISSUE TITLE
您好，请问当我在表格点开右键的下拉菜单，然后点击配置项选择自己需要的表头以后，怎么获取当前的表头数据

### ISSUE THREAD

**Issue by Willmind** [baukh789/GridManager#204]
当我使用GridManager.get(table).columnData获取的数据还是全部的表头数据，而不是自己所需要的表头数据

**Comment by Willmind** [comment]
然后我现在的做法是通过遍历GridManager.get(table).columnMap中的数据的isShow是否为true来完成的

**Comment by baukh789** [comment]
你所使用的columnMap方式是可以的
