### ISSUE TITLE
版本2.15.0多表头template第一次起作用，有缓存之后不起作用

### ISSUE THREAD

**Issue by luoshuangshenglgzk** [baukh789/GridManager#208]
版本2.15.0多表头template第一次起作用，有缓存之后不起作用

**Comment by baukh789** [comment]
@luoshuangshenglgzk 是否可以详细的描述一下，比如说你的配置项及错误的说明。

**Comment by luoshuangshenglgzk** [comment]
多表头的情况下，在columnData中的children中使用template,第一次起作用，有缓存之后不起作用。比如  我在children中的template函数中  把一列的值“1”转为“1-正常”，“0”转为“0-异常”，第一次加载会显示“1-正常”或“0-异常”，但是再刷新网页，就显示1或者0，清除gridmanager的缓存后再刷新网页会正常显示“1-正常”或“0-异常”，但是再刷新网页，就显示1或0。另：同一个表格的非children中使用template都正常

**Comment by baukh789** [comment]
已确认，下个版本将修复

**Comment by baukh789** [comment]
@luoshuangshenglgzk 已修复，请更新至@2.15.1
