### ISSUE TITLE
一个表格通过tab切换获得不同参数形成多个表格

### ISSUE THREAD

**Issue by deepthan** [baukh789/GridManager#21]
首先，非常感谢插件作者提供了一个这么好的插件，也非常感谢你的耐心解答，现在我遇到了一个问题，先描述下：
        我有三个表格需要做，也有三个tab键，点击每个tab可以切换到自己的表格。
        如果给每个表格都写上自己一套逻辑代码有点冗余，所以我想着能不能只用一个表格，通过每次传参不同使表格渲染出不同的数据形成三个不同的表格。
        暂时的思路：
               点击单个tab的时候往query里面传值（后端通过传入的customerStatus进行判断返回哪个类型的值，总共有三个类型：0,1，2），可以从后端请求到不同的值并重新加载页面，但是在这个之前得初始化表格，改写columnData里面的数据（即对应的键）。
代码如下：

html:
 `  <table id="allInfoTable" ></table>`

js:   
`table.GM({ 

        ....
        query: {customerStatus: 0},
        columnData: [{
		 		key: 'name',
				remind: 'the name',
				width: '10%',
				text: '姓名',
				sorting: ''
			},{
				key: 'organization',
				remind: 'the organization',
				text: '单位'
			},{
				key: 'position',
				remind: 'the position',
				width: '10%',
				text: '职位'
			}
         }]

})
`
以上是初始化表格渲染的第一个表格，那么我点击tab切换到第二个表格时：
方法是： 向后端传入参数customerStatus为1获得第二个表格的数据，然后初始化表格，在初始化表格的回调函数里执行函数，即往columnData里面传值把表格的字段改成只有一个名字的表。
js:
`	
$(".getType2").on("click",function(){

                document.querySelector('#allInfoTable').GM('setQuery',{
                   'customerStatus': '1'
                },function(){
                    document.querySelector('table').GM('init', {columnData:[{
                            key: 'name',
                            remind: 'the name',
                            width: '10%',
                            text: '姓名',
                            sorting: ''
                    }]}, function(callback){
                            console.log("callback",callback);
                    })
                });
})`
   
但是这样做（点击了tab切换想要切换成第二个表）表格没有任何变化，请问我这样做有什么问题导致失败呢？
谢谢！

**Comment by baukh789** [comment]
GridManager不支持重复渲染，所以不能通过一个表格实例化为三个表格。
我看了你所说的内容中有存在更改columnData的情况， 所以可以明确你所要的是三个不同的表格。
虽然GridManager不支持同一个table多次渲染，但是可以把公共的部分抽取出来。
如:
```
var tabel1 = document.querySelector('table1');
var tabel2 = document.querySelector('table2');
var tabel3 = document.querySelector('table3');
var commonSettings = {
     ....// 公共的配置
}
var table1Settings = {
    query: {customerStatus: 0},
    columnData:[]
}
var table2Settings = {
    query: {customerStatus: 2},
    columnData:[]
}
var table3Settings = {
    query: {customerStatus: 3},
    columnData:[]
}
table1.GM(Object.assign({}, tabl1Settings, commonSettings));
table2.GM(Object.assign({}, tabl2Settings, commonSettings));
table3.GM(Object.assign({}, tabl3Settings, commonSettings));
```
这种方式， 就会省去重复的代码。 
不可重复渲染问题，是在设计时就确定不使用的。

我看到你下午所用到了setQuery, 这个方法主要是用于搜索功能的。而你所需要的是三个不同的表格，所以建议你用上面的方式，将公共的抽取来解决。 

另外，谢谢你的支持，如果对GridManager感兴趣，可以star或fork之后来一同对该组件进行维护。

**Comment by deepthan** [comment]
谢谢你的方法，这样可以省去很多冗余代码。我又遇到一个问题请教一下啊？还是上面那个表格，当我切换到不同的表格调用document.querySelector('#allInfoTable').GM('refreshGrid',false,{});这个方法刷新表格，当然每个表格的取不同的id吗，这时候就会出现传过去的cpage=0的情况，麻烦帮忙看一下 ，谢谢。

**Comment by deepthan** [comment]
补充： 当两个表格互相切换的时候，若从有数据的表格切换到无数据的表格时候，无数据表格传递的参数是cpage=0，如果两个表格都有数据则正常。

**Comment by baukh789** [comment]
refreshGrid 方法存在的BUG已经修复，请重新下载新版本。
十分感谢你所提供的BUG信息。

**Comment by deepthan** [comment]
谢谢 神速啊 超赞 我马上下载试试

**Comment by deepthan** [comment]
你好，我下载了2.3.11版本并替换了，但是还是不起作用，切换到其他表格的时候还是传递的

`{

pSize:10
cPage:0
tPage:0
tSize:0
}`，我试了setquery方法触发刷新还是一样。是不是我版本没下正确？

**Comment by baukh789** [comment]
检查你的数据格式是否与Demo格式相同
检查是否返回了totals或者指定的匹配字段，
另建议你在切换tab所执行的refreshGrid方法中， gotoFristPage设置为true

**Comment by deepthan** [comment]
数据格式是相同的。
返回了totals和指定的匹配字段，因为我让后端做了处理，我传cpage=0和传cpage=1效果一样。
gotoFristPage设置为true了。
但是还是有这个问题：
三个表格，切换到另外一个表格的时候触发refreshGrid方法，传递过去的参数是{pSize:10,
cPage:0,
tPage:0,
tSize:0
}，
理应是{cpage=1,pSize:10}。我来拜读一下源码~

**Comment by baukh789** [comment]
你先自已看下，实在解决不了，可以把完整的代码块粘在这里。
