### ISSUE TITLE
表格分页样式与bootstrap冲突如何解决？

### ISSUE THREAD

**Issue by chenzijicc** [baukh789/GridManager#211]
在使用这个表格的时候，发现同时与bootstrap一起写页面的时候，分页栏样式会出现问题，请问怎么解决？
![屏幕截图 2021-05-20 100533](https://user-images.githubusercontent.com/52203093/118907922-fd1e2480-b952-11eb-999f-fd508d5bbc96.jpg)

**Comment by baukh789** [comment]
- 方法一：通过定制化的分页模板进行处理，[示例](https://github.com/xtfan21/GridManager-element-skin/blob/master/src/js/ajaxPage.tpl.html)
- 方法二：自行处理冲突样式。
