### ISSUE TITLE
模糊搜索

### ISSUE THREAD

**Issue by huanruiz** [baukh789/GridManager#213]
请问query中支持模糊搜索吗, 比如一列中包含["苹果", "西瓜","香蕉"]三个元素, 在setQuery的query中放"果", 就能搜索出"苹果". 多谢大佬~

**Comment by baukh789** [comment]
表格组件的搜索是将查询参数传递至ajaxData中所配置的接口，只要接口支持即可。

**Comment by huanruiz** [comment]
搞定了, 谢谢~

**Comment by huanruiz** [comment]
搞定了, 谢谢~
