### ISSUE TITLE
支持客户端分页吗

### ISSUE THREAD

**Issue by Rexes** [baukh789/GridManager#214]
有些数据数据量不是特别大但又需要分页、排序功能，  不想让后端去分页，怎么设置搞成前端分页？

**Comment by baukh789** [comment]
组件并没有提供配置项可以对静态数据分页，如果需要这个功能可以在ajaxData函数中进行模拟(其实做的就是后端需要的工作量)

**Comment by Rexes** [comment]
主要又要做排序和分页 ，排序希望是全局排序， 前端性能就没那么好了。前端小白，希望大神多多指教

https://github.com/TheoXiong/vue-table-dynamic  这个可以做前端排序 性能也不错 ，但是没有你的gridmanager好用。

**Comment by Rexes** [comment]
大神可不可搞个前端排序    网上搜索了太多组件， 好不容易看到你的很漂亮。

**Comment by baukh789** [comment]
@Rexes 目前是需要自已在ajaxData中进行处理的，你可以尝试处理一下。
