### ISSUE TITLE
开启了首列checkbox，并且固定在左侧，如何设置宽度

### ISSUE THREAD

**Issue by kavizzz** [baukh789/GridManager#215]
![image](https://user-images.githubusercontent.com/23111013/121979471-d7066b80-cdbc-11eb-9b46-19c3b3d930ef.png)
此时， 我如何给checkbox列设置宽度呢？ 我想让合计行的文本显示完整

**Comment by kavizzz** [comment]
此外，还想咨询一下， 如何增加两个合计行？ 一行显示本页的合计值， 一行显示总的合计值。 目前我是通过在一行中换行展示，效果肯定没两行展示好。

**Comment by baukh789** [comment]
感谢你提的问题，只是很抱歉在目前的版本中并不支持以下功能:
- checkbox列配置宽度
- 汇总行以两行模式展示

这两个功能目前正在调研中，也许会在之后的版本出现。
