### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by leonyyang** [baukh789/GridManager#216]
感谢作者奉献了这么好的组件。
以下能否改进：

1. 页数的下拉框，如果上面有固定列，分页会显示会被遮挡
src\module\dropdown\style.less
 .gm-dropdown-list 添加: z-index: 5;

2. 缩短左下角刷新图标的时长，能否可定义。现在写死了3000毫秒。
我们页面刷新很快，但是图标还是在旋转，客户觉得我们加载慢
src\module\ajaxPage\index.js

```
       // 停止刷新
        setTimeout(() => {
            refreshAction.removeClass(refreshClass);
        }, 3000);
```

3. 固定列，能否添加拖拉调整列宽功能

**Comment by baukh789** [comment]
感谢你的建议，针对于你所提的问题
- 下拉框问题属于BUG，我会在近期修复
- 刷新图标的3000秒设置，是在停止刷新时用于保证刷新动画正常显示的数值，触发时机为数据加载完成后，并不把加载时长写死了。
- 固定列有特殊性，需要一个固定的宽和位置。目前不能支持固定列调整宽及位置。

**Comment by leonyyang** [comment]
感谢！！
