### ISSUE TITLE
表格宽度较小的情况下,选择页面样式乱了，请问如何限制可以选择的页面数

### ISSUE THREAD

**Issue by woshixiguagua** [baukh789/GridManager#217]
![8D7WAWLXC_JJH7@U_E83%IV](https://user-images.githubusercontent.com/49368187/122351627-e46c5300-cf80-11eb-8f9a-c7cffb128173.png)

**Comment by woshixiguagua** [comment]
如图，如何限制可供选择的页面数量

**Comment by baukh789** [comment]
针对于表格所在容器特别小的情况，建议将页码区域进行隐藏，有两个解决方式:
- 使用样式隐藏 `ul[pagination-number]`
- 通过自定义分页参数[ajaxPageTemplate](https://gridmanager.lovejavascript.com/api/index.html#ajaxPageTemplate)进行布局重排

**Comment by baukh789** [comment]
如果想自定义分页，可以参考下[element-ui皮肤中关于分页的处理](https://github.com/xtfan21/GridManager-element-skin/blob/master/src/js/index.js)，ajaxPageTemplate参数接收一个字符串，并通过这个字符串进行分页解析。

**Comment by woshixiguagua** [comment]
@baukh789 问题已解决，感谢您所做的工作！
