### ISSUE TITLE
是否支持表格初始化后更新表头

### ISSUE THREAD

**Issue by wenguangji** [baukh789/GridManager#218]
你好，我想使用下这个表格，请问是否支持动态生成表头，而不是使用固定表头呢

**Comment by wenguangji** [comment]
> 你好，我想使用下这个表格，请问是否支持动态生成表头，而不是使用固定表头呢

我表格的请求头是从数据库获取的，每个界面不固定，无法在初始化时确定表头

**Comment by BoWang816** [comment]
可以通过接口获取表头配置数据，等配置数据接口成功返回数据，再进行初始化表格即可

**Comment by wenguangji** [comment]
> 可以通过接口获取表头配置数据，等配置数据接口成功返回数据，再进行初始化表格即可

![image](https://user-images.githubusercontent.com/48205856/123596477-d17d3c80-d824-11eb-9f9b-4ab0d4ba87c2.png)
问下我看样例中angularjs的html标签使用的是<grid-manager></grid-manager>，这个是如何进行初始化呢

**Comment by baukh789** [comment]
angular的使用gridmanager-angular-1.x，并不是直接使用gridmanager。
需要注意的是angular只支持1.x版本，并不支持2及以上版本

**Comment by wenguangji** [comment]
> angular的使用gridmanager-angular-1.x，并不是直接使用gridmanager。
> 需要注意的是angular只支持1.x版本，并不支持2及以上版本

当前使用版本为1.5版本，在获取到表头数据后进行表格的初始化报错

**Comment by wenguangji** [comment]
> > angular的使用gridmanager-angular-1.x，并不是直接使用gridmanager。
> > 需要注意的是angular只支持1.x版本，并不支持2及以上版本
> 
> 当前使用版本为1.5版本，在获取到表头数据后进行表格的初始化报错

可以加您微信聊下吗？微信号：J1094510360

**Comment by wenguangji** [comment]
![image](https://user-images.githubusercontent.com/48205856/123598856-8d3f6b80-d827-11eb-85bf-2448006f53d7.png)
这部分代码在请求表头数据返回后，但是表格初始化失败了，html标签是<grid-manager id="entry-grid" option="option"></grid-manager>

**Comment by BoWang816** [comment]
可以查看angularjs版本的使用方法：https://github.com/baukh789/GridManager-Angular-1.x

在数据返回之前使用ng-if先隐藏组件，数据返回后在显示组件

**Comment by baukh789** [comment]
刚在上面提到了，如果你要使用angular-1.x的版本，需要引入gridmanager-angular-1.x，而不是直接使用gridmanager。
还有，你看一下ajaxData的使用规范，这个需要返回一个promise。

**Comment by wenguangji** [comment]
> 可以查看angularjs版本的使用方法：https://github.com/baukh789/GridManager-Angular-1.x
> 
> 在数据返回之前使用ng-if先隐藏组件，数据返回后在显示组件



> 刚在上面提到了，如果你要使用angular-1.x的版本，需要引入gridmanager-angular-1.x，而不是直接使用gridmanager。
> 还有，你看一下ajaxData的使用规范，这个需要返回一个promise。

我这边引入的是gridmanager-angular-1.x，gridmanager是起的别名，ajax这边是我们封装过的，请求数据我试过是没问题的，我先试下ng-if的写法，谢谢！

**Comment by wenguangji** [comment]
大佬们，我这还是不可以，请问有angularJS1.x版本的动态表头示例吗？

**Comment by baukh789** [comment]
暂时没有这种示例，你可以参考以下的逻辑进行下修改。或者你从[gridmanager首页](https://gridmanager.lovejavascript.com/index.html)扫码加群看有没有其他人有相关的示例。
```html
<grid-manager option="$ctrl.gmOption" ng-if="$ctrl.gmOption"></grid-manager>
```

```javascript
// 1、获取表头信息，此时$ctrl.gmOption需为undefined
// 2、通过获取到的表头信息拼装columnData
// 3、将拼装后的配置信息赋值于$ctrl.gmOption，此时模板中的nf-if将会生效
```

**Comment by wenguangji** [comment]
好的，我先试试，在群里再问下

**Comment by wenguangji** [comment]
解决了，谢谢大家
