### ISSUE TITLE
GridManager嵌套表头的情况下,导出excel列错位了

### ISSUE THREAD

**Issue by liuzhengzhuo2020** [baukh789/GridManager#219]
GridManager嵌套表头的情况下,导出excel列错位了,有问题请帮修复一下,感谢

目前嵌套表头导出的情况是单表头的格式,如果可以导出按照嵌套表头的格式就更好了

**Comment by baukh789** [comment]
请查看 [exportConfig](https://gridmanager.lovejavascript.com/api/index.html#exportConfig)，静态导出的数据是可以自由操控的

**Comment by liuzhengzhuo2020** [comment]
好的谢谢了,我去试试
