### ISSUE TITLE
您好，可以实现一下单选配置吗？

### ISSUE THREAD

**Issue by MyWikey** [baukh789/GridManager#22]
我觉得是不是可以加有个配置项，实现单选配置啊？万分感谢

**Comment by baukh789** [comment]
是否可以带下示意图

**Comment by MyWikey** [comment]
就像图片上这个位置，只能保证选择一个而不是多个，可以实现吗？
![image](https://user-images.githubusercontent.com/19515245/28400619-eec6376c-6d46-11e7-9221-aa988dff1701.png)

**Comment by baukh789** [comment]
首先这个功能为全选，所以你提到的这个方式，是没有提供可配置参数的。
如果需要实现你所说的这种情况，可以按以下步骤实现:
- 配置参数[supportCheckbox=false] 禁用全选功能
- 配置参数columnData下指定项的template, 如
```
columnData:[{
				key: 'radio',
				remind: 'the radio',
				width: '10%',
				text: '操作',
				template: function(action, rowObject){
					return '<input type="radio" name="myRadio"/>';
				}
			}]
```
希望可以帮助到你

**Comment by baukh789** [comment]
关于template 使用方式，可参考demo- 自定义列模版

**Comment by MyWikey** [comment]
好的，哥，多谢啦，还有一个问题，我看了看API，貌似咱这个插件目前还没有绑定点击行的响应事件对吗？

**Comment by baukh789** [comment]
template可以实现各种自定义事件， 包括你说的点击行事件。这个是一个变通参数，你可以研究一下。

**Comment by MyWikey** [comment]
嗯，我研究研究，目前做一个项目在用，感觉你这个插件很棒

**Comment by baukh789** [comment]
如果有时间的话，可以试着提交一些commit。

**Comment by MyWikey** [comment]
嗯，好的

**Comment by MyWikey** [comment]
你好，为什么换了2.3.11版本的之后宽度就不能调整了呢，操作栏加了一个radio,然后每个item是一样宽的，设置width不管用，帮忙看下可以吗？
![qq 20170725160722](https://user-images.githubusercontent.com/19515245/28562057-6b2a99b4-7153-11e7-8401-7a5a76642c7f.png)

**Comment by baukh789** [comment]
从你描述的信息来看，像是css与js版本不同导致。
你需要替换掉所有的文件，而不仅仅是js。

**Comment by MyWikey** [comment]
还有一个问题是，为什么我自己写了后台方法，成功请求数据后，分页不管用了呢，pagesize设置的是10却显示了43个，都在一个页上，麻烦了

**Comment by MyWikey** [comment]
我替换掉的是整个文件夹，css和js在文件夹都没有动，所以应该不是css与js版本的事吧

**Comment by baukh789** [comment]
单选功能在后续的版本中已经通过配置项`checkboxConfig.useRadio`支持
