### ISSUE TITLE
用户如何增大最后一列的宽度

### ISSUE THREAD

**Issue by ZhaoZuohong** [baukh789/GridManager#221]
在Demo演示中，如果表格的列宽允许用户调整，如何增大最后一列的宽度？目前最后一列只有左侧可以调整，在右侧无法调整。

**Comment by BoWang816** [comment]
.....
右侧当然不能调整

**Comment by baukh789** [comment]
最后一例是不允许直接操作的，用户操作最后一列的宽度时需要先将最后一列移动到其他的列进行调整。
