### ISSUE TITLE
ios微信内置浏览器修改UA导致执行异常

### ISSUE THREAD

**Issue by pbl-pw** [baukh789/GridManager#222]
![1](https://user-images.githubusercontent.com/3636470/125766866-2bc2f81c-a99c-46bd-b222-28efb0589fa4.jpg)
![2](https://user-images.githubusercontent.com/3636470/125766891-cc046ae9-abe6-4f41-bb6c-72f3614fd918.jpg)
https://github.com/baukh789/GridManager/blob/29e09506d25410e4ff1070201b1a1921ad1b9605/src/jTool/utils.js#L292-L293
微信去掉了UA里面的Version导致上面这里正则匹配失败

**Comment by baukh789** [comment]
针对于移动端比较遗憾，这个组件是以PC端为主体的，移动端上并没有尝试过。

**Comment by pbl-pw** [comment]
虽然不声明支持移动端，可否匹配失败时返回一个默认值而避免异常
事实上我临时将其改为返回空的话，在微信上表现良好。
在android和ios默认浏览器上不必修改也表现良好

**Comment by baukh789** [comment]
好的，我尝试调整下

**Comment by baukh789** [comment]
V2.16.0已经将该异常处理，但还是需要注意：该组件的设计初衷并未包含移动端，请谨慎使用。
