### ISSUE TITLE
refreshGrid建议增加局部刷新的功能

### ISSUE THREAD

**Issue by ylforest** [baukh789/GridManager#223]
避免更新数据后，列表又跳回到第一行

**Comment by baukh789** [comment]
请参考[updateRowData](https://gridmanager.lovejavascript.com/api/index.html#updateRowData)

**Comment by ylforest** [comment]
非常感谢 已经通过这个方法完美解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baukh789/GridManager"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月16日(星期五) 下午5:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baukh789/GridManager] refreshGrid建议增加局部刷新的功能 (#223)





 
请参考updateRowData
