### ISSUE TITLE
veu2使用表格(小白入门)

### ISSUE THREAD

**Issue by qin9911** [baukh789/GridManager#224]
一；安装
`npm install gridmanager-vue --save`

二；配置（以element-ui为例)

     1、全局配置
          在main.js中引入并注册全局组件
          `import GridManager from 'gridmanager-vue';
           import 'gridmanager-vue/css/gm-vue.css';
           Vue.use(GridManager);`

      2、使用
            在所需页面html调用组件：
            `<grid-manager :option="gridOption" ref="grid"></grid-manager>`

            js添加data（组件的option值要与data时声明的变量名字要一样）：
            `gridOption: {
        height: '100VH', //表格高度
        gridManagerName: "gm",  // 表格唯一标识
        ajaxData:'', //表内容
       // ajaxType: "POST",  //此处我使用的是自己的请求方式；如使用官方请求方式可在ajaxData上写请求地址；ajaxType写请求方式
        columnData:'',  //表头内容
      },`
        请求表格内容可在页面的生命周期created方法中进行请求后端
        表头数据格式：[{key:'key1',text:'text'}，{key:'key2',text:'text'}]
        表内容数据格式：[{key1:'123',key2:'456}] //对象下标要和表头的key对应
       示例代码：
       `getTable().then(res=>{
        this.gridOption.columnData =res.tabHead;
        this.gridOption.ajaxData ={data:res.detailList,"totals": 8}
      })`
   **注意：**请求到数据后页面是无显示的；因为grid-manager组件在未请求到数据前已经渲染；所以要控制grid-manager组件的渲染时间；我使用的是v-if判断ajaxData 是否有内容；上第2 点里调用组件做了以下修改；
`<grid-manager v-if="gridOption.ajaxData" :option="gridOption"  ref="grid"></grid-manager>`
到此一个基本的表格已经展现在页面上了；其他参数可以参考[官方文档](https://gridmanager.lovejavascript.com/api/index.html)按需添加。

**Comment by baukh789** [comment]
可以考虑把这些文章发到类似于掘金的地方
