### ISSUE TITLE
某行某个td的模板根据当前行其他数据改变而改变

### ISSUE THREAD

**Issue by kavizzz** [baukh789/GridManager#226]
业务场景：
 
> 假设渲染的table一共2行。第一列渲染的模板是一个select下拉框（option为[1,2]），第二列的模板是一个input输入框（可写）。此时我将第一行的select选中值由1改为了2，我想实现让我的第二列input改变为禁填状态, 仅仅只是改变当前行的input而不是所有行。

> 目前我自己的解决方法很笨拙，就是监听select的change事件，从而update当前行的数据，再通过dom操作去改变对应的 input的 状态。想问问大佬有没有更好的解决方案。

> 当然，我这只是一个简单的例子，我们还有更为复杂的应用场景，基本难题都停滞在于改变了rowdata之后的一些改行某些 td中的模板更改操作

**Comment by kavizzz** [comment]
也就是说， 想实现 同一列的不同行有不同的渲染模板，目前只能在初始化的时候配置每列的模板。

**Comment by baukh789** [comment]
我大概理解了下你的意思，如果想通过一列的操作改变行的数据，可以看一下[updateRowData](https://gridmanager.lovejavascript.com/api/index.html#updateRowData)方法。

操作列的事件中调用该方法，将更新后的数据传入即可。

**Comment by kavizzz** [comment]
> 我大概理解了下你的意思，如果想通过一列的操作改变行的数据，可以看一下[updateRowData](https://gridmanager.lovejavascript.com/api/index.html#updateRowData)方法。
> 
> 操作列的事件中调用该方法，将更新后的数据传入即可。

不对， 我不只是要改变数据，我还需要改变模板。 
在GM初始化的时候，我们可以通过表头数据的template去给该列设置模板， 但是在数据渲染完毕之后， 我们是没法去动态修改某个td的template模板，例如我们改变了第一个td中的内容，从而自动去修改第二个td中的模板，这才是我们想要的

**Comment by kavizzz** [comment]
> 我大概理解了下你的意思，如果想通过一列的操作改变行的数据，可以看一下[updateRowData](https://gridmanager.lovejavascript.com/api/index.html#updateRowData)方法。
> 
> 操作列的事件中调用该方法，将更新后的数据传入即可。

![Uploading image.png…]()

**Comment by baukh789** [comment]
通过updateRowData方法更改数据后，相应的DOM也会更新。如果你在template中对可能存在的各种展现形式做已经做好了区分，在数据更新之后会通过template渲染出相应的DOM。

**Comment by kavizzz** [comment]
> 通过updateRowData方法更改数据后，相应的DOM也会更新。如果你在template中对可能存在的各种展现形式做已经做好了区分，在数据更新之后会通过template渲染出相应的DOM。

懂了，如果updateRowData能触发模板渲染的话就好办了。 谢谢啦~
