### ISSUE TITLE
数据显示形式问题

### ISSUE THREAD

**Issue by huangsjmh** [baukh789/GridManager#233]
当数据中包含html标签时会自动转换，能否给个选择，默认以文本text显示，或者自定义以html显示？

**Comment by BoWang816** [comment]
自己可以转义一下，自己写xaing相关的模板即可
![image](https://user-images.githubusercontent.com/26587649/140707771-19fa4cc3-2345-4c0f-b04e-161cb889f80a.png)

**Comment by huangsjmh** [comment]
可以在以后更新中加入这种选择嘛？这样添加的话每一个都需要添加模板自定义，而且不注意的话数据很容易被特殊字符给改变。

**Comment by huangsjmh** [comment]
maxHeight，最大高度需要先把默认高度300px给取消才能正常显示，否则最高不能超过300px，能设置成设了最大高度默认把默认高度取消嘛？没错，甲方就是我！
![image](https://user-images.githubusercontent.com/50041686/141044884-d6cb46be-3987-4cf5-84af-fdc31160d991.png)
![image](https://user-images.githubusercontent.com/50041686/141044960-06422fd2-1ab4-41d5-bc90-44d9c0dbf3f0.png)

**Comment by huangsjmh** [comment]
但是这样把高度设置成空后会导致下拉没了，所以这种方法也行不通。

**Comment by BoWang816** [comment]
高度的控制，可以在表格外层包一层，表格高度设置100%，控制外层元素的高度，表格会根据外层自适应的。

**Comment by huangsjmh** [comment]
那样子他会依据最外层的高度固定住，无论内容数据有多少，那样子maxHeight这个属性不是就没意义了嘛？
![image](https://user-images.githubusercontent.com/50041686/141063702-b7ec192f-c96d-42bb-9c22-50093dd3d084.png)
最大高度不应该是会依据内容的多少去改变高度嘛？
![image](https://user-images.githubusercontent.com/50041686/141063995-7582bf29-1c6d-4564-b51d-eeb51fcaef77.png)

**Comment by w19960528** [comment]
在没有做任何改动的情况下，数据数量变多右边固定列th样式right会增加10px
![uTools_1636702638618](https://user-images.githubusercontent.com/31678874/141429740-cecb37c7-4e7c-41b8-ba1f-15b46d12a12c.png)
![uTools_1636702806549](https://user-images.githubusercontent.com/31678874/141429749-7605e670-3c04-4b32-adda-c89e0c35f2a1.png)
![uTools_1636703113509](https://user-images.githubusercontent.com/31678874/141429782-4cc2b238-6309-49ab-8875-b5e4e3bfe293.png)
![uTools_1636703174975](https://user-images.githubusercontent.com/31678874/141429800-8289e21b-c98d-4f0f-9c25-97165e7f76ec.png)

**Comment by baukh789** [comment]
@w19960528 当出现Y轴滚动条时，会自动增加10px，这是个正常的现像。但你提供的示例中th区域样式却出现了问题，你可以提供下你当前所使用的版本`console.log(GM.version)`，或者在[demo](http://develop.lovejavascript.com/gridmanager/demo/index.html
)中复现。

**Comment by baukh789** [comment]
maxHeight和height是两个概念，maxHeight用于控制height为100% 且 外部容器高度过大时 对表格进行高度限制。
