### ISSUE TITLE
在没有做任何改动的情况下，数据数量变多右边固定列th样式right会增加10px

### ISSUE THREAD

**Issue by w19960528** [baukh789/GridManager#234]
在没有做任何改动的情况下，数据数量变多右边固定列th样式right会增加10px
![uTools_1636702638618](https://user-images.githubusercontent.com/31678874/141435575-cba3bb1f-4e44-4534-8ec8-80e4f1da71ea.png)
![uTools_1636702806549](https://user-images.githubusercontent.com/31678874/141435643-1452e438-94ab-4d75-8b70-846ad394ad5b.png)
![uTools_1636703113509](https://user-images.githubusercontent.com/31678874/141435674-c9eca37c-313a-4c39-bc52-97082ac0b5a8.png)
![uTools_1636703174975](https://user-images.githubusercontent.com/31678874/141435687-93f73730-e0da-43dc-8dd1-11e35710ec94.png)

**Comment by baukh789** [comment]
当出现Y轴滚动条时，会自动增加10px，这是个正常的现像。但你提供的示例中th区域样式却出现了问题，你可以提供下你当前所使用的版本console.log(GM.version)，或者在demo中复现。

**Comment by w19960528** [comment]
demo地址: https://github.com/w19960528/demo.git
GridManagerVersion：2.16.3
试了一下如果把操作中template去掉它会显示正常。另外，我高度设置的为100%，如果去掉这个参数他会显示正常。
UI使用的是vuetify。可能某些地方跟vuetify有冲突。

**Comment by baukh789** [comment]
我并没有复现，可以测试下在template内使用非vuetify相关的元素，确认下是否为样式冲突
