### ISSUE TITLE
建议增加拖动表头实现列隐藏和固定功能

### ISSUE THREAD

**Issue by oopyoung** [baukh789/GridManager#236]
![image](https://user-images.githubusercontent.com/11434784/141882842-0a595274-22a8-4d90-b0f8-f1b88c013613.png)
类似于layui-soultable里面的这个功能

**Comment by baukh789** [comment]
谢谢你提的建议，不过我没有完全明白你所指的是哪个功能，建议详细描述一下。

**Comment by oopyoung** [comment]
谢谢作者关注，就是在表头增加拖动的事件，拖动表头时：1.向上拖动出现删除的图标，然后将本列隐藏。2.拖动时出现固定菜单，可以将某列固定（固定就是当横向可以拖动时，该列保持不拖动）

**Comment by baukh789** [comment]
感谢你的提议，针对于这个交互，我需要调研一下使用的场景和范围。
暂时可能不会增加该功能，因为这样会改变现有表头的拖动交互(现有的表头拖动用于左右移动)。
