### ISSUE TITLE
表格行高在一行记录时显示有问题

### ISSUE THREAD

**Issue by liuzhaolei107** [baukh789/GridManager#238]
表格行高在不能填满时，能否按设置的行高进行展示，不要自动计算行高。

**Comment by baukh789** [comment]
关于行高，请参考下[API lineHeight](https://gridmanager.lovejavascript.com/api/index.html#lineHeight)

**Comment by liuzhaolei107** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by liuzhaolei107** [comment]
设置完行高，如果只有记录数比较少，就会自动填充，这是不应该的[grid-manager].gm-ready{visibility:inherit;height: 30px;}我在这个地方加了一个高度才控制住，但是这个应该是不对的

**Comment by baukh789** [comment]
你的意思可能并不是行高，而指的是整个表格的高度随着内容自动变化。你可以设置height为auto，但需要注意下：这并不是一种常用的表格高度处理方式。

**Comment by liuzhaolei107** [comment]
可否加微信我截图说明，这块可能是存在问题的，主要是tr继承了整个表格容器的高度100%，导致的问题

**Comment by baukh789** [comment]
网址上有微信群的加入方式
