### ISSUE TITLE
表格在从无到有动态添加数据时，出现纵向滚动条后表格宽度自动增长

### ISSUE THREAD

**Issue by liuzhaolei107** [baukh789/GridManager#239]
表格在从无到有动态添加数据时，出现纵向滚动条后表格宽度自动增长，无法控制，是用的方法是GridManager.setAjaxData

**Comment by baukh789** [comment]
setAjaxData用于组件不管控数据的情况，也就是说这种情况下所有的数据处理都由你自行解决。
如果想简化操作，参考下api ajaxData

**Comment by liuzhaolei107** [comment]
这个也不是说数据问题，这块很可能是表格自动列宽处，出现滚动条后内部逻辑出现的问题，我给你一演示你应该就知道我描述的问题了
