### ISSUE TITLE
参数问题

### ISSUE THREAD

**Issue by a-l-o-n-g** [baukh789/GridManager#240]
请问下传过来的请求参数（query）是自动解码（decodeURIComponent）了吗?
由于在代码中未看到相关处理，因此过来问下这里的逻辑是怎样的。

**Comment by baukh789** [comment]
这个主要是看你的ajax是怎么写的了，如果是自已处理的http那就自已的逻辑；如果不是自已处理的，用的就是[jtool ajax](https://github.com/baukh789/GridManager/blob/master/src/jTool/Ajax.ts)的逻辑。
