### ISSUE TITLE
tooltip

### ISSUE THREAD

**Issue by a-l-o-n-g** [baukh789/GridManager#241]
![image](https://user-images.githubusercontent.com/25051361/147621520-2c33a121-a360-449a-9cc4-cb79434c45f7.png)
如上图，在cellHover事件中可通过返回{ text: '这里有个提示' }来显示tooltip；由于tooltip高度是30px,，如果提示过长显示就会有问题，如果改为auto，则定位不准，有什么方法可以解决这种异常呢

**Comment by baukh789** [comment]
当前版本不支持对tooltip的样式进行配置，如果确实需要调整可以对`gm-tooltip`中的`height`进行样式覆盖。
