### ISSUE TITLE
建议添加英文版的文档和DEMO

### ISSUE THREAD

**Issue by wossig** [baukh789/GridManager#242]
如题， GridManager我看下来，她确实很强大，功能很丰富，我目前技术栈内用到的Grid是用的ag-grid, 建议作者去参考下， ag-grid有的功能，GridManger大部分都支持， 不仅如此GridManger还支持不少ag-grid作为付费版的内容，这就很强大了，所以如果有英文版， 我觉得国外的朋友才能看到，可以让GridManger走得更好。

**Comment by baukh789** [comment]
感谢你的提议，关于英语相关的文档与demo已经有了相关的计划，在一个工作相对清闲的时候，这个事情会被处理的。
再次感谢！
