### ISSUE TITLE
绑定查询数据后，表格上的历史数据未清除

### ISSUE THREAD

**Issue by TonyChan993** [baukh789/GridManager#244]
#### 重现步骤如下
1. 表格通过`firstLoading`载入数据
2. `GM.setQuery`调用进行查询
3. 查询当返回数据`response.data.length==1`，表格中显示的数据仅刷第一行被刷新，其余历史数据未被清除

#### 查询前
![image](https://user-images.githubusercontent.com/21140166/155958086-a167e802-683f-4f09-a141-2a48201de3f9.png)
#### 查询后
![image](https://user-images.githubusercontent.com/21140166/155958353-76ba0d5f-a045-4c47-9e11-f92040ea8cd4.png)

**Comment by baukh789** [comment]
收到，感谢你的反馈

**Comment by baukh789** [comment]
@TonyChan993  问题已修复，请更新至v2.18.2
