### ISSUE TITLE
请问如何解决预选中记录？

### ISSUE THREAD

**Issue by 0obuwawao0** [baukh789/GridManager#245]
我要做的功能 就像是 QQ邮箱一样

**已勾选本页 100 封邮件，勾选"收件箱"中全部 888 封邮件**
那么 点了 **勾选"收件箱"中全部 888 封邮件** 之后 所有分页拿到的数据后，都应该是勾选状态。
我通过 在 ajaxSuccess 事件里 
GridManager.setCheckedData(gridManagerName, GridManager.getTableData(gridManagerName));

做这样的操作，但没成功

**Comment by 0obuwawao0** [comment]
搞定了，通过群友了解了 可以用 rowRenderHandler 方法解决了

**Comment by baukh789** [comment]
还有另外一种方式:
```javascript
// AllData需要提前将所有数据获取，并传入已选中数据池
GridManager.setCheckedData(gridManagerName, AllData);
```

这种方式的优势是不会干预由gm控制的数据状态，但缺点也很明显: 数据量特别大时，接口压力过大。

`rowRenderHandler `方式正好与之相反，可以根据当前的需求进行选择。

**Comment by 0obuwawao0** [comment]
> 

好的，多谢解答
