### ISSUE TITLE
如果使用在H5移动端，表格会有问题吗

### ISSUE THREAD

**Issue by qiuweikangdev** [baukh789/GridManager#246]

**Comment by baukh789** [comment]
目标使用场景不是移动端，主要是做管理端的项目

**Comment by qiuweikangdev** [comment]
那如果在移动端使用的话，可以吗

**Comment by baukh789** [comment]
不太建议使用在移动端，虽然之前有人用过

**Comment by qiuweikangdev** [comment]
有滚动事件吗，滚动底部触发加载数据，如何做呢

**Comment by baukh789** [comment]
没有这种加载方式，有虚拟滚动，这是[demo](https://gridmanager.lovejavascript.com/demo/index.html#demo-virtualScroll)
