### ISSUE TITLE
参数问题

### ISSUE THREAD

**Issue by a-l-o-n-g** [baukh789/GridManager#248]
![image](https://user-images.githubusercontent.com/25051361/159861959-bcaad77e-9e8c-4a42-b2e6-4cba9820246b.png)
如果请求数据中有&符号，参数是做过处理吗？把&后面的数据直接转换成了key值

**Comment by baukh789** [comment]
可以将ajaxData设置返回promise，在函数内使用三方的http工具(如axios)进行处理。
