### ISSUE TITLE
dataKey指定问题

### ISSUE THREAD

**Issue by Bennie-liu** [baukh789/GridManager#249]
你好，我后台返回如下数据，提示说Rows不是一个Array，我应该怎么做才能正确绑定显示。望回复，多谢！
![image](https://user-images.githubusercontent.com/74805959/161890859-8bb762fd-4923-4937-8b8d-252712f886ad.png)

**Comment by BoWang816** [comment]
![image](https://user-images.githubusercontent.com/26587649/161909527-20867236-e8aa-491a-9318-fc0d6d1424b7.png)
默认key值是data，如果不是，需要你自己配置一下

**Comment by Bennie-liu** [comment]
![image](https://user-images.githubusercontent.com/74805959/161925445-abefc9af-1701-4c5b-a784-8cee833fb228.png)
如图，是有进行指定dataKey

**Comment by BoWang816** [comment]
那应该是你多套了一层，你可以在ajaxData或其他回调函数中打印一下response，是否是多了一层

**Comment by Bennie-liu** [comment]
对的，是会多一层。因为后台返回格式已经固定了，像这种多层级的指定dataKey可有方法。

**Comment by baukh789** [comment]
你可以在响应处理函数里把返回的数据进行整理，[参考API](https://gridmanager.lovejavascript.com/api/index.html#responseHandler)

**Comment by Bennie-liu** [comment]
嗯好的
