### ISSUE TITLE
表格的单元格宽度设置

### ISSUE THREAD

**Issue by wYuanHpp** [baukh789/GridManager#25]
表格的单元格的宽度是否可以强制设置为某个百分比，目前我在使用上发现很多时候设置完百分比宽度后，都不起作用。并且我也确定该宽度下 内容均可显示完整

**Comment by baukh789** [comment]
列宽设计时仅对像素进行了支持，并没特别针于%做出设计。

**Comment by wYuanHpp** [comment]
但是api文档上不是注明可以设置百分比么？

**Comment by baukh789** [comment]
你指的是表格的宽度，而不是表格所属单元格宽度。
![image](https://user-images.githubusercontent.com/11342827/28857740-1fd4d20a-777e-11e7-95de-79b6f20df78f.png)

**Comment by wYuanHpp** [comment]
好的 谢谢
