### ISSUE TITLE
表格直接右键，然后啥也不操作，直接点击旁边，此时右键菜单会关闭了，,此时跳转到其它页面后，上个页面的表格会报错，纯js版本， 【用的vue3】

### ISSUE THREAD

**Issue by frontend-qin** [baukh789/GridManager#250]
![image](https://user-images.githubusercontent.com/26999638/162396038-d53f352a-1759-4ecd-a76e-9c85e48215ec.png)
![image](https://user-images.githubusercontent.com/26999638/162396101-a2be70d8-a74b-42c7-8213-524a2fbdf922.png)

**Comment by baukh789** [comment]
当前版本并不支持vue3，使用原生版本无法在模板中使用Vue特性
