### ISSUE TITLE
表头拖拽大小后 固定的右侧设置出现边框错位

### ISSUE THREAD

**Issue by szz25** [baukh789/GridManager#254]
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/34016696/163963205-78ed140c-c4a0-48a0-a1b5-c0ad72e1fc52.png">

**Comment by szz25** [comment]
bug

**Comment by baukh789** [comment]
你可以在本地运行下[demo](http://develop.lovejavascript.com/gridmanager/demo/demo1.html)，如果也存在该问题，请提供下系统信息和浏览器版本信息。
