### ISSUE TITLE
GridManager Error  render tbody error  index.js:1 TypeError: $(...).html(...).replaceAll is not a function

### ISSUE THREAD

**Issue by EwingTsai** [baukh789/GridManager#255]
请问一下出现这种情况大概率是什么问题呢
![image](https://user-images.githubusercontent.com/24237413/164613028-e53ee028-440d-4923-9d5d-bc409afc8b3d.png)

**Comment by EwingTsai** [comment]
Chrome版本 80.0.3987.149（正式版本） （64 位）
在Safari和Edge浏览器下正常

**Comment by BoWang816** [comment]
浏览器版本太低，不支持replaceAll方法

![image](https://user-images.githubusercontent.com/26587649/164613937-71365a96-95bd-41e7-a2bb-20389ad05f52.png)

**Comment by EwingTsai** [comment]
@BoWang816 感谢。但是奇怪的是同一个浏览器上，另一个项目用它就没问题，难道是其他js补充了这个方法。。

**Comment by BoWang816** [comment]
> @BoWang816 感谢。但是奇怪的是同一个浏览器上，另一个项目用它就没问题，难道是其他js补充了这个方法。。

可能你另一个项目里面使用了polyfill做了兼容低版本浏览器的功能

**Comment by EwingTsai** [comment]
@BoWang816 好的，谢谢

**Comment by baukh789** [comment]
GridManager中并没有使用到replaceAll，chrome支持56及以上。
报错的代码并不在GridManager内。

**Comment by EwingTsai** [comment]
> GridManager中并没有使用到replaceAll，chrome支持56及以上。 报错的代码并不在GridManager内。

原因定位到了，是我自己的模板方法里报错了，有办法catch一下，以错误信息展示吗
