### ISSUE TITLE
动态创建销毁表格时报 Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by EwingTsai** [baukh789/GridManager#256]
动态创建和覆盖html标签：
`<table id='main-table'></table>`

动态使用标签创建和销毁表格（先销毁后创建）：
`GridManager.destroy('main-table'); 
document.querySelector('#main-table').GM({gridManagerName: 'main-table', ......})`

在执行第二次销毁和创建时报错：
![image](https://user-images.githubusercontent.com/24237413/164646336-3f529146-64e4-4dc7-8525-aa87fc36b613.png)

![image](https://user-images.githubusercontent.com/24237413/164646506-72e76beb-7819-4c00-83fb-664230a9160d.png)

导致报错的代码：
`setTimeout((()=>{
                    n.style.maxHeight = (t.height() - 90 - 20 - s.height() || 0) + Ke,
                    o.css("visibility", "inherit")
   }))`

**Comment by EwingTsai** [comment]
本地做了一下简单的修改解决了，希望官方修复一下。。
`setTimeout((()=>{
n&&(n.style.maxHeight=(t.height()-90-20-s.height()||0)+Ke), o.css("visibility","inherit")
}))`

**Comment by baukh789** [comment]
建议在销毁后，异步执行初始化方法。因为浏览器在处理DOM操作时，本身存在延迟。

另外，v3.0.0以上版本，可以动态修改表头信息了，[renderGrid的传送门](https://gridmanager.lovejavascript.com/api/index.html#renderGrid)

**Comment by EwingTsai** [comment]
@baukh789 感谢，已经用上最新版了。使用setTimeout()创建依然会出现上述问题，希望兼容一下，避免下次升级后再次出现。
