### ISSUE TITLE
columnData内的width 和 align 两个属性 配置后不起作用

### ISSUE THREAD

**Issue by wYuanHpp** [baukh789/GridManager#26]
问题如标题 谢谢
![image](https://user-images.githubusercontent.com/20528803/29016064-630e0c86-7b83-11e7-9f3d-0edaefa86f6b.png)

**Comment by baukh789** [comment]
该宽度不得小于实际宽度， 正如文档中所提到的: 
![image](https://user-images.githubusercontent.com/11342827/29023709-77b4adb6-7ba1-11e7-8bac-3b4bd14f5bba.png)

**Comment by wYuanHpp** [comment]
我确认 设置宽度绝对大于文本实际占用宽度 依然不生效

**Comment by baukh789** [comment]
20像素应该是不可以的，因为GM要在TH区域添加宽度调整、表头提醒、排序的触发区域，以及padding值。 
以下是demo中的示例，希望可以帮到你
![image](https://user-images.githubusercontent.com/11342827/29116313-fc6a30ee-7d2c-11e7-8377-914f08c1aa87.png)

**Comment by wYuanHpp** [comment]
是的 但是后来我把宽度调整为50 甚至 70 都依然不可用

**Comment by baukh789** [comment]
使用get方法查看下版本号，验证是否为版本过低。
```
document.querySelector('table').GM('get').version
```
