### ISSUE TITLE
可否增加一个设置某 行、单元格背景色的api

### ISSUE THREAD

**Issue by oopyoung** [baukh789/GridManager#261]
如题，要动态设置单行或某单元格的背景色，貌似没有什么很好的办法，作者可否指点一二

**Comment by baukh789** [comment]
没有直接修改背景色的API，不过你可以通过下面的方法实现:
[rowRenderHandler](https://gridmanager.lovejavascript.com/api/index.html#rowRenderHandler)可以为行设置className，也可以通过操作数据，并通过在`template`进行区别处理。

**Comment by oopyoung** [comment]
👍🏻 测试过有效，改变一行的背景
`
,
rowRenderHandler: (row, index) => {
         if(row.id === 888) {
	    row.gm_row_class_name="highlight-bg";
         }
         return row;
}
// 最关键的是设置td的样式
.highlight-bg td {
	background: #0f88eb !important;
}
`
