### ISSUE TITLE
表格在tabs分页组件内显示

### ISSUE THREAD

**Issue by yllalovelyrali** [baukh789/GridManager#262]
您好 站长
我这边做了一个分页组件，用的是antd tabs
然后需要在每个分页里面显示我们的GridManager
遇到一个问题，就是在第一个分页可以显示表格没有问题，但是第二个分页就无法显示了

两个分页的表格都是用了默认的option
能问问我是什么属性没有配置对吗

**Comment by baukh789** [comment]
- 需要确保gridManagerName的唯一性
- tabs 内容被隐藏时，尽量销毁容器
