### ISSUE TITLE
文档！！！

### ISSUE THREAD

**Issue by hjzg** [baukh789/GridManager#269]
如果考虑服务器成本的话 建议把文档内容放到github（GridManager）

**Comment by baukh789** [comment]
暂时还没有考虑这块，谢谢反馈

**Comment by hjzg** [comment]
没有文档对开发效率这一块  有一定的影响

**Comment by BoWang816** [comment]
> 没有文档对开发效率这一块 有一定的影响

有在线文档，http://gridmanager.lovejavascript.com/api/index.html

**Comment by hjzg** [comment]
谢谢！
但是访问不了

**Comment by hjzg** [comment]
@BoWang816  
谢谢！
但是访问不了

**Comment by hjzg** [comment]
@BoWang816 打开后 直接跳到反诈网站，个人判断，域名当中的“love”字眼，有影响到，建议更换

**Comment by BoWang816** [comment]
> @BoWang816 打开后 直接跳到反诈网站，个人判断，域名当中的“love”字眼，有影响到，建议更换

不接受建议，这是你自己电脑上或浏览器上面有相关的插件导致的

**Comment by hjzg** [comment]
现在的情况，不是我一个人的电脑上出现这种情况，别人的也是
手机上打开也一样
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baukh789/GridManager"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月12日(星期五) 上午8:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baukh789/GridManager] 文档！！！ (Issue #269)





  
@BoWang816 打开后 直接跳到反诈网站，个人判断，域名当中的“love”字眼，有影响到，建议更换
  
不接受建议，这是你自己电脑上或浏览器上面有相关的插件导致的

**Comment by hjzg** [comment]
@BoWang816  我让好多人试过，电脑各种浏览器和手机   基本可以确信 是域名的问题

**Comment by baukh789** [comment]
这个域名[域名](https://gridmanager.lovejavascript.com/)，在很多设备上都试过了，没发现你说的问题

**Comment by hjzg** [comment]
@baukh789  请问你是哪个地区的网络

**Comment by hjzg** [comment]
@baukh789 找到原因了  是网络环境的问题 我用的是江苏地区的网络（江苏省对域名中可能存在的敏感词汇进行了拦截） 都打不开  其他地区的都可以
