### ISSUE TITLE
关于翻页查询后跳转到第一页的问题

### ISSUE THREAD

**Issue by jwyhanliang512** [baukh789/GridManager#27]
请问下，当我跳转到了第4页，然后进行搜索，数据只有不到两页，这样当前显示为空白，还得自己输入跳转到第一页，如何自动跳转到第一页？类似这个问题[https://github.com/baukh789/GridManager/issues/24](url)，我看到API说【5. 可以通过在参数query中添加cPage字段对分页进行控制，如=> {cPage: 1}】，但是前面有【1. query的key值如果与分页及排序等字段冲突, query中的值将会被忽略.】，另外，我尝试在【table.GM('setQuery', _query)】后进行【table.GM('refreshGrid', true);】,也没有生效。还请麻烦讲解一下~~

**Comment by jwyhanliang512** [comment]
不好意思，刚点了关闭，我尝试在【table.GM('setQuery', _query)】后进行【table.GM('refreshGrid', true);】，发现进行了两次查询操作，这样子不是很友好？如何在setQuery的时候，就直接跳到第一页？

**Comment by baukh789** [comment]
已经确认， 这块存在BUG。 谢谢你的提醒，我正在修复。 你可以绕过这块先处理其它项。新版本发布后，我会在这里说明的。谢谢

**Comment by baukh789** [comment]
已经发布，
![image](https://user-images.githubusercontent.com/11342827/29219670-4614fc1e-7eeb-11e7-964a-c6ee467402e7.png)

**Comment by jwyhanliang512** [comment]
OK，辛苦~

**Comment by jwyhanliang512** [comment]
你好，请问下，在分页事件执行前，如何方便更改query参数？比如，表格初始化条件为a,b,c。后面分页时，我想增加查询条件为a,b,c,d,，API有没有考虑增加这个情况？
