### ISSUE TITLE
列隐藏的数据点击后展开

### ISSUE THREAD

**Issue by hanxiao123** [baukh789/GridManager#271]
希望能加入一个功能：列隐藏的数据点击箭头后可以展开全部
![image](https://user-images.githubusercontent.com/17881934/183400310-aecf2c07-4f01-41b0-a92e-6ede2a93f747.png)
![image](https://user-images.githubusercontent.com/17881934/183400336-023153db-837f-4412-89ad-07f137a3463f.png)
列数据较多时，能有一个按钮展开显示全部数据

**Comment by hanxiao123** [comment]
![image](https://user-images.githubusercontent.com/17881934/183400573-d5feda24-c6c2-4195-b5f1-b3d535f394fb.png)

**Comment by baukh789** [comment]
收到，感谢反馈。
目前该需求可以在template内自行实现，再次感谢。

**Comment by hanxiao123** [comment]
请问如果自行实现，怎样知道当前列的部分信息是有被隐藏的？

**Comment by baukh789** [comment]
可以在渲染前获取文本的宽度，如果文本宽度超出了td的宽度就是有文本被隐藏了。
或者你可以用另外一种方式: 在模板内对文本进行换行处理。
