### ISSUE TITLE
有复杂表头时不能拖动改变列宽

### ISSUE THREAD

**Issue by hanxiao123** [baukh789/GridManager#272]
已经设置了开启拖动改变列宽，但有复杂表头时拖动失效了，希望可以加入按指定列改变列宽的功能

**Comment by baukh789** [comment]
嵌套表头与宽度调整、位置更换等功能是不能同时使用的，短期内并没有计划要对这块进行调整。

**Comment by hanxiao123** [comment]
能否提供一下实现思路？
