### ISSUE TITLE
列属性isShow=false时只隐藏了表头的所在列

### ISSUE THREAD

**Issue by hanxiao123** [baukh789/GridManager#273]
列属性isShow=false时只隐藏了表头的所在列，下面的数据行对应的列并没有隐藏，整体数据列就错位了

**Comment by baukh789** [comment]
这个与嵌套表格中是冲突的

**Comment by hanxiao123** [comment]
在有嵌套列需求的情况下，为了让操作列能拿到rowObject里的id提交到后台，绑定了id列，但又不想显示id列，那这种情况怎么能拿到所在行的id?

**Comment by baukh789** [comment]
template的第二个参数可以获取到当前行的所有数据，建议看一下[API](https://gridmanager.lovejavascript.com/api/index.html#columnData)。
