### ISSUE TITLE
虚拟滚动cellHover功能返回提示错位

### ISSUE THREAD

**Issue by Koilzy** [baukh789/GridManager#278]
设置了虚拟滚动了，部分元素cellHover会出现tooltip错位问题（图一）。滚动到比较下面的元素时，直接没有tooltip提示了（也可能是错位问题被挡到了）（图二）
![image](https://user-images.githubusercontent.com/103628367/201030787-75f69e95-64c6-4653-9c8a-a8784e7d9ff0.png)
![image](https://user-images.githubusercontent.com/103628367/201030847-ef30f1de-0277-40c6-b9c8-181f0e158049.png)
![image](https://user-images.githubusercontent.com/103628367/201031153-8d75852a-f80a-4cae-be61-3d33bfeca188.png)

**Comment by baukh789** [comment]
tooltip与虚拟滚动存在冲突，已在V3.2.0中修复，希望可以帮助到你。
