### ISSUE TITLE
超宽表(col>500)的性能问题

### ISSUE THREAD

**Issue by ZzMark** [baukh789/GridManager#279]
目前我们业务有用到超宽表格，因为DOM过多导致性能很惨
(500列甚至1000列的情况，行数反而不多，存在不超过三级的嵌套表头)

是否有可能将虚拟滚动应用到横向表格

**Comment by baukh789** [comment]
目前并没有虚拟列功能，如果行数固定，可以将表头与第一列的位置互换展示。

**Comment by ZzMark** [comment]
遗憾的是超宽表格是业务部门提出的需求，没办法改为纵向

目前测试结果是，仅宽表格(col ~ 100)的情况还能接受，超过 300 帧数就很低了

稍后我研究下 changeTableData 能否增加这个功能，若有成果我提个pr
