### ISSUE TITLE
希望增加 afterRender 事件，或修复 ajaxSuccess 隐藏列与右键设置里的列不一致bug

### ISSUE THREAD

**Issue by canuran** [baukh789/GridManager#281]
有些场景表格列太多，我使用 ajaxSuccess 来隐藏全是空白数据的列，有两个问题
1、需要对 ajaxSuccess 的数据进行JSON解析，不能使用 getTableData 直接获取
2、此时隐藏列后，在右键菜单里显示该列被仍然勾选

在渲染完成后再隐藏列则没有问题，但由于数据是异步加载再渲染的，并不知道它什么时候渲染完成，希望通过 afterRender 事件来触发

**Comment by baukh789** [comment]
感谢你的建议，我会尽快的进行评估，如果可行的话会提供相应的事件函数。

**Comment by canuran** [comment]
Get！确实也是一种解决方法，只不过使用起来有些绕，需要先创建空白表格，再调用内置函数去加载数据，如果能在创建时就提供回调会更简单明了，仅个人建议~

**Comment by baukh789** [comment]
建议在初始化时增加`firstLoading: false`参数, 这种模式将数据的渲染触发交给了使用者。使用者在合适的地方再调用渲染方法，如setQuery
