### ISSUE TITLE
发现3个问题，前台分页参数如何get，还有排序没有效果，最后一个就是后台如果没有传递参数table会渲染默认值undefined

### ISSUE THREAD

**Issue by adminPan** [baukh789/GridManager#29]

**Comment by baukh789** [comment]
1、在发起请求后，你通过请求链接上的请求参可以核对。至于在后端语言中如何获取，需要根据请求方式及使用的何种后端语言来进行对应处理。
2、排序请参照demo及api
3、后端需要按照规定格式进行数据返回，详情参与api
