### ISSUE TITLE
数据15条，每页规定pagesize=10，为什么没有实现分页？

### ISSUE THREAD

**Issue by AbbyWB** [baukh789/GridManager#3]
没有实现分页，同时，两页的数据完全一样，不晓得哪里出错了？求指教

**Comment by baukh789** [comment]
你好，你应该在配置中使用的是静态数据源。修改方法如下：
1、移除静态数据参数[ajax_data]。
2、使用动态数据获取地址参数[ajax_url]。
参数详解：
参数[ajax_url]=>获取表格数据地址，配置该参数后，将会动态获取数据。
参数[ajax_data]=>ajax静态数据,配置后将不再通过ajax_url进行数据请求,且ajax_beforeSend、ajax_error、ajax_complete将失效，仅有ajax_success会被执行。

希望可以帮到你，你可以参考下src/demo2.html。
