### ISSUE TITLE
分页为什么只能看到第一页 点下一页还是第一页的内容

### ISSUE THREAD

**Issue by xiaoxi233** [baukh789/GridManager#31]

**Comment by baukh789** [comment]
请对照一下demo中的数据返回格式，具体的请参考API文档中的ajax_url参数介绍。

**Comment by xiaoxi233** [comment]
![image](https://user-images.githubusercontent.com/29827048/29305985-f1387712-81cd-11e7-8b9c-19d3d256ba17.png)
这样不对？

**Comment by xiaoxi233** [comment]
@baukh789

**Comment by baukh789** [comment]
前端只做分页参数传递，后端需要对分页参数进行处理，并返回对应的数据。 建议你看一下API和DEMO示例

**Comment by xiaoxi233** [comment]
@baukh789 这个插件在tp框架要怎么用？ 表示后端不会用，我是小白，请见谅
这是我的后端代码，感觉有问题
![image](https://user-images.githubusercontent.com/29827048/29310660-2a5508d6-81e1-11e7-9014-2a2a22ac389e.png)

**Comment by baukh789** [comment]
我没学过PHP， 这个你找个后端同学了解下吧。

**Comment by xiaoxi233** [comment]
抓了下包发现神的东西然后懂了 谢谢！！！
