### ISSUE TITLE
karma配合ES6的问题

### ISSUE THREAD

**Issue by lisleyang** [baukh789/GridManager#37]
您好，一直把您的项目当作自己的一个教程，受益匪浅；
看到您最近添加了单元测试的内容，想了解下您是如何实现在断言中使用ES6语法，比如import之类的？

**Comment by baukh789** [comment]
在断言里面不能使用import，可以使用equire。
示例:
```javascrpit
equire('../src/js/GridManager').default;
```

**Comment by lisleyang** [comment]
我说错了，不是断言，就是*.test.js文件中如何使用import引入需要测试的js文件，我在使用的时候一直在报import no defined

**Comment by baukh789** [comment]
你可以看一下这个项目中的使用方式，如果按同样方式报错的话。请检查你的依赖是否安装完整。
另外你如果想了解自动化测试，可以看一下我的jTool项目，相对于GridManager，jTool的自动化测试更全面一些。
