### ISSUE TITLE
GridManager不支持后端分页吗

### ISSUE THREAD

**Issue by weiyang7545** [baukh789/GridManager#38]
Demo中分页示例 ajax请求的json数据是全部的，只有一个totals字段，分页由前段完成吗？如果数据量很大，有没有后端分页的功能

**Comment by baukh789** [comment]
后端通过pSize(每页显示条数),cPage(当前页)参数进行分页，返回的数据是当前页的数据。具体的可以参考下API与DEMO。

**Comment by weiyang7545** [comment]
可能我没表述清楚，我指的后端是web后端数据API，我们通过total/current_page从接口请求回来的数据就应该是分好页的，不指GridManager后端处理过程，GridManager好像每次都是把数据都抓过来，再在本地进行分页操作

**Comment by weiyang7545** [comment]
接口类似于以下这种：
{
"page": 1,
"totals": 300,
"data": [
           {"id": "tiny",
           "name": "123",
           "age": 18,
            "gender": "male"
           }]
}
请问有支持吗？接口返回当前页数据

**Comment by baukh789** [comment]
你查看下DEMO中使用的数据格式，你可以直接在后端改成对应的格式。也可以通过参数responseHandler对返回的数据进行重置。

**Comment by weiyang7545** [comment]
分页的条数值不能自定义设置吗，有的话，怎么设呢

**Comment by baukh789** [comment]
参数pageSize，你看一下API。上面都有介绍的

**Comment by zonebond** [comment]
Good!!!

**Comment by weiyang7545** [comment]
调用方法setQuery能返回结果，但页码、条数都没有更新，请问是怎么回事呢，tSize和tPage这俩个参数又是怎么用的呢

**Comment by baukh789** [comment]
你可以把完整的代码粘上来，我看下

**Comment by weiyang7545** [comment]
插件很好用，非常感谢大神前期的帮忙！！ 最近碰到一个新的问题，网页导出excel报网络错误，导出的数据量有限制吗？

**Comment by weiyang7545** [comment]
好的，谢谢大神！

**Comment by Wnig** [comment]
搜索框搜索的筛选是已经写好的还是后台写的？
还有怎么控制每页显示条数？
删除，修改这些也都是前端传参数给后台，进行操作的吗？

**Comment by Wnig** [comment]
pageSize和sizeData都已经设置好了，为什么当前页还是把后台传来的数据全部显示出来了？
是要后台控制当前页显示条数吗？

**Comment by wang6688** [comment]
求助，为什么我点击 其他页码的时候 ，我的后台Controller 接收不到 cPage和pSize 参数。我的 Controller方法 头代码如下:

	@ResponseBody
	@RequestMapping(value = "getBidderProductList", method = RequestMethod.POST)
	public String getBidderProductList(	BidderProduct bidderProduct,	HttpServletRequest request,HttpServletResponse response,
			@RequestParam(required = false, defaultValue = "1") Integer cPage,
			@RequestParam(required = false, defaultValue = "15") Integer pSize) {
.........

}

**Comment by baukh789** [comment]
查看请求类型是否为post,查看请求参数是否存在cPage。
如果存在，后端按对应类型的接收就可以了。
另外附一个分页相关的介绍:http://www.lovejavascript.com/#!zone/blog/content.html?id=77
