### ISSUE TITLE
请问怎么设置可以让页面刚进入的时候不发送请求，点击查询的时候才发送请求

### ISSUE THREAD

**Issue by fengyefengxiang** [baukh789/GridManager#39]
如题；
蛋疼的产品非要提这种sb的需求，要进页面的时候是空白的，非要点击查询再查询出数据来。
欢迎屌大的大佬帮小弟解决下。

**Comment by baukh789** [comment]
第一次点击查询的时候再进行表格初始化， 之后再次点击查询则调用setQuery方法

**Comment by fengyefengxiang** [comment]
大佬可能没理解我意思，我现在对页面效果是刚跳转到这个页面到时候，表格里是有数据到，我点击查询到时候他是重新发了一次请求，我现在想要的效果是刚进页面不让他发请求，显示空白效果，点击查询的时候让表格里有数据。麻烦大佬里



table.GM({
                 gridManagerName: 'test'
                ,disableCache:false
                ,supportAjaxPage:true
                ,supportSorting: true
                ,isCombSorting: true
                ,supportDrag:true
                ,supportAutoOrder:true
                ,supportSorting:true
                ,supportCheckbox:true
                ,ajax_url: '/order/checkajax.php'
                ,ajax_type: 'POST'
                ,query: {pluginId: 1,call_search_state:$('input[name=call_search_state]').val()}
                ,pageSize:10
                ,columnData:cData
                ,ajax_success: function () {
                  console.log("成功");
                  if($('input[name=call_search_state]').val()) {
                      var name = util.cookie('call_search_data');
                      var obj = JSON.parse(name);
                      if($.isEmptyObject(obj)) {
                        return false;
                      }
                      $("input[name=start]").val(obj.start);
                      $("input[name=end]").val(obj.end);
                      $(".numbercode").val(obj.code);
                      $("input[name=receiver]").val(obj.receiver);
                      $("input[name=mobile]").val(obj.mobile);
                  }
                }
            });


            // 搜索
            $(".searchbtn").on("click",function(){

                var start      = $("input[name=start]").val() || "";
                var end        = $("input[name=end]").val() || "";
                //var code       = $("textarea[name=code]").val() || "";
                var code       = $(".numbercode").val() || "";
                var receiver   = $("input[name=receiver]").val() || "";
                var mobile     = $("input[name=mobile]").val() || "";
                var shop       = checkbox("_shop");
                var store      = checkbox("_store");
                var flag       = checkbox("_flag");

                var _query = {
                    start       : start,
                    end         : end,
                    code        : code,
                    receiver    : receiver,
                    mobile      : mobile,
                    shopid      : shop,
                    storeid     : store,
                    flag        : flag
                };

                util.cookie('call_search_data', JSON.stringify(_query), {expires:7});

              table.GM('setQuery', _query).GM('refreshGrid', function () {
                console.log('搜索成功...');
              });
            });

**Comment by baukh789** [comment]
初始进入表格渲染并不显示数据，暂时没有提供此类参数。
你们产品所考虑可能是性能优化，我考虑下是否有增加此类参数的必要。

**Comment by fengyefengxiang** [comment]
好的 大佬
