### ISSUE TITLE
宽度自适应BUG

### ISSUE THREAD

**Issue by boxui** [baukh789/GridManager#41]
`<div style="width:200px;padding:20px"><table></table></div>`
1、如果表格父级容器的padding为0的话，表格的宽度可100%自适应不会出现滚动条
2，如果表格父级容器设置padding的话，表格的宽度会出现横向滚动条

初步判定应该是在计算表格列宽度时没有把表格的父级padding减去的原因。

**Comment by baukh789** [comment]
这个是自适应的一个效果，当宽度满足不了表格的展示时， 会以出现横向滚动条来解决表头文字换行的问题。
还有，你所示例的HTML并不规范。 示例：
```html
<table grid-manager="demo-baseCode"></table>
```

**Comment by boxui** [comment]
谢谢大大回复。
HTML我只是个示例，实际是按你上面列的写。
实际应用场景是：
1，我表格只放了三列，父级容器宽度有1000PX,理论上宽度是绝对够的
2，如果我父级窗口把padding设置成0是表格是可以宽度自适应不出现滚动条的。
3，源码我没细看，但初步判定是不是在算表格各列宽度时直接拿的表格父级容器的宽度来计算（没减去padding)

**Comment by baukh789** [comment]
收到，待验证后，会找时间去修复
