### ISSUE TITLE
如何方便在分页事件或者其他事件里，修改query参数

### ISSUE THREAD

**Issue by jwyhanliang512** [baukh789/GridManager#42]
你好，请问下，在分页事件执行前，如何方便更改query参数？比如，表格初始化条件为a,b,c。后面分页时，我想增加查询条件为a,b,c,d,，API有没有考虑增加这个情况？

**Comment by jwyhanliang512** [comment]
我再补充下我那种做法的弊端，后台会进行两次查询

**Comment by baukh789** [comment]
请求前处理程序， 可以通过参数 requestHandler 进行配置，该程序可在分页、排序等数据请求前触发。
建议你在初始时，配置合理的query参数

**Comment by jwyhanliang512** [comment]
这个能在分页前触发吗？比如我现在在第一页，切到第二页的时候增加参数，这个requestHandler 是配置，是初始化的时候增加的，不是方法，效果跟setQuery差不多？还是我理解错误？

**Comment by jwyhanliang512** [comment]
我这边 
`document.querySelector('table').GM('get').responseHandler =  function(request){request.list = "dag";};`是错误的吗？参数并没有增加

**Comment by jwyhanliang512** [comment]
你好，可否大概说明下

**Comment by baukh789** [comment]
你看一下API，上面有示例的。 requestHandler是请求前执行程序，responseHandler是请求后

**Comment by jwyhanliang512** [comment]
requestHandler这个一样的啊，初始化表格的时候，参数已经加了进去了，我要的效果是，在分页切换的时候增加参数

**Comment by jwyhanliang512** [comment]
效果就是跟直接配置query参数一样

**Comment by baukh789** [comment]
requestHandler 是每次触发请求前都会执行的一个方法， 该方法可以更改请求时所用的参数。
这个方法里面可以使用 if 或者调用外部的变量对参数进行灵活的配置。

**Comment by jwyhanliang512** [comment]
好吧，我建议下一个版本可以考虑增加一个方法，能够修改查询参数。这种场景还是蛮多的~
