### ISSUE TITLE
为什么点搜索的时候会触发两次post请求？

### ISSUE THREAD

**Issue by hklliang** [baukh789/GridManager#46]

**Comment by baukh789** [comment]
贴段代码，或者是核对下setQuery 是否使用正确。

**Comment by hklliang** [comment]
` var table = document.querySelector('table');
    var TGM = table.GM({
        supportRemind: false
        , i18n: 'en-us'
        , gridManagerName: 'test'
        , isCombSorting: true
        , height: 'auto'
        , supportAjaxPage: true
        , supportSorting: true
        , isCombSorting: true
        , ajax_url: '/getHotelMap'
        , ajax_type: 'POST'
        , query: {status: 4}
        , pageSize: 30
        , sortDownText: '-1'
        , sortUpText: '1'
        , supportAjaxPage: true
        , columnData: [
            {
                key: 'gf_id',
                text: 'gf_id'
            },
            {
                key: 'supp_id',
                text: 'supp_id'
            },
            {`

`    document.querySelector('.search-action').addEventListener('click', function () {

        var _query = {
            gf_id: document.querySelector('[name="gf_id"]').value,
            supp_id: document.querySelector('[name="supp_id"]').value,
            supp_name: document.querySelector('[name="supp_name"]').value,
            supp_city: document.querySelector('[name="supp_city"]').value,
            country: document.querySelector('[name="country"]').value,
            status: $('.selectpicker[name="status"]').val(),
        };

        table.GM('setQuery', _query).GM('refreshGrid', function () {

        });
    });`

**Comment by hklliang** [comment]
![image](https://user-images.githubusercontent.com/24997125/32043490-72aab602-ba6d-11e7-8690-b5ac51490d91.png)
![image](https://user-images.githubusercontent.com/24997125/32043499-7ecccb82-ba6d-11e7-9c92-6414e77886b5.png)

**Comment by baukh789** [comment]
![image](https://user-images.githubusercontent.com/11342827/32045706-856966a2-ba73-11e7-93d9-1291690bbb47.png)

这个方法做过调整，从原先的只设置参数优化为了设置参数后即时刷新。

如果方便的话，把你看到的demo详细来源发一下。 我把遗漏的修正下

**Comment by hklliang** [comment]
![image](https://user-images.githubusercontent.com/24997125/32046238-0b293a82-ba75-11e7-8f6f-2412525dd21c.png)

![image](https://user-images.githubusercontent.com/24997125/32046207-f33c97b6-ba74-11e7-88e7-d7cfa05751e8.png)


demo5
那么我应该如何修改呢

**Comment by baukh789** [comment]
```javascirpt
table.GM('setQuery', _query, function(){
     console.log('搜索成功');
});
```
或者你去看下API中的详细介绍

**Comment by hklliang** [comment]
改好了，谢谢！
