### ISSUE TITLE
操作标签是通过onclick()绑定的，只能用function来做，后面用jq来增加点击事件没有效果，这是为什么呢？而且后面用jq增加css也是没有效果。

### ISSUE THREAD

**Issue by hklliang** [baukh789/GridManager#47]
![image](https://user-images.githubusercontent.com/24997125/32046897-f231b2d2-ba76-11e7-8423-00b04f7104a3.png)
![image](https://user-images.githubusercontent.com/24997125/32047019-49fd47ec-ba77-11e7-892e-db9f8c1fde21.png)

**Comment by baukh789** [comment]
你绑定事件的时候，DOM节点并没有渲染完。
你用的jquery的话建议看一下事件预绑定。
