### ISSUE TITLE
列居中问题

### ISSUE THREAD

**Issue by ynnyh** [baukh789/GridManager#48]
使用align属性时，发现不起作用，检查源码后发现是因为在css中给td设置了（text-align:left）样式，去掉该样式align属性就起作用了

**Comment by baukh789** [comment]
现在发布的版本是存在这个问题的, github上的源代码中已经修复了这个问题，但是并未发布。
你可以通过样式去修正，待新版本测试通过了，再下载新版本替换掉原来的文件。
或者也可以从github上下载现有的代码进行使用（github现有的源代码未完全测试）
