### ISSUE TITLE
列表导出

### ISSUE THREAD

**Issue by ynnyh** [baukh789/GridManager#50]
在点击右键导出列表时，发现只能导出表头，数据都没有导出来，请问是怎么回事呢

**Comment by baukh789** [comment]
请问
否为最新版的？
使用的什么浏览器？
如何配置的？

**Comment by ynnyh** [comment]
谷歌浏览器，使用的是2.3.14最新版的，配置里面我没有设置导出因为默认是可以导出的

**Comment by baukh789** [comment]
http://www.lovejavascript.com/node_modules/GridManager/demo/demo2.html
你在这个地址上试下，是否存在同样的问题。这个是我测试时写的demo

**Comment by ynnyh** [comment]
ajax_url: orderUrl,
                    ajax_type: 'GET',
                    query: data,
                    supportAutoOrder: true,
                    supportAjaxPage: true,
                    supportCheckbox: false,
                    supportConfig: false,
                    supportDrag: false,
                    disableCache: true,
                    height: ['560px'],
                    textAlign: "center",
                    emptyTemplate: "暂无数据",
这个是我的配置，里面我看没有影响到导出功能的啊

**Comment by ynnyh** [comment]
我有修改过源码里面的分页数据，这个会有影响吗

**Comment by baukh789** [comment]
你把各个参数核对下，比方说你的height配置就是错的。
应该是height:'560px'
API上的方括号只是个范围符的意思，可能对你有误导。
