### ISSUE TITLE
一个页面多个表格出错

### ISSUE THREAD

**Issue by lifeisgood1990** [baukh789/GridManager#51]
我的一个页面里有多个表格   有时候第一次近来表格 都能够正常显示  但再次刷新就会报错
如下
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element': 'th[th-name=]' is not a valid selector 
请问是什么问题

**Comment by baukh789** [comment]
配置时 多个表的gridManagerName 不能相同
单个表的columnData属性下的key不能相同且不能为空
