### ISSUE TITLE
某一列数据能固定在后面吗？

### ISSUE THREAD

**Issue by zhangweihua66** [baukh789/GridManager#54]
当表格中列数很多时，会挤出滚动条，一般对于每一行数据的操作会放在最后一列，此时，需要滚动滚动条才能找到操作列，可能导致操作错误。

**Comment by SycamoreYC** [comment]
你是要类似excel冻结功能么？如果是这个功能，暂时没有实现。

**Comment by baukh789** [comment]
固定列功能已经发布
