### ISSUE TITLE
请教两个问题，1后台接收不到cPage和pSize的参数问题，2怎样获得用户选择的复选框对应的值。

### ISSUE THREAD

**Issue by wang6688** [baukh789/GridManager#58]
1.

jsp 代码 : var table = document.querySelector('table'); table.GM({ supportRemind: true ,gridManagerName: 'test' // ,disableCache:true ,isCombSorting: true ,height: '300px' ,supportConfig: false ,supportExport:false ,supportAjaxPage:true ,supportSorting: true ,ajax_url: '${ctx}/exBidRegister/getBidderProductList' // ,ajax_headers: {'header-test': 'baukh'} ,ajax_type: 'post' ,query: {} ,pageSize:10 ,dataKey: 'list' // 注意: 这里是用来测试responseHandler 是否生效; 数据本身返回为data, 而在这里我把数据名模拟为list, 再通过responseHandler去更改 ,totalsKey: 'count' // 指定总数 key 为 number ....});

后台Controller 代码如下 :

@ResponseBody @RequestMapping(value = "getBidderProductList", method = RequestMethod.POST) public String getBidderProductList( BidderProduct bidderProduct, HttpServletRequest request,HttpServletResponse response, @RequestParam(required = true, defaultValue = "1") int cPage, @RequestParam(required = true, defaultValue = "10") int pSize) { ...... }

经查看ajax 发送的post的 参数如下: pSize=10&cPage=4&tPage=5&tSize=47&sort_createDate=DESC 可是 当 点击其他页码的时候可以进入我写的Controller 方法，可是 就是 接收不到 cPage 和pSize参数。

2.我查看API中 发现有getCheckedData()方法，但是怎么触发调用这个方法呢。 还有我想将数据记录的id隐藏在checkbox中，这样我在点击 选中时 就可以得到这个id的值 了。我就能进行后续操作了。 请指教，我该怎么操作。

**Comment by baukh789** [comment]
关于后端取不到的问题，使用post向后端发送的是from data格式的数据。
希望你自已通过后端方法去处理下。
关于getCheckedData的用法，
```javascript
document.querySelector('table').GM('getCheckedData');
```
其中table是你当前的DOM节点， 如果用的jquery, 也可以直接使用jquery对象进行调用
```javascript
$('table').GM('getCheckedData');
```
方法返回的是个数组， 该数组包含当前渲染行所使用的数据，将会包含你所需要的id值(如果数据列表中存在的话)
另外，时间允许的话，你把提问的格式整理下

**Comment by SuperHaoSunMan** [comment]
1.你编写的问题格式可以调整下，利于查看问题
2.接收不到 cPage 和pSize参数是因为前面的参数你是用对象去接收的，而cPage和pSize是由于你虽然用了@requestparam但是你没有指定你的这两个参数到底接收的是什么？正确的写法是
@requestparam(value=''cPage",required = true, defaultValue = "1") int cPage, @requestparam(value=''pSize",required = true, defaultValue = "10") int pSize) 即可接收
