### ISSUE TITLE
请教一个问题 pageSize设置后没有生效

### ISSUE THREAD

**Issue by zhaojun0193** [baukh789/GridManager#60]
配置了pageSize没有生效，每次进入页面还是显示的30 但是我配置的是10
我是这样配置的
`... ,ajax_type: 'POST' 
  ,pageSize:10
   ,sizeData:[10,20,30] ...`

是我哪里还没有配置好吗？
谢谢

**Comment by zhaojun0193** [comment]
找到原因了，我用的版本是2.2的版本 升级版本后问题解决了。还有请求参数的获取方式变得更加方便了：）
感谢作者~

**Comment by baukh789** [comment]
每页显示条数在默认情况下会被记忆，这个是组件的一个特性。

配置项disableCache，你可以看一下API。可能对你有帮助。
