### ISSUE TITLE
关于跨域的设置

### ISSUE THREAD

**Issue by lifeisgood1990** [baukh789/GridManager#61]
怎么设置跨域请求带上cookie
jquery ajax请求是这样的 如下
crossDomain: true,
xhrFields: {
         withCredentials: true
 },

**Comment by baukh789** [comment]
暂时没有这个配置项

**Comment by baukh789** [comment]
v2.4.0已发布
```javascript
document.querySelector('table').GM({
   // 配置xhr, 如: withCredentials -> 跨域情况使用cookie等证书. 需要在后端进行对应的配置
    ajax_xhrFields: {
         withCredentials: true
    }
    // 其它配置项...
});
```
另附withCredentials 参考链接: http://www.lovejavascript.com/#!zone/blog/content.html?id=59
