### ISSUE TITLE
关于排序的问题

### ISSUE THREAD

**Issue by Strive-Java** [baukh789/GridManager#62]
点击排序的时候，总页码，变成 undefined

**Comment by baukh789** [comment]
不是很了解你把描述的场景。
请将对应的代码 和 错误信息 追加到问题描述中。

**Comment by Strive-Java** [comment]
问题如下截图

![issue](https://user-images.githubusercontent.com/20058791/33803662-c551b79a-ddcf-11e7-8c0d-dd589a62e243.jpg)

![test](https://user-images.githubusercontent.com/20058791/33803690-863c8ba6-ddd0-11e7-9ba1-b8e5d9d16270.jpg)

![test1](https://user-images.githubusercontent.com/20058791/33803692-93c646fe-ddd0-11e7-9243-6b080bb3b29f.jpg)

**Comment by Strive-Java** [comment]
按道理，当前页面排序，只会排序当前页的数据，像这种情况，永远只能排序第一页的数据了。

**Comment by baukh789** [comment]
现有的排序是基于以下逻辑实现的:
1、排序生效的是全部数据，而非当前页。
2、排序在触发后，会跳转至第一页。

**Comment by Strive-Java** [comment]
你好！对于大数据量，整表操作排序比较耗时，我现在想把他改成只对当前页面数据排序，点击排序时在哪里可以保持 tPage 不会被置空，没有找到修改的地方。  谢谢！
源码 1664 line 获取param参数
    var pram = _jTool2.default.extend(true, {}, settings.query);

**Comment by baukh789** [comment]
你看到的只是生成出的代码，原代码逻辑我正在修改。
下个版本将会对排序进行调整: 在排序触发时，分页将默认保持在当前页； 而不再重置为第一页。
这个版本正在最后测试阶段，发布后我将第一时间通知你。

**Comment by silence717** [comment]
@Strive-Java 能把你现在使用的样式文件给我一份？我想添加一套皮肤上去，感觉你这个样式还不错，谢谢！我的邮箱是：yangfang2028@126.com。

**Comment by Strive-Java** [comment]
ok

**Comment by baukh789** [comment]
v2.4.0已经发布，你可以更新下，排序问题已经处理。
另，感 @silence717 @Strive-Java 你们提供的样式。

**Comment by chuchuzhao** [comment]
排序只支持字符串格式吗？？

**Comment by baukh789** [comment]
@chuchuzhao GridManager的排序是在事件触发后，由组件发起一个包含排序信息的请求。具体的排序逻辑由请求服务程序处理。
通过配置项sortUpText与sortDownText可以指定传递的排序标识，详看[API](http://gridmanager.lovejavascript.com/api/index.html#sortUpText)

**Comment by baukh789** [comment]
关于排序的问题， 直接查看这里-> [排序详解](http://www.lovejavascript.com/#!zone/blog/content.html?id=78)

**Comment by cafugiggs** [comment]
大神，请问我进行了一次排序以后如何再取消排序？
希望能在界面上操作，即：点击向上箭头（如升序），再次点击向上箭头则取消排序，可以吗?

**Comment by baukh789** [comment]
@cafugiggs 现在的版本交互和你所期望的效果有些出入，点击事件是在升降序之间进行切换。

**Comment by cafugiggs** [comment]
额，今后可以提供一个取消排序的功能吗？

**Comment by baukh789** [comment]
通过setSort方法可以自由设置排序。
至于修改现有的点击交互，这个需要考虑一下，因为这个会影响到其它用户的使用。

**Comment by baukh789** [comment]
@cafugiggs 
排序的交互:
- 单列排序:点击将会将现有方向取反。
- 多列排序: 
     - isCombSorting===false: 触发其它例的排序会将其它列的排序重置为空
     - isCombSorting === true: 触发其它例的排序会将已设置列的排序保留

**Comment by cafugiggs** [comment]
明白

**Comment by baukh789** [comment]
@cafugiggs 
v2.8.9 对应vue版本v1.1.9中新增 `sortMode`参数，可以通过将该参数设置为`single`来实现你所期望的效果。
