### ISSUE TITLE
关于发起请求中参数的问题

### ISSUE THREAD

**Issue by Balis0ng** [baukh789/GridManager#65]
目前我用setQuery控制请求参数的时候发现，如果我上一步对表格排过序，那么这一步请求会把表格排序的参数带进去，有没有什么方法只是单独的发送我设置的请求参数，而不带入排序分页等参数？

**Comment by baukh789** [comment]
setQuery方法触发后，默认会将分页重置至第一页。
如果想在调用setQuery时清除排序， 可以在调用前通过setSort方法实现。 但是需要注意的是第三个参数需要配置为false, 以防止刷新两次。
具体的操作，请查看API

**Comment by Balis0ng** [comment]
还是不行啊，试了之后，
` var sort={
            name: treeNode.id
        };
        table.GM('setSort',sort,function (){
        		table.GM('setQuery', _query);
        },true);`
这样用吗？？但是还是会有排序带入进来。

**Comment by Balis0ng** [comment]
那么该如何做..API太简洁了，我怎么操作感觉都没效果，比如:
`        var _query = {
            dir: treeNode.id
		};
        var sort={
        };
        table.GM('setSort',sort,function (){
        table.GM('setQuery', _query).GM('refreshGrid', function () {
			console.log('搜索成功...');
            });
        },false);`
这样做对么？但是没效果，麻烦给一个正确的例子参考一下...

**Comment by baukh789** [comment]
比如当前的排序为升序，且sortUpText、sortDownText未进行过配置。
那么执行以下步骤
```
// 更新排序数据， 但不刷新表格
document.querySelector('table').GM('setSort', {'name': 'DESC'}, undefined, false);
// 更新query 参数， 并刷新表格
document.querySelector('table').GM('setQuery',{'userName':'baukh','sex':'男'});
```

**Comment by Balis0ng** [comment]
emmm，失败了...还是会有上一次的表格排序...

**Comment by baukh789** [comment]
http://develop.lovejavascript.com/node_modules/GridManager/demo/demo2.html
你在demo文件上试一下

**Comment by Balis0ng** [comment]
不知为何，document.querySelector('table').GM('setQuery',{'userName':'baukh','sex':'男'})这个后面不接refreshGrid的话，表格不会刷新，也不会有请求发送，很奇怪。

**Comment by baukh789** [comment]
我给你提供的demo上是可以的，你更新下版本试一下。

**Comment by Balis0ng** [comment]
蓝瘦...原来是版本的问题...搞的我们不在一个频道....哈哈..现在可以了..谢谢啦..

**Comment by Balis0ng** [comment]
另外，问一个问题..有静态排序的功能么？因为目前得排序功能是要向服务端发送请求的..有没有那种可以在客户端完成的排序的功能。

**Comment by baukh789** [comment]
这个是没有的

**Comment by Balis0ng** [comment]
好吧，另外就是..右键表格有一个“重新加载"的功能，如何做到在重新加载的时候也去掉上一次的排序参数？

**Comment by Balis0ng** [comment]
另外，这个插件有单击某行数据所触发事件得功能么？

**Comment by baukh789** [comment]
> 另外，这个插件有单击某行数据所触发事件得功能么？
这个需要通过columnData. template自行配置
