### ISSUE TITLE
td保留值问题

### ISSUE THREAD

**Issue by ynnyh** [baukh789/GridManager#67]
表格中如果td是个下拉框，如果已经选中值的话，在对表格进行刷新操作或者检索操作时，该选中值不会被携带过来，而且操作DOM也并没有复原，请问是什么愿意呢？？？

**Comment by baukh789** [comment]
eg.
```javascript
// 配置项columnData
columnData: [{
	key: 'type',
	remind: 'the type',
	text: '分类',
	isShow: false,
	template: function(nodeData, rowObject){
		return `
		       <select>
				<option value="1" ${nodeData === 1 ? 'selected="selected"' : ''}>111</option>
				<option value="2" ${nodeData === 2 ? 'selected="selected"' : ''}>222</option>
			</select>`;
		}
	}]
```
如上所示
- 在执行刷新时， GridManager 都会使用 template 中返回的字符串，对td进行重新渲染。
- 如果没有配置 template ， 那么将会直接使用当前列配置项中的 key 对应的返回数据。

template 方法参数介绍: 
-  nodeData为返回数据中的type字段
-  rowObject为每一行使用的完整数据。

**Comment by ynnyh** [comment]
好的，谢谢哈，我当时确实是这样做的但是===用错了，类型不一样导致没有将值填入，我换成==就可以了。再次感谢!!!
