### ISSUE TITLE
关于动态渲染表头内容问题

### ISSUE THREAD

**Issue by kavizzz** [baukh789/GridManager#68]
其实工作中，更多的情况是 表头和内容都是动态渲染的。刚接触这个插件， 这个插件能根据数据动态渲染表头吗？

**Comment by silence717** [comment]
@kavizzz 同学，首先去读一下api文档看看能不能解答你的疑问，然后再搞清楚一下什么是issue可以不？这样很让人苦恼的。

**Comment by kavizzz** [comment]
@silence717  就是因为api上没有， 我才来这里问的啊，  其次， 在这里讨论这个问题 提出这个问题  有什么毛病？

**Comment by baukh789** [comment]
demo上有对应的一些示例，API上也有具体的使用方式。
关健的字段是ajax_url和columnData.

**Comment by kavizzz** [comment]
@baukh789 我的意思是，columnData的数组中，长度是动态的，每个对象中的 text、key也是动态的， 您的demo中，所有的columnData都是写死了的。有多少列， columnData中就有多少个对象， 其中的 key指向、text都是每个对应写好了的。

**Comment by baukh789** [comment]
渲染完成后对增加或减少列的操作是不被支持的，你可以尝试用以下方式进行解决：
将所有的列一起进行初始化，并且将一部分列设置为隐藏。
通过showTh和hideTh方法对列进行显示或隐藏操作。

**Comment by kavizzz** [comment]
@baukh789  大神，那么  在初始化的时候， 能进行动态填写text吗？
之前是这样的（有多少列就要写多少个对象）：
![default](https://user-images.githubusercontent.com/23111013/34334388-1e11fe6e-e981-11e7-940f-50f95e9ca8ba.png)
现在我想问问能这样吗？
![default](https://user-images.githubusercontent.com/23111013/34334413-5f70f93c-e981-11e7-8aba-bb6538bcb893.png)，
配置的时候只用填写 columnData: dataArr

**Comment by baukh789** [comment]
初始化前都是可以随意改动的, 注意必要的key值就可以了。

**Comment by kavizzz** [comment]
![default](https://user-images.githubusercontent.com/23111013/34334820-b9cb42d6-e984-11e7-8a87-417d07cb46d0.png)
我现在的数据如图， 我想  body的数据 就用这个table_data.body中的（这里没问题）， 问题在于  渲染每一列的标题  我想用table_data.head的数据来渲染，现在的问题是， 我在哪取这个head值，我的做法是： 在实例化GM之前写了一个ajax请求， 请求到这个数据， 然后用我之前一次回复中的 函数方法处理，然后 赋值给一个变量， 但是，当配置的时候， 并不能取到这个  dataArr的， 因为ajax还没完成的时候 就去执行了GM实例化， 而且GM实例化也不能写在ajax成功回调函数中，我现在就卡在这里了。。

**Comment by baukh789** [comment]
ajax_url返回的数据是在tbody里使用的，你这种操作我建意你还是拆接口或者是使用ajax_data去处理。
具体的你自已看一下吧

**Comment by kavizzz** [comment]
好的， 已经解决了， 谢谢 @baukh789
