### ISSUE TITLE
table跳转问题

### ISSUE THREAD

**Issue by ynnyh** [baukh789/GridManager#69]
在表格下方跳转至那里如果输入负数会发生序号错误现象。

**Comment by baukh789** [comment]
如你描述的方式，我并没有复现。
你可以在 http://develop.lovejavascript.com/node_modules/GridManager/demo/index.html
上复现一下， 并提供下描述的问题详细。 以方便我这边进行问题定位，3Q

**Comment by ynnyh** [comment]
在静态数据那里的表格里输入负数是可以复现的

**Comment by ynnyh** [comment]
意思是输入负数序号会错乱，但是数据实际还是第一页的数据，相当于一次刷新

**Comment by baukh789** [comment]
已复现，会尽快修复该问题。

**Comment by ynnyh** [comment]
好的，麻烦您了

**Comment by baukh789** [comment]
2.4.2已发布，该问题已修复。
