### ISSUE TITLE
关于分页的问题

### ISSUE THREAD

**Issue by luoyuchen** [baukh789/GridManager#70]
API中所述：
分页实现需要后端程序通过 GridManager 传递的参数[ cPage(当前页) 和 pSize(每页显示条数) ] 返回对应的数据。

这里的cPage和pSize该怎么传递，想用外部json模拟数据，可是分页不好使。入行不久，希望大神能担待我这个水平浅的问题。

**Comment by baukh789** [comment]
传递是由GridManager 自动传递的，是需要后端通过接收并根据这两个参数返回对应的列表数据。

**Comment by luoyuchen** [comment]
如果我只是从后端取回json数据，在前端进行分页，这样不行吗？

**Comment by luoyuchen** [comment]
我想说的是 我从后端取回了100条json数据，想在前端把这100条进行分页，该怎么分啊？API分页那里介绍的太笼统了，不明白

**Comment by baukh789** [comment]
需要后端根据cPage,pSize做为条件，返回对应的数据。
