### ISSUE TITLE
请问排序怎么传递查询条件给后端?

### ISSUE THREAD

**Issue by lytlucky** [baukh789/GridManager#72]
我这个查询条件是动态的.每次排序都有可能改变.现在好像只能传写死的值!
请问怎么在排序时获取这个值.我在排序前有设置data,但没有效果.

**Comment by lytlucky** [comment]
我的意思是除排序参数之外的其他查询条件.我在sortingBefore这个里有动态获取的条件但是后端还是没有接收到^_^.我就不知道怎么改了!

**Comment by baukh789** [comment]
查询条件通过setQuery进行设置。
具体的请参考API。

**Comment by lytlucky** [comment]
点击排序setQuery怎么写^_^

**Comment by lytlucky** [comment]
我在sortingBefore调用
table.GM('setQuery', _query).GM('refreshGrid', function () {console.log('搜索成功...');});
这样是能查询,但是这也相当于查询两遍,有没有其他办法可以在点击排序的时候把查询条件带进去?
table.GM({
	 ajax_url: 'rankVenderList.do'
	 ,ajax_type: 'GET'
	 ,query: {
		  'keywords' : $("#keywords").val()
	 }
});
这样写的话点击排序的时候keywords后端是接收不到值的!

**Comment by baukh789** [comment]
```javascript
table.GM('setQuery', _query, null, false).GM('refreshGrid', function () {console.log('搜索成功...');});
```
setQuery不允许传入分页排序相同的key

setSort第三个参数是用于指定是否刷新的

如上问题API上有详细的说明
