### ISSUE TITLE
关于表单查询使用序列化提交

### ISSUE THREAD

**Issue by Strive-Java** [baukh789/GridManager#73]
拭目以待 你好！我使用“setQuery”表单提交查询时发现，请求的参数name分开了。
代码如下：
       var _query = $("#qryUserForm").serialize();
       userList.GM('setQuery',_query);

请求参数如下：
![issu](https://user-images.githubusercontent.com/20058791/35185222-a3cdcb54-fe3b-11e7-88b3-a1eda532b954.png)

**Comment by Strive-Java** [comment]
已经找到解决的办法了：
解决方法如下：
$.fn.serializeJson=function(){
        	        var serializeObj={};
        	        var array=this.serializeArray();
        	        var str=this.serialize();
        	        $(array).each(function(){
        	            if(serializeObj[this.name]){
        	                if($.isArray(serializeObj[this.name])){
        	                    serializeObj[this.name].push(this.value);
        	                }else{
        	                    serializeObj[this.name]=[serializeObj[this.name],this.value];
        	                }
        	            }else{
        	                serializeObj[this.name]=this.value;
        	            }
        	        });
        	        return serializeObj;
        	    };

**Comment by baukh789** [comment]
你这个属于jquery获取formdata的问题，GridManager仅是将查询信息提供向接口提供方。
并不会对查询参进行处理
