### ISSUE TITLE
请求ajax_url时，报302错误

### ISSUE THREAD

**Issue by tenggua17800** [baukh789/GridManager#74]
ajax_url: '@Url.Action("GetDetail", "CardGroupSearchEditList")?rd=' + Math.random()，
请问下asp.net MVC模式下请求时，提示302错误，但是直接使用Ajax时该请求URL可以获取到Json数据，
看url解析地址也正确
请求网址：http://localhost:38086/CardGroupSearchEditList/GetDetail?rd=0.9618772678622732
请求方法：POST
远程地址：127.0.0.1:38086
状态码：302 Found

**Comment by baukh789** [comment]
在post请求中请不要使用 `?rd=' + Math.random()` ，而且这里也没有必要增加该参数。
如果需要传递请求参，请使用配置项 `query`进行设置。

**Comment by tenggua17800** [comment]
去掉?rd=' + Math.random()也一样 还是302错误，请问还有哪块有问题？
