### ISSUE TITLE
动态加载数据

### ISSUE THREAD

**Issue by tenggua17800** [baukh789/GridManager#75]
请问下http://www.lovejavascript.com/learnLinkManager/getLearnLinkList这个方法返回的结果集是Json还是List<T>，还是其它格式，为什么我动态加载时，Json和List=<T>等都不可以，每次请求都是302，也不请求方法。
版主求助啊啊啊
还是动态加载时Url不能用localhost请求？？？
急急急~~~
大神们解答下啊啊啊

**Comment by baukh789** [comment]
返回的是JSON
对于你所提的问题，你可以更换一个接口进行调试，或者使用静态json文件进行调试。
