### ISSUE TITLE
一个页面两个表格读取行数据混乱

### ISSUE THREAD

**Issue by AmazingXiaomi** [baukh789/GridManager#76]
我在一个页面中有两个表格，通过选择的tr读取其中一个表格的数据，但是读取到的数据是最近一个刷新的表格的数据，不是根据我传入的   'table[grid-manager="stdSpecData-ajaxPageCode"]' 获取的。
代码如下。
 var outTr = document.querySelector('table[grid-manager="outData-ajaxPageCode"]').GM('getCheckedTr');
        var StdTr = document.querySelector('table[grid-manager="stdSpecData-ajaxPageCode"]').GM('getCheckedTr');
         if (outTr && outTr.length == 1) {
                outData = document.querySelector('table[grid-manager="outData-ajaxPageCode"]').GM('getRowData', outData[key]);
         } else {
             layer.msg("勾选一条外部数据再进行操作！！");
             return;
         }

**Comment by baukh789** [comment]
看到你关闭了问题，应该是已经解决了。
如果还有类似的问题可以先在[develop demo](http://develop.lovejavascript.com/) 中进行测试。
这个地址是我自测使用的demo

**Comment by AmazingXiaomi** [comment]
没有解决，但是我们发现一个页面中的缓存只能保存一个最近刷新的表格的数据

**Comment by baukh789** [comment]
建议你到我上面提到的地址进行测试，并且确认是否为最新版本。
