### ISSUE TITLE
不兼容ie浏览器么???

### ISSUE THREAD

**Issue by meixiaohei** [baukh789/GridManager#78]
![image](https://user-images.githubusercontent.com/33745879/37443426-06d56308-2847-11e8-8e37-91314b85e8a9.png)

**Comment by baukh789** [comment]
是的
使用表格插件的大都是管理平台或系统,通常都是会进行浏览器指定,所以设计之初就没有考虑这个方面.

**Comment by meixiaohei** [comment]
那有没有什么办法解决???

**Comment by baukh789** [comment]
蛮遗憾的，目前GridManager还没有计划拥抱IE。
IE下可用代表着将会多出一些代码，而按目前的状态来看，这并不是必须的。
不过谢谢你的反馈，我会认真考虑下这种场景是否足够大。

**Comment by windancer79** [comment]
safari浏览器也有类似问题，若没有兼容升级计划，对这个错误提示能否给一些修改的建议

**Comment by deardirks** [comment]
公司项目写完了 发现不兼容IE....
