### ISSUE TITLE
拖曳调整每一列宽度的功能是否已废弃? 在官网的历程栏目中没找到相关说明

### ISSUE THREAD

**Issue by acc4mei** [baukh789/GridManager#81]
#### 浏览器 Firefox, GridManager v2.5
- 官网的demo两列之间还会自动提示 `<-||->` 的拖曳调整图标, 但是无作用 **实际测试2.0 版本中生效**

**Comment by baukh789** [comment]
首先十分感谢你的反馈，下列是所提问题的回复: 
- 问题一
     > 官网的demo两列之间还会自动提示 <-||-> 的拖曳调整图标, 但是无作用 实际测试2.0 版本中生效

     这个问题将在下个版本中被修复，发布后，我会在该issues中回复你。


- 问题二
     > 设置 supportMenu:false 后, 右键菜单依旧存在

     supportMenu:false 所禁用的仅是GirdManager所提供的快捷菜单， 并不是浏览器的默认右键菜单。

**Comment by baukh789** [comment]
@acc4mei 该问题已在v2.5.1中修复。

**Comment by acc4mei** [comment]
**问题二是我自己的缓存问题, 提错了**,  我修改了issue但好像github没及时更新过来... 现在issue只有一问题一了, 然后感谢及时修复问题一
