### ISSUE TITLE
如何实现checkbox的绑定选中？

### ISSUE THREAD

**Issue by cuitwangshicheng** [baukh789/GridManager#86]
我想实现编辑的时候，根据已有的数据显示某些行时选中的，有方案吗？

**Comment by cupPhone** [comment]
h

**Comment by cupPhone** [comment]
有复选框的选中事件么？     想实现的效果：选中某行的复选框，得到当前行的所有数据

**Comment by baukh789** [comment]
可以通过`getCheckedData `方法获取已选中的行的数据
或通过`getCheckedTr `方法获取已选中的行dom

行的选中不支持通过代码进行操作
单条行显中后没有事件进行接收，但是可以通过`getCheckedData`进行获取已选中的

或者可以将所遇到的详细场景进行描述，如果确实存在这种需求，会考虑对此进行升级。

**Comment by cuitwangshicheng** [comment]
获取数据确实没有问题，就是通过行的的主键来绑定已有的值，通常用在编辑的时候。这个现在我还没有找到合适的方法，就去手动遍历了每一行的数据，然后对比主键，将这一行的checbox选中
