### ISSUE TITLE
销毁实例报错

### ISSUE THREAD

**Issue by zoutianshu** [baukh789/GridManager#87]
调用销毁实例方法报错：Uncaught TypeError: Cannot read property '0' of undefined
代码是document.querySelector('table[grid-manager="managers"]').GM('destroy');

**Comment by zoutianshu** [comment]
能够正确找到，只有销毁方法是调用出错的

**Comment by baukh789** [comment]
[demo](http://develop.lovejavascript.com/node_modules/gridmanager/demo/demo1.html)
你通过这个Demo测试下，也有可能是版本问题
