### ISSUE TITLE
建议优化GridManager请求和返回参数的处理方式

### ISSUE THREAD

**Issue by 464193096** [baukh789/GridManager#88]
目前是通过这种方式改变参数值，个人觉得不实用 复杂
document.querySelector('table').GM('init', {
    responseHandler: function(response){
        response.list = response.data;
    },
    // 其它配置项...
});

建议table.GM 加个request参数处理
request: {
  pageName: 'curr' //页码的参数名称，默认：page
  ,limitName: 'nums' //每页数据量的参数名，默认：limit
}  
同理 加个repose 处理请求返回的参数key
response: {
  statusName: 'status' //数据状态的字段名称，默认：code
  ,statusCode: 200 //成功的状态码，默认：0
  ,msgName: 'hint' //状态信息的字段名称，默认：msg
  ,countName: 'total' //数据总数的字段名称，默认：count
  ,dataName: 'rows' //数据列表的字段名称，默认：data
}  

有效解决不需要改后台框架情况下使用GridManager插件

**Comment by baukh789** [comment]
v2.6.0已发布，对该问题已进行了优化, 与本问题相关的项:
- `currentPageKey`: 请求参数中当前页key键值,默认为cPage
- `pageSizeKey`: 请求参数中每页显示条数key健值, 默认为pSize
- `requestHandler` 与 `responseHandler` 由直接修改实参优化为通过`return`进行结果返回

其它如返回数据格式的调整参数，在之前版本中就已实现。
具体请参考[API](http://gridmanager.lovejavascript.com/api/index.html)
