### ISSUE TITLE
请问动态获取数据时，ajax_url指向的部分的格式是什么

### ISSUE THREAD

**Issue by chemist0086** [baukh789/GridManager#9]
首先感谢提供了一个这么好用的表格插件！
我准备动态获取数据，但是没有看懂demo中ajax_url指向的数据源的格式是什么，请问能否说明一下。谢谢。

**Comment by baukh789** [comment]
![image](https://cloud.githubusercontent.com/assets/11342827/24838236/e2b1c93e-1d76-11e7-9f53-25465d501957.png)
GridManager后端返回数据仅需要以下两个键值，具体可以通过开发者工具查看demo中使用的接口。
{
data: [], // 当前页列表数据
totals:  10 // 总条数
}

**Comment by chemist0086** [comment]
后端用的是stuts框架，现在已经能够解决列表显示的问题，但是在正确设置了query的值以后，列表没有办法根据query的值加载内容，仍然是全部数据都显示出来。使用setQuery设置query然后refreshGrid也没有用。请问有没有办法解决，谢谢！

**Comment by baukh789** [comment]
类似于这样进行设置query及刷新
```javascript
table.GM('setQuery', _query).GM('refreshGrid', function () {
      console.log('搜索成功...');
});
```

给你一个我自测该功能使用的demo做为参考
http://www.lovejavascript.com/node_modules/GridManager/demo/index.html

**Comment by chemist0086** [comment]
我query设置的值是正确的，也调用了函数进行刷新，但是刷新后的页面仍然没有变化。
我的设置如下：
query: {"pass_id" : “1111”}
测试数据：
"data":[{"pass_id":"5005","pass_name":"罗嘉言","pass_age":"28","pass_sex":"男"},{"pass_id":"5214","pass_name":"马兴生","pass_age":"43","pass_sex":"男"}]
调用
table.GM('refreshGrid', function () {
      console.log('搜索成功...');
});
回调函数能够执行。但是页面任然显示原始数据。

感谢解答！

**Comment by baukh789** [comment]
分析后，以为是后端未能正确获取并处理参数导致的。
你要以在后端接口内打断点进行验证，是否可以正确的获取到传参pass_id, 并且正确的使用到了pass_id.

GridManager与jQuery并不冲突，不会相互影响

另外，在渲染表格进行query属性赋值，是不需要调用setQuery 及 refreshGrid 方法的。如：
![image](https://cloud.githubusercontent.com/assets/11342827/24890732/24953dc6-1ea4-11e7-84fb-585f7c327f42.png)


setQuery 及 refreshGrid 方法主要是用于手动触发的搜索功能。如：
![image](https://cloud.githubusercontent.com/assets/11342827/24890748/328efc6e-1ea4-11e7-9d1b-2214040db316.png)


建议你确认下后端返回，如果后端返回正常。请参考demo: http://www.lovejavascript.com/node_modules/GridManager/demo/demo2.html
进行调整，该demo包含初始query设置及手动触发搜索功能

**Comment by chemist0086** [comment]
通过实例化的时候设置query的值或者使用setQuery设置query的值都没有办法按照条件正常的渲染表格。
可能是我对demo没有理解。请问搜索功能是需要向后端传参，然后由后端返回搜索后的data列表的吗？谢谢。

**Comment by baukh789** [comment]
是的，是对后端进行传参。需要在后端对该接口进行参数接收并返回相应数据。

**Comment by chemist0086** [comment]
请问在哪里设置后端接受参数的url呢

**Comment by baukh789** [comment]
参数ajax_url， 就是这个查询接口url

**Comment by chemist0086** [comment]
后端使用的struts2框架，应该使用什么方法接受参数呢？
实在不好意思，我是初学者，多有打扰。

**Comment by baukh789** [comment]
后端的解决方案需要你自已解决了

**Comment by chemist0086** [comment]
我使用HttpServletRequest的getParameter()没有办法获取到参数。不知道query参数是以什么形式传递到后端的。

**Comment by baukh789** [comment]
Request Payload

**Comment by baukh789** [comment]
![image](https://cloud.githubusercontent.com/assets/11342827/24893307/9551a868-1eb5-11e7-9a59-baf777dfcc42.png)
如图所示，你可以通过以下方式来修改参数传递形式
1.更改ajax_type 为 GET。
2.如何必须使用POST， 增加配置参数
```javascript
ajax_headers: {"Content-Type": "application/x-www-form-urlencoded"}
```

**Comment by chemist0086** [comment]
非常感谢！问题解决了。
新人刚刚开始学习，十分感谢陈老师指导！
