### ISSUE TITLE
能否提供编辑内嵌控件功能，还有多表头，锁定列，还有分组功能。

### ISSUE THREAD

**Issue by yangyuanlife** [baukh789/GridManager#91]
这个是蛮轻量级的，一看就是喜欢用的表格。但是能否提供编辑内嵌控件功能，还有多表头，锁定列，还有分组功能。如果加上这几种功能，基本上能使用90%以上的业务场景了。

**Comment by baukh789** [comment]
谢谢反馈，这些近期不在开发计划内。
我调研下具体的影响，如果可行的话会考虑增加。

再次感谢反馈
