### ISSUE TITLE
官网提供的下载的gm.js还有对应的css能否提供sources

### ISSUE THREAD

**Issue by yangyuanlife** [baukh789/GridManager#96]
官网http://gridmanager.lovejavascript.com/提供的下载的gm.js还有对应的css能否提供sources，因为项目没用用到require，本人对webpackage还有node真是不熟，环境搭建了半天还是不能用来着。

**Comment by baukh789** [comment]
暂时不会，因为暂时未发现可使用的场景。
至于环境搭建你可以了解下 `readme/DEVELOP_README.md`
祝你工作娱快
