### ISSUE TITLE
remind 当只设置某几列的时候显示有问题。

### ISSUE THREAD

**Issue by yangyuanlife** [baukh789/GridManager#98]
,columnData: [{
			key: 'name',
			width: '100px',
			text: '名称',
			sorting: 'DESC'
		},{
			key: 'info',
      remind: 'the info',
			text: '使用说明',
			sorting: ''
		},{
			key: 'url',
			text: 'url'
		}
		}
		]

如上设置，只设置了info列的remind，可是显示的时候最后一列remind也出来了，而且显示的内容跟info列的remind一样

**Comment by yangyuanlife** [comment]
用官网的2.6.0版本测试的

**Comment by baukh789** [comment]
这个BUG已经修复了，本周未发布。

**Comment by baukh789** [comment]
2.6.1中该BUG已修复，请更新版本
