### ISSUE TITLE
有多级表头么？

### ISSUE THREAD

**Issue by cupPhone** [baukh789/GridManager#99]
可以实现多级表头么？
另外，为什么设置了disableCache: true之后，每次请求接口的时候，就不再带分页的参数cPage和pSize了

**Comment by baukh789** [comment]
- 暂不支持多级表头
- `disableCache: true`的问题已经修复，本周会发新版本

**Comment by baukh789** [comment]
2.6.1中该BUG已修复，请更新版本。

**Comment by cupPhone** [comment]
vue版本也更新了么

**Comment by baukh789** [comment]
是的对应的Vue版本是0.1.15
